using System.Reflection;
using WAID.Application.Abstractions;
using WAID.Application.Services;
using WAID.Domain.Repairs;
using WAID.Infrastructure.Plugins;
namespace WAID.Infrastructure.Automation;
public sealed class WaidCliRuntime(ScanOrchestrator scanner,IScanRepository scans,IDiagnosisRepository diagnoses,IDiagnosticsExportService exports,IReliabilityTimelineRepository timeline,IEnterprisePolicyService policy,IPluginInventoryRepository plugins,IRepairOrchestrationRepository plans,RepairOrchestrator repairs,RepairRegistry repairRegistry,IAdministratorService administrator,IDatabaseMaintenanceService database,WaidModuleCatalog modules,IAuditTrailService audit,TimeProvider time):IWaidCliRuntime
{
 public async Task<CliResult>ExecuteAsync(CliRequest request,IProgress<string>?progress,CancellationToken token){var result=request.Command switch{"version"=>Version(),"status"=>await Status(token),"scan"=>await Scan(progress,token),"findings"=>await Findings(request,token),"report"=>await Report(request,token),"timeline"=>await Timeline(request,token),"policy"=>await Policy(request,token),"plugins"=>await Plugins(token),"repair-plan"=>await RepairPlan(request,progress,token),_=>CliResult.Failure(CliExitCode.Usage,"WAID-CLI-COMMAND","Unknown command.","Run 'waid help'.")};await Record(request,result,token);return result;}
 CliResult Version()=>CliResult.Success(new{applicationVersion=Assembly.GetEntryAssembly()?.GetName().Version?.ToString()??Assembly.GetExecutingAssembly().GetName().Version?.ToString()??"unknown",cliSchema=WaidCliApplication.SchemaVersion,framework=System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription});
 async Task<CliResult>Status(CancellationToken token){var health=await database.CheckHealthAsync(token);return CliResult.Success(new{database=new{health.State,health.SchemaVersion,health.SupportedSchemaVersion,health.JournalMode,health.LastMigration,health.Detail},modules=modules.Items.Select(x=>new{x.Id,x.DisplayName,x.State,x.Detail}),policy=new{policy.Current.State,policy.Current.Fingerprint,policy.Current.Explanation}});}
 async Task<CliResult>Scan(IProgress<string>?progress,CancellationToken token){progress?.Report("Planning WAID scanners...");var scanProgress=new Progress<ScanProgress>(x=>progress?.Report($"{x.CompletedScanners}/{x.TotalScanners} {x.ScannerId}: {x.Status}"));var session=await scanner.RunAsync(administrator.IsAdministrator(),scanProgress,token);progress?.Report("Scan completed and persisted.");return CliResult.Success(new{session.Id,session.StartedAtUtc,session.CompletedAtUtc,findings=session.Findings.Count,critical=session.Findings.Count(x=>x.Severity==WAID.Domain.Diagnostics.DiagnosticSeverity.Critical)});}
 async Task<CliResult>Findings(CliRequest request,CancellationToken token){var limit=Limit(request,100,1,500);var sessions=await scans.GetRecentAsync(25,token);var items=sessions.SelectMany(x=>x.Findings.Select(f=>new{x.Id,sessionId=x.Id,f.ScannerId,f.Code,f.Title,f.Description,severity=f.Severity.ToString()})).Take(limit).ToArray();return CliResult.Success(new{count=items.Length,items});}
 async Task<CliResult>Report(CliRequest request,CancellationToken token){if(request.Option("export") is{ }format){if(!format.Equals("package",StringComparison.OrdinalIgnoreCase))return CliResult.Failure(CliExitCode.Usage,"WAID-CLI-REPORT-FORMAT","Only the redacted package export is supported by this command.","Use --export package.");var path=await exports.ExportAsync(token);return CliResult.Success(new{format="zip",path=SafePath(path)});}var report=await diagnoses.GetLatestAsync(token);return report is null?CliResult.Failure(CliExitCode.NotFound,"WAID-CLI-REPORT-NOTFOUND","No diagnosis report is available.","Run a scan and diagnosis in WAID first."):CliResult.Success(report);}
 async Task<CliResult>Timeline(CliRequest request,CancellationToken token){var limit=Limit(request,50,1,200);var page=await timeline.QueryAsync(new(0,limit),token);return CliResult.Success(new{page.TotalCount,events=page.Items});}
 async Task<CliResult>Policy(CliRequest request,CancellationToken token){var snapshot=request.Flag("refresh")?await policy.RefreshAsync(token):policy.Current;return CliResult.Success(new{snapshot.State,snapshot.Fingerprint,snapshot.EvaluatedAtUtc,snapshot.Explanation,snapshot.FailureCode,snapshot.Retention,rules=Enum.GetValues<EnterpriseCapability>().Select(policy.Evaluate)});}
 async Task<CliResult>Plugins(CancellationToken token){var items=(await plugins.GetAllAsync(token)).Select(x=>new{x.Id,x.Name,x.Version,x.State,x.Certified,x.SignatureStatus,x.Capabilities,x.Permissions,x.Detail,x.UpdatedAtUtc});return CliResult.Success(new{items});}
 async Task<CliResult>RepairPlan(CliRequest request,IProgress<string>?progress,CancellationToken token){if(request.Subcommand=="list"){var limit=Limit(request,25,1,100);return CliResult.Success(new{plans=await plans.GetRecentAsync(limit,token)});}if(request.Subcommand=="simulate"){var id=request.Option("repair");if(string.IsNullOrWhiteSpace(id)||!repairRegistry.TryGet(id,out _))return CliResult.Failure(CliExitCode.NotFound,"WAID-CLI-REPAIR-NOTFOUND","The repair identifier is not registered.","Run repair-plan list or review recommended repairs.");progress?.Report("Creating a read-only repair simulation; no system command will run...");var record=await repairs.AssessAndSimulateAsync(new(id,null,new HashSet<string>(StringComparer.OrdinalIgnoreCase),new HashSet<string>(StringComparer.OrdinalIgnoreCase)),null,token);return CliResult.Success(new{record.Id,record.RepairId,record.Stage,record.Simulation,record.Outcome,executionConfirmation=$"EXECUTE WAID REPAIR {record.Id:D}"});}if(request.Subcommand=="execute"){if(!Guid.TryParse(request.Option("id"),out var id))return CliResult.Failure(CliExitCode.Usage,"WAID-CLI-PLAN-ID","A valid --id GUID is required.","Copy the plan ID from repair-plan simulate or list.");if(!RepairExecutionConfirmation.IsValid(request,id,out var expected))return CliResult.Failure(CliExitCode.Conflict,"WAID-CLI-REPAIR-CONFIRMATION","Repair execution requires --approve, --acknowledge-risk, and the exact plan-bound confirmation phrase.",$"Use --confirmation \"{expected}\" only after reviewing the current simulation.");var existing=await plans.GetAsync(id,token);if(existing is null)return CliResult.Failure(CliExitCode.NotFound,"WAID-CLI-PLAN-NOTFOUND","The repair plan does not exist.","Create and review a new simulation.");if(existing.Stage!=RepairOrchestrationStage.AwaitingApproval)return CliResult.Failure(CliExitCode.Conflict,"WAID-CLI-PLAN-STATE",$"Plan state {existing.Stage} cannot execute.","Create or refresh a plan that is awaiting approval.");progress?.Report("Executing the explicitly approved plan through WAID safety, backup, restore-point, validation, and rollback gates...");var record=await repairs.ExecuteAsync(id,true,true,null,token,"CLI");return CliResult.Success(new{record.Id,record.RepairId,record.Stage,record.TransactionStatus,record.RestartRequired,record.Validation,record.Outcome});}return CliResult.Failure(CliExitCode.Usage,"WAID-CLI-REPAIR-SUBCOMMAND","A repair-plan subcommand is required.","Use list, simulate, or execute.");}
 static int Limit(CliRequest request,int defaultValue,int minimum,int maximum){if(request.Option("limit") is not{ }value)return defaultValue;if(!int.TryParse(value,System.Globalization.NumberStyles.None,System.Globalization.CultureInfo.InvariantCulture,out var parsed)||parsed<minimum||parsed>maximum)throw new CliParseException($"--limit must be between {minimum} and {maximum}.");return parsed;}
 async Task Record(CliRequest request,CliResult result,CancellationToken token){var mutation=request.Command=="repair-plan"&&request.Subcommand is "simulate" or "execute";await audit.AppendAsync(new(Guid.NewGuid(),time.GetUtcNow(),AuditActor.Cli,"CliCommand",$"{request.Command}:{request.Subcommand??"none"}",result.Succeeded?AuditResult.Succeeded:AuditResult.Rejected,mutation?SafetyLevel.High:SafetyLevel.Low,request.Subcommand=="execute",request.Subcommand=="execute",Guid.NewGuid(),Guid.NewGuid(),$"CLI command completed with exit code {(int)result.ExitCode}; no command arguments or secrets recorded."),token);}
 static string SafePath(string path){var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);return string.IsNullOrWhiteSpace(profile)?path:path.Replace(profile,"%USERPROFILE%",StringComparison.OrdinalIgnoreCase);}
}