using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using WAID.Desktop.ViewModels;
using WAID.Desktop.Views;
namespace WAID.Desktop;
public sealed partial class MainWindow : Window
{
    private readonly WAID.Infrastructure.Plugins.PluginCatalog _plugins; private readonly WAID.Infrastructure.WaidModuleCatalog _modules;
    private readonly LiveMonitoringViewModel _liveMonitoring; private readonly PredictiveHealthViewModel _predictive; private readonly KnowledgeViewModel _knowledge; private readonly EvidenceExplorerViewModel _evidence; private readonly DashboardViewModel _dashboard; private readonly DiagnosisViewModel _diagnosis; private readonly SettingsViewModel _settings; private readonly HistoryViewModel _history; private readonly OperationsViewModel _operations; private readonly AuditViewModel _audit; private readonly DriverHealthViewModel _drivers; private readonly BootHealthViewModel _boot; private readonly UpdateHealthViewModel _updates; private readonly StorageCenterViewModel _storage; private readonly SecurityCenterViewModel _security; private readonly NetworkHealthViewModel _network; private readonly ChatViewModel _chat;
    public MainWindow(DashboardViewModel dashboard,DiagnosisViewModel diagnosis,SettingsViewModel settings,HistoryViewModel history,OperationsViewModel operations,AuditViewModel audit,DriverHealthViewModel drivers,BootHealthViewModel boot,UpdateHealthViewModel updates,StorageCenterViewModel storage,SecurityCenterViewModel security,NetworkHealthViewModel network,ChatViewModel chat,EvidenceExplorerViewModel evidence,KnowledgeViewModel knowledge,PredictiveHealthViewModel predictive,LiveMonitoringViewModel liveMonitoring,WAID.Infrastructure.Plugins.PluginCatalog plugins,WAID.Infrastructure.WaidModuleCatalog modules) { InitializeComponent(); _dashboard=dashboard; _diagnosis=diagnosis; _settings=settings; _history=history; _operations=operations;_audit=audit;_drivers=drivers;_boot=boot;_updates=updates;_storage=storage;_security=security;_network=network;_chat=chat;_evidence=evidence;_knowledge=knowledge;_predictive=predictive;_liveMonitoring=liveMonitoring;_plugins=plugins;_modules=modules; Navigation.SelectedItem=Navigation.MenuItems[0]; ShowDashboard(); }
    private void OnSelectionChanged(NavigationView sender,NavigationViewSelectionChangedEventArgs args) { if(args.IsSettingsSelected){ContentFrame.Content=new SettingsPage(_settings);return;} var tag=(args.SelectedItem as NavigationViewItem)?.Tag as string; ContentFrame.Content=tag switch{"drivers"=>new DriverHealthPage(_drivers),"boot"=>new BootHealthPage(_boot),"updates"=>new UpdateHealthPage(_updates),"storage"=>new StorageCenterPage(_storage),"security"=>new SecurityCenterPage(_security),"network"=>new NetworkHealthPage(_network),"chat"=>new ChatPage(_chat),"evidence"=>new EvidenceExplorerPage(_evidence),"knowledge"=>new KnowledgePage(_knowledge),"diagnosis"=>new DiagnosisPage(_diagnosis),"health"=>new HealthPage(_diagnosis),"predictive"=>new PredictiveHealthPage(_predictive),"live-monitoring"=>new LiveMonitoringPage(_liveMonitoring),"operations"=>new OperationsPage(_operations),"recommended"=>new RecommendedRepairsPage(_diagnosis,_dashboard),"history"=>new HistoryPage(_history),"audit"=>new AuditPage(_audit),"plugins"=>new PluginsPage(_plugins,_modules),_=>new DashboardPage(_dashboard)}; }
    private void ShowDashboard()=>ContentFrame.Content=new DashboardPage(_dashboard);
}
