using System.Reflection;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using WAID.Desktop.ViewModels;
using WAID.Desktop.Views;
using WAID.Infrastructure;
namespace WAID.Desktop;
public sealed partial class MainWindow : Window
{
    private readonly EnterprisePolicyViewModel _enterprisePolicy; private readonly WAID.Infrastructure.Plugins.PluginCatalog _plugins; private readonly WAID.Infrastructure.Plugins.PluginManager _pluginManager; private readonly WAID.Infrastructure.WaidModuleCatalog _modules;
    private readonly TechnicianDashboardViewModel _technician; private readonly RepairOrchestrationViewModel _repairOrchestration; private readonly NotificationCenterViewModel _notifications; private readonly DigitalTwinViewModel _digitalTwin; private readonly PerformanceHistoryViewModel _performanceHistory; private readonly ReliabilityTimelineViewModel _reliabilityTimeline; private readonly LiveMonitoringViewModel _liveMonitoring; private readonly PredictiveHealthViewModel _predictive; private readonly KnowledgeViewModel _knowledge; private readonly EvidenceExplorerViewModel _evidence; private readonly DashboardViewModel _dashboard; private readonly DiagnosisViewModel _diagnosis; private readonly SettingsViewModel _settings; private readonly HistoryViewModel _history; private readonly OperationsViewModel _operations; private readonly CaseExchangeViewModel _caseExchange; private readonly AuditViewModel _audit; private readonly DriverHealthViewModel _drivers; private readonly BootHealthViewModel _boot; private readonly UpdateHealthViewModel _updates; private readonly StorageCenterViewModel _storage; private readonly SecurityCenterViewModel _security; private readonly NetworkHealthViewModel _network; private readonly ChatViewModel _chat;
    public MainWindow(IWaidWorkspaceContext workspace,TechnicianDashboardViewModel technician,DashboardViewModel dashboard,DiagnosisViewModel diagnosis,SettingsViewModel settings,HistoryViewModel history,OperationsViewModel operations,CaseExchangeViewModel caseExchange,AuditViewModel audit,DriverHealthViewModel drivers,BootHealthViewModel boot,UpdateHealthViewModel updates,StorageCenterViewModel storage,SecurityCenterViewModel security,NetworkHealthViewModel network,ChatViewModel chat,EvidenceExplorerViewModel evidence,KnowledgeViewModel knowledge,PredictiveHealthViewModel predictive,LiveMonitoringViewModel liveMonitoring,ReliabilityTimelineViewModel reliabilityTimeline,PerformanceHistoryViewModel performanceHistory,DigitalTwinViewModel digitalTwin,NotificationCenterViewModel notifications,RepairOrchestrationViewModel repairOrchestration,EnterprisePolicyViewModel enterprisePolicy,WAID.Infrastructure.Plugins.PluginCatalog plugins,WAID.Infrastructure.Plugins.PluginManager pluginManager,WAID.Infrastructure.WaidModuleCatalog modules) { InitializeComponent(); var releaseVersion=typeof(MainWindow).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion??"unknown";var channel=releaseVersion.Contains('-',StringComparison.Ordinal)?"Unsigned development channel":"Stable channel";WorkspaceIndicator.Text=(workspace.Status.Mode==WaidStorageMode.Portable?$"Portable | {workspace.Status.RootPath}":"Installed workspace")+$" | Version {releaseVersion} | {channel}";Title=workspace.Status.Mode==WaidStorageMode.Portable?"Windows AI Doctor - Portable":channel.StartsWith("Unsigned",StringComparison.Ordinal)?"Windows AI Doctor - Development":"Windows AI Doctor"; _technician=technician; _dashboard=dashboard; _diagnosis=diagnosis; _settings=settings; _history=history; _operations=operations;_caseExchange=caseExchange;_audit=audit;_drivers=drivers;_boot=boot;_updates=updates;_storage=storage;_security=security;_network=network;_chat=chat;_evidence=evidence;_knowledge=knowledge;_predictive=predictive;_liveMonitoring=liveMonitoring;_reliabilityTimeline=reliabilityTimeline;_performanceHistory=performanceHistory;_digitalTwin=digitalTwin;_notifications=notifications;_repairOrchestration=repairOrchestration;_enterprisePolicy=enterprisePolicy;_notifications.NavigationRequested+=NavigateToAlertTarget;_plugins=plugins;_pluginManager=pluginManager;_modules=modules; Navigation.SelectedItem=Navigation.MenuItems[0]; ShowDashboard(); }
    private void OnSelectionChanged(NavigationView sender,NavigationViewSelectionChangedEventArgs args) { if(args.IsSettingsSelected){ContentFrame.Content=new SettingsPage(_settings);return;} var tag=(args.SelectedItem as NavigationViewItem)?.Tag as string; ContentFrame.Content=tag switch{"technician"=>new TechnicianDashboardPage(_technician),"drivers"=>new DriverHealthPage(_drivers),"boot"=>new BootHealthPage(_boot),"updates"=>new UpdateHealthPage(_updates),"storage"=>new StorageCenterPage(_storage),"security"=>new SecurityCenterPage(_security),"network"=>new NetworkHealthPage(_network),"chat"=>new ChatPage(_chat),"evidence"=>new EvidenceExplorerPage(_evidence),"knowledge"=>new KnowledgePage(_knowledge),"diagnosis"=>new DiagnosisPage(_diagnosis),"health"=>new HealthPage(_diagnosis),"predictive"=>new PredictiveHealthPage(_predictive),"live-monitoring"=>new LiveMonitoringPage(_liveMonitoring),"reliability-timeline"=>new ReliabilityTimelinePage(_reliabilityTimeline),"performance-history"=>new PerformanceHistoryPage(_performanceHistory),"digital-twin"=>new DigitalTwinPage(_digitalTwin),"notifications"=>new NotificationCenterPage(_notifications),"operations"=>new OperationsPage(_operations),"case-exchange"=>new CaseExchangePage(_caseExchange),"recommended"=>new RecommendedRepairsPage(_diagnosis,_dashboard),"repair-lifecycle"=>new RepairOrchestrationPage(_repairOrchestration),"history"=>new HistoryPage(_history),"audit"=>new AuditPage(_audit),"enterprise-policy"=>new EnterprisePolicyPage(_enterprisePolicy),"plugins"=>new PluginsPage(_plugins,_pluginManager,_modules),_=>new DashboardPage(_dashboard)}; }
    private void NavigateToAlertTarget(string target){var tag=target switch{"waid://live-monitoring"=>"live-monitoring","waid://storage"=>"storage","waid://security"=>"security","waid://updates"=>"updates","waid://network"=>"network",_=>null};if(tag is null)return;var item=Navigation.MenuItems.OfType<NavigationViewItem>().FirstOrDefault(x=>string.Equals(x.Tag as string,tag,StringComparison.OrdinalIgnoreCase));if(item is not null)Navigation.SelectedItem=item;}
    private void ShowDashboard()=>ContentFrame.Content=new DashboardPage(_dashboard);
}
