using System.Reflection;using System.Security.Cryptography;using System.Text;using System.Text.Json;using System.Text.RegularExpressions;
namespace WAID.KnowledgeBase;
public enum KnowledgeTrustLevel{Official,Curated,Community,Plugin}
public sealed record KnowledgeArticle(string Id,string Title,string Summary,string Body,IReadOnlyList<string> Errors,IReadOnlyList<string> Symptoms,IReadOnlyList<string> Prerequisites,IReadOnlyList<string> Risks,IReadOnlyList<string> SupportedOsVersions,string? RepairGuidance,IReadOnlyList<string> References,string Source,string License,KnowledgeTrustLevel TrustLevel,string Checksum,DateTimeOffset PublishedAtUtc,DateTimeOffset ReviewedAtUtc);
public sealed record KnowledgeCatalog(string KnowledgeVersion,string IndexVersion,IReadOnlyList<KnowledgeArticle> Articles);
public sealed record KnowledgeQuery(string Text,string OsVersion,IReadOnlyCollection<string> EvidenceCodes,int Limit=20);
public sealed record KnowledgeSearchResult(KnowledgeArticle Article,double Score,bool IsCompatible,IReadOnlyList<string> MatchedEvidence,string Applicability,string ContentLabel,string? TrustedRepairGuidance);
public sealed record KnowledgeIndexDocument(string KnowledgeVersion,string IndexVersion,string Checksum,DateTimeOffset BuiltAtUtc,IReadOnlyList<KnowledgeArticle> Articles);
public static class KnowledgeChecksum{public static string ForText(string value)=>"sha256:"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();}
public sealed class KnowledgeIndexException(string code,string message,Exception? inner=null):InvalidOperationException(message,inner){public string Code{get;}=code;}
public interface IKnowledgeRetrievalService{Task RebuildAsync(CancellationToken token);IReadOnlyList<KnowledgeSearchResult> Search(KnowledgeQuery query);KnowledgeIndexDocument LoadValidatedIndex();}
public sealed class OfflineKnowledgeRetrievalService:IKnowledgeRetrievalService
{
 private static readonly Regex Token=new("[A-Za-z0-9_.-]{2,}",RegexOptions.Compiled,TimeSpan.FromMilliseconds(100));private static readonly string[] Hostile=["ignore previous","system prompt","<script","javascript:","powershell -encoded","execute this command"];
 private readonly string _path;private readonly TimeProvider _time;private KnowledgeIndexDocument _snapshot;
 public OfflineKnowledgeRetrievalService(string path,TimeProvider time):this(path,time,LoadEmbedded()){}
 public OfflineKnowledgeRetrievalService(string path,TimeProvider time,KnowledgeCatalog catalog){_path=Path.GetFullPath(path);_time=time;Validate(catalog);_snapshot=Build(catalog);if(File.Exists(_path)){try{_snapshot=LoadValidatedIndex();}catch(KnowledgeIndexException){RebuildAsync(CancellationToken.None).GetAwaiter().GetResult();}}else RebuildAsync(CancellationToken.None).GetAwaiter().GetResult();}
 public async Task RebuildAsync(CancellationToken token){var data=JsonSerializer.SerializeToUtf8Bytes(_snapshot,new JsonSerializerOptions(JsonSerializerDefaults.Web));Directory.CreateDirectory(Path.GetDirectoryName(_path)!);var temp=_path+"."+Guid.NewGuid().ToString("N")+".tmp";try{await File.WriteAllBytesAsync(temp,data,token);File.Move(temp,_path,true);}finally{if(File.Exists(temp))File.Delete(temp);}}
 public KnowledgeIndexDocument LoadValidatedIndex(){try{var bytes=File.ReadAllBytes(_path);var value=JsonSerializer.Deserialize<KnowledgeIndexDocument>(bytes,new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new KnowledgeIndexException("WAID-KB-CORRUPT","Knowledge index is empty.");if(value.Checksum!=Checksum(value.Articles))throw new KnowledgeIndexException("WAID-KB-CHECKSUM","Knowledge index checksum validation failed.");Validate(new(value.KnowledgeVersion,value.IndexVersion,value.Articles));return value;}catch(KnowledgeIndexException){throw;}catch(Exception e)when(e is IOException or JsonException){throw new KnowledgeIndexException("WAID-KB-CORRUPT","Knowledge index is corrupt or unavailable.",e);}}
 public IReadOnlyList<KnowledgeSearchResult> Search(KnowledgeQuery query){if(string.IsNullOrWhiteSpace(query.Text)||query.Text.Length>500)throw new ArgumentException("Search text must contain 1-500 characters.");var terms=Token.Matches(query.Text).Select(x=>x.Value).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();var os=Version.TryParse(query.OsVersion,out var parsed)?parsed:null;return _snapshot.Articles.Select(a=>Rank(a,terms,query.EvidenceCodes,os)).Where(x=>x.Score>0).OrderByDescending(x=>x.Score).ThenByDescending(x=>x.Article.ReviewedAtUtc).ThenBy(x=>x.Article.Id,StringComparer.Ordinal).Take(Math.Clamp(query.Limit,1,100)).ToArray();}
 private KnowledgeSearchResult Rank(KnowledgeArticle a,string[] terms,IReadOnlyCollection<string> evidence,Version? os){var searchable=$"{a.Title} {a.Summary} {a.Body} {string.Join(' ',a.Errors)} {string.Join(' ',a.Symptoms)}";double score=terms.Sum(t=>a.Title.Contains(t,StringComparison.OrdinalIgnoreCase)?8:searchable.Contains(t,StringComparison.OrdinalIgnoreCase)?2:0);var matched=a.Errors.Concat(a.Symptoms).Intersect(evidence,StringComparer.OrdinalIgnoreCase).ToArray();score+=matched.Length*12;var compatible=Compatible(a,os);score+=compatible?4:-20;score+=a.TrustLevel switch{KnowledgeTrustLevel.Official=>4,KnowledgeTrustLevel.Curated=>2,_=>0};var age=(_time.GetUtcNow()-a.ReviewedAtUtc).TotalDays;score+=age<=365?2:age<=1095?1:0;var trusted=a.TrustLevel is KnowledgeTrustLevel.Official or KnowledgeTrustLevel.Curated?a.RepairGuidance:null;var label=a.TrustLevel is KnowledgeTrustLevel.Community or KnowledgeTrustLevel.Plugin?$"{a.TrustLevel} content — informational only":"WAID trusted content";return new(a,score,compatible,matched,compatible?"Applicable to this Windows version":"Not listed as compatible with this Windows version",label,trusted);}
 private static bool Compatible(KnowledgeArticle a,Version? os)=>os is null||a.SupportedOsVersions.Any(x=>x=="Windows 10+"||x=="Windows 11"&&os.Major>=10&&os.Build>=22000||x=="Windows 10"&&os.Major==10&&os.Build<22000);
 private KnowledgeIndexDocument Build(KnowledgeCatalog c)=>new(c.KnowledgeVersion,c.IndexVersion,Checksum(c.Articles),_time.GetUtcNow(),c.Articles);
 private static void Validate(KnowledgeCatalog c){if(string.IsNullOrWhiteSpace(c.KnowledgeVersion)||string.IsNullOrWhiteSpace(c.IndexVersion)||c.Articles.Count==0)throw new KnowledgeIndexException("WAID-KB-SCHEMA","Knowledge catalog metadata or articles are missing.");if(c.Articles.Select(x=>x.Id).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=c.Articles.Count)throw new KnowledgeIndexException("WAID-KB-DUPLICATE","Knowledge article IDs must be unique.");foreach(var a in c.Articles){if(string.IsNullOrWhiteSpace(a.Id)||string.IsNullOrWhiteSpace(a.Title)||string.IsNullOrWhiteSpace(a.Body)||string.IsNullOrWhiteSpace(a.Source)||string.IsNullOrWhiteSpace(a.License)||a.References.Count==0||a.SupportedOsVersions.Count==0)throw new KnowledgeIndexException("WAID-KB-ARTICLE","Knowledge article metadata is incomplete.");if(!string.Equals(a.Checksum,KnowledgeChecksum.ForText(a.Body),StringComparison.OrdinalIgnoreCase))throw new KnowledgeIndexException("WAID-KB-ARTICLE-CHECKSUM","Knowledge article checksum validation failed.");if(Hostile.Any(x=>$"{a.Title} {a.Summary} {a.Body} {a.RepairGuidance}".Contains(x,StringComparison.OrdinalIgnoreCase)))throw new KnowledgeIndexException("WAID-KB-UNSAFE","Knowledge content contains instruction-like or executable material.");if(a.TrustLevel is KnowledgeTrustLevel.Community or KnowledgeTrustLevel.Plugin&&a.RepairGuidance is not null)throw new KnowledgeIndexException("WAID-KB-TRUST","Untrusted content cannot define repair guidance.");}}
 private static string Checksum(IReadOnlyList<KnowledgeArticle> articles)=>Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(articles,new JsonSerializerOptions(JsonSerializerDefaults.Web)))).ToLowerInvariant();
 private static KnowledgeCatalog LoadEmbedded(){var asm=typeof(OfflineKnowledgeRetrievalService).Assembly;var name=asm.GetManifestResourceNames().Single(x=>x.EndsWith("curated-articles.json",StringComparison.Ordinal));using var stream=asm.GetManifestResourceStream(name)!;return JsonSerializer.Deserialize<KnowledgeCatalog>(stream,new JsonSerializerOptions(JsonSerializerDefaults.Web){PropertyNameCaseInsensitive=true,Converters={new System.Text.Json.Serialization.JsonStringEnumConverter()}})??throw new KnowledgeIndexException("WAID-KB-RESOURCE","Embedded knowledge is invalid.");}
}