using System.Collections.Frozen;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using WAID.Application.Abstractions;
using WAID.Application.Services;
using WAID.Domain.Repairs;
using WAID.Infrastructure.Diagnostics;
namespace WAID.Infrastructure.Configuration;
public sealed class BuiltInEnterprisePolicyProvider: IEnterprisePolicyProvider
{
 public int Priority=>0;public string Name=>"Built-in defaults";
 public Task<EnterprisePolicyDocument?>ReadAsync(CancellationToken token)=>Task.FromResult<EnterprisePolicyDocument?>(new(1,"waid-default","Built-in defaults",DateTimeOffset.UnixEpoch,new Dictionary<EnterpriseCapability,bool>(),EnterpriseRetentionPolicy.Default));
}
public sealed class JsonEnterprisePolicyProvider(string path):IEnterprisePolicyProvider
{
 static readonly JsonSerializerOptions Options=CreateOptions();public int Priority=>100;public string Name=>"Organization policy";
 public async Task<EnterprisePolicyDocument?>ReadAsync(CancellationToken token){if(!File.Exists(path))return null;var info=new FileInfo(path);if(info.Length>1024*1024)throw new InvalidDataException("Enterprise policy exceeds the one-megabyte limit.");await using var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read,4096,FileOptions.Asynchronous|FileOptions.SequentialScan);var document=await JsonSerializer.DeserializeAsync<EnterprisePolicyDocument>(stream,Options,token)??throw new InvalidDataException("Enterprise policy is empty.");return document.Validate() with{Source=Name};}
 static JsonSerializerOptions CreateOptions(){var o=new JsonSerializerOptions(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};o.Converters.Add(new JsonStringEnumConverter());return o;}
}
public sealed class EnterprisePolicyService(IEnumerable<IEnterprisePolicyProvider>providers,IEnterprisePolicyRepository repository,IAuditTrailService audit,TimeProvider time,ILogger<EnterprisePolicyService>logger):IEnterprisePolicyService
{
 readonly SemaphoreSlim gate=new(1,1);readonly IEnterprisePolicyProvider[]chain=providers.OrderBy(x=>x.Priority).ThenBy(x=>x.Name,StringComparer.Ordinal).ToArray();public EnterprisePolicySnapshot Current{get;private set;}=EnterprisePolicySnapshot.SafeDefault(DateTimeOffset.UtcNow);
 public async Task<EnterprisePolicySnapshot>RefreshAsync(CancellationToken token){await gate.WaitAsync(token);try{var rules=Enum.GetValues<EnterpriseCapability>().ToDictionary(x=>x,x=>new EnterprisePolicyRule(true,false,"Built-in default","Allowed unless a higher-priority organization policy restricts it."));var retention=EnterpriseRetentionPolicy.Default;var applied=new List<string>();foreach(var provider in chain){var document=await provider.ReadAsync(token);if(document is null)continue;document.Validate();foreach(var item in document.Rules)rules[item.Key]=new(item.Value,provider.Priority>0,provider.Name,item.Value?"Allowed by the effective organization policy.":"Blocked by the effective organization policy.");if(document.Retention is not null)retention=document.Retention.Validate();applied.Add(provider.Name);}var canonical=JsonSerializer.Serialize(new{rules=rules.OrderBy(x=>x.Key).Select(x=>new{x.Key,x.Value.Allowed,x.Value.Locked,x.Value.Source}),retention});var fingerprint=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical)));Current=new(Guid.NewGuid(),time.GetUtcNow(),EnterprisePolicyState.Active,fingerprint,rules.ToFrozenDictionary(),retention,applied.Count>1?$"Effective policy resolved deterministically from {string.Join(" -> ",applied)}.":"Built-in policy is active; no organization override was found.");await repository.SaveAsync(Current,token);await Audit("EnterprisePolicyRefresh",AuditResult.Succeeded,Current.Explanation,token);return Current;}
 catch(Exception e)when(e is JsonException or InvalidDataException or InvalidOperationException or IOException or UnauthorizedAccessException){logger.LogError("Enterprise policy validation failed closed with {FailureType}",e.GetType().Name);var rules=Enum.GetValues<EnterpriseCapability>().ToDictionary(x=>x,x=>new EnterprisePolicyRule(false,true,"Fail-closed safety policy","Blocked because organization policy could not be validated."));Current=new(Guid.NewGuid(),time.GetUtcNow(),EnterprisePolicyState.FailClosed,"invalid-policy",rules.ToFrozenDictionary(),EnterpriseRetentionPolicy.Default,"Organization policy is invalid or unreadable. Security-sensitive capabilities are blocked until an administrator corrects it.","WAID-POLICY-INVALID");await repository.SaveAsync(Current,CancellationToken.None);await Audit("EnterprisePolicyRefresh",AuditResult.Rejected,Current.Explanation,CancellationToken.None);return Current;}finally{gate.Release();}}
 public EnterprisePolicyDecision Evaluate(EnterpriseCapability capability){var rule=Current.Rules[capability];return new(capability,rule.Allowed,rule.Locked,rule.Source,rule.Reason,Current.FailureCode);}
 public async Task<EnterprisePolicySnapshot>RollbackAsync(Guid snapshotId,CancellationToken token){await gate.WaitAsync(token);try{var source=(await repository.GetRecentAsync(50,token)).FirstOrDefault(x=>x.Id==snapshotId&&x.State!=EnterprisePolicyState.FailClosed)??throw new EnterprisePolicyException("WAID-POLICY-ROLLBACK-MISSING","The selected valid policy snapshot is unavailable.","Refresh policy history and select a valid snapshot.");Current=source with{Id=Guid.NewGuid(),EvaluatedAtUtc=time.GetUtcNow(),State=EnterprisePolicyState.RolledBack,Explanation=$"Rolled back to validated snapshot {source.Id}. Deployment policy must be corrected before the next refresh."};await repository.SaveAsync(Current,token);await Audit("EnterprisePolicyRollback",AuditResult.Succeeded,Current.Explanation,token);return Current;}finally{gate.Release();}}
 async Task Audit(string action,AuditResult result,string detail,CancellationToken token)=>await audit.AppendAsync(new(Guid.NewGuid(),time.GetUtcNow(),AuditActor.Application,action,"Enterprise policy",result,SafetyLevel.High,false,false,Guid.NewGuid(),Guid.NewGuid(),detail),token);
}
public sealed class EnterpriseLiveMonitoringPolicy(IEnterprisePolicyService policy):ILiveMonitoringPolicy{public bool IsMonitoringAllowed()=>policy.Evaluate(EnterpriseCapability.Monitoring).Allowed;public int? MaximumRetentionDays=>policy.Current.Retention.MonitoringDays;}
public static class EnterprisePolicyBootstrap
{
 public static EnterpriseRetentionPolicy? ReadRetention(string? path){if(string.IsNullOrWhiteSpace(path)||!File.Exists(path))return null;try{var options=new JsonSerializerOptions(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};options.Converters.Add(new JsonStringEnumConverter());return JsonSerializer.Deserialize<EnterprisePolicyDocument>(File.ReadAllText(path),options)?.Validate().Retention?.Validate();}catch(Exception e)when(e is JsonException or InvalidDataException or InvalidOperationException or IOException or UnauthorizedAccessException){return EnterpriseRetentionPolicy.Default;}}
 public static bool IsAllowed(string? path,EnterpriseCapability capability){if(string.IsNullOrWhiteSpace(path)||!File.Exists(path))return true;try{var info=new FileInfo(path);if(info.Length>1024*1024)return false;var options=new JsonSerializerOptions(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};options.Converters.Add(new JsonStringEnumConverter());var document=JsonSerializer.Deserialize<EnterprisePolicyDocument>(File.ReadAllText(path),options)?.Validate();return document is not null&&(!document.Rules.TryGetValue(capability,out var allowed)||allowed);}catch(Exception e)when(e is JsonException or InvalidDataException or InvalidOperationException or IOException or UnauthorizedAccessException){return false;}}
}