using System.Collections.ObjectModel;
using System.Windows.Input;
using WAID.Application.Abstractions;
using WAID.Domain.Diagnostics;
using WAID.EventAnalysis;
namespace WAID.Desktop.ViewModels;
public sealed class EvidenceExplorerViewModel(IScanRepository scans,IRepairHistoryRepository repairs,EvidenceAggregationEngine engine,IEvidenceGraphRepository repository):ViewModelBase
{
 private AsyncCommand? _refresh;private string _status="Select Refresh to aggregate recent evidence.";private string _filter="All";private bool _graphMode;
 public ObservableCollection<EvidenceNode> Nodes{get;}=[];public ObservableCollection<EvidenceRelationship> Relationships{get;}=[];public IReadOnlyList<string> Filters{get;}=["All",..Enum.GetNames<EvidenceDomain>()];public ICommand RefreshCommand=>_refresh??=new(RefreshAsync);public string Status{get=>_status;private set=>Set(ref _status,value);}public string Filter{get=>_filter;set{if(Set(ref _filter,value))_ = LoadLatestAsync();}}public bool GraphMode{get=>_graphMode;set{if(Set(ref _graphMode,value)){Notify(nameof(NodeListVisibility));Notify(nameof(GraphListVisibility));}}}public Microsoft.UI.Xaml.Visibility NodeListVisibility=>GraphMode?Microsoft.UI.Xaml.Visibility.Collapsed:Microsoft.UI.Xaml.Visibility.Visible;public Microsoft.UI.Xaml.Visibility GraphListVisibility=>GraphMode?Microsoft.UI.Xaml.Visibility.Visible:Microsoft.UI.Xaml.Visibility.Collapsed;
 public async Task InitializeAsync()=>await LoadLatestAsync();
 private async Task RefreshAsync(){try{Status="Aggregating normalized evidence…";var observations=new List<EvidenceObservation>();foreach(var scan in await scans.GetRecentAsync(25,CancellationToken.None))foreach(var f in scan.Findings)observations.Add(FromFinding(f,scan.CompletedAtUtc??scan.StartedAtUtc));foreach(var repair in await repairs.GetRecentAsync(25,CancellationToken.None))observations.Add(new($"repair:{repair.TransactionId}",EvidenceDomain.Repair,repair.RepairId,repair.Summary??repair.Status.ToString(),repair.CompletedAtUtc??repair.CreatedAtUtc,new Dictionary<string,string>{{"status",repair.Status.ToString()}},new(repair.TransactionId.ToString(),"repair","repair_history",null)));var graph=engine.Build(observations);await repository.SaveAsync(graph,CancellationToken.None);Populate(graph);Status=$"Aggregated {graph.Nodes.Count} immutable node(s) and {graph.Relationships.Count} traceable association(s). Associations are not claims of causation.";}catch(Exception e){Status=$"Evidence aggregation could not complete: {e.Message}";}}
 private async Task LoadLatestAsync(){var graph=await repository.GetLatestAsync(CancellationToken.None);if(graph is not null)Populate(graph);}
 private void Populate(EvidenceGraph graph){Nodes.Clear();Relationships.Clear();var nodes=Filter=="All"?graph.Nodes:graph.Nodes.Where(x=>x.Domain.ToString()==Filter);foreach(var n in nodes)Nodes.Add(n);var ids=Nodes.Select(x=>x.Id).ToHashSet();foreach(var e in graph.Relationships.Where(x=>ids.Contains(x.FromNodeId)&&ids.Contains(x.ToNodeId)))Relationships.Add(e);Status=$"Showing {Nodes.Count} node(s). Strategy {graph.StrategyVersion}; retained until {graph.RetainUntilUtc.LocalDateTime:g}.";}
 private static EvidenceObservation FromFinding(DiagnosticFinding f,DateTimeOffset fallback){var at=f.Evidence.TryGetValue("timeCreated",out var v)&&DateTimeOffset.TryParse(v,out var parsed)?parsed:fallback;return new($"finding:{f.Id}",Domain(f),f.Code,f.Title,at,new Dictionary<string,string>(f.Evidence,StringComparer.OrdinalIgnoreCase),new(f.Id.ToString(),"scanner",f.ScannerId,null));}
 private static EvidenceDomain Domain(DiagnosticFinding f){var text=$"{f.ScannerId} {f.Code}";if(text.Contains("driver",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Driver;if(text.Contains("update",StringComparison.OrdinalIgnoreCase)||text.Contains("cbs",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Update;if(text.Contains("storage",StringComparison.OrdinalIgnoreCase)||text.Contains("smart",StringComparison.OrdinalIgnoreCase)||text.Contains("disk",StringComparison.OrdinalIgnoreCase)||text.Contains("ntfs",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Storage;if(text.Contains("network",StringComparison.OrdinalIgnoreCase)||text.Contains("dns",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Network;if(text.Contains("bsod",StringComparison.OrdinalIgnoreCase)||text.Contains("crash",StringComparison.OrdinalIgnoreCase)||text.Contains("dump",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Crash;if(text.Contains("cpu",StringComparison.OrdinalIgnoreCase)||text.Contains("memory",StringComparison.OrdinalIgnoreCase)||text.Contains("performance",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Performance;if(text.Contains("event",StringComparison.OrdinalIgnoreCase))return EvidenceDomain.Event;return EvidenceDomain.Other;}
}