using System.Collections.ObjectModel;
using System.Windows.Input;
using WAID.Application.Services;
namespace WAID.Desktop.ViewModels;
public sealed class LiveMonitoringViewModel:ViewModelBase
{
    private readonly LiveMonitoringService _service;private readonly ILiveMonitoringRepository _repository;private bool _enabled;private bool _cpu=true;private bool _memory=true;private bool _storage=true;private int _intervalSeconds=60;private int _maximumIntervalSeconds=300;private string _status="Live monitoring is fully disabled until you enable and start it.";private string _resourceUsage="No collection has run.";
    public LiveMonitoringViewModel(LiveMonitoringService service,ILiveMonitoringRepository repository){_service=service;_repository=repository;StartCommand=new AsyncCommand(StartAsync);StopCommand=new AsyncCommand(StopAsync);PauseCommand=new RelayCommand(()=>{_service.Pause();UpdateStatus();});ResumeCommand=new RelayCommand(()=>{_service.Resume();UpdateStatus();});RefreshCommand=new AsyncCommand(LoadAsync);}
    public ObservableCollection<LiveHealthAlert> Alerts{get;}=[];public ObservableCollection<LiveSignalSample> Samples{get;}=[];public ObservableCollection<MonitoringGap> Gaps{get;}=[];public ObservableCollection<CollectorFailure> Failures{get;}=[];
    public ICommand StartCommand{get;}public ICommand StopCommand{get;}public ICommand PauseCommand{get;}public ICommand ResumeCommand{get;}public ICommand RefreshCommand{get;}
    public bool Enabled{get=>_enabled;set=>Set(ref _enabled,value);}public bool CpuEnabled{get=>_cpu;set=>Set(ref _cpu,value);}public bool MemoryEnabled{get=>_memory;set=>Set(ref _memory,value);}public bool StorageEnabled{get=>_storage;set=>Set(ref _storage,value);}public int IntervalSeconds{get=>_intervalSeconds;set=>Set(ref _intervalSeconds,Math.Clamp(value,15,3600));}public int MaximumIntervalSeconds{get=>_maximumIntervalSeconds;set=>Set(ref _maximumIntervalSeconds,Math.Clamp(value,IntervalSeconds,14400));}public string Status{get=>_status;private set=>Set(ref _status,value);}public string ResourceUsage{get=>_resourceUsage;private set=>Set(ref _resourceUsage,value);}
    public async Task LoadAsync(){LiveMonitoringSnapshot? snapshot;try{snapshot=await _repository.GetLatestAsync(100,CancellationToken.None);}catch(Exception){Status="Monitoring history is unavailable. Check Logs & Audit and database health, then retry.";return;}Samples.Clear();Gaps.Clear();Failures.Clear();Alerts.Clear();if(snapshot is not null){foreach(var x in snapshot.Samples)Samples.Add(x);foreach(var x in snapshot.Gaps)Gaps.Add(x);foreach(var x in snapshot.Failures)Failures.Add(x);}UpdateStatus();}
    private async Task StopAsync(){try{await _service.StopAsync();Enabled=false;UpdateStatus();}catch(Exception){Status="Monitoring stopped in memory, but its final session state could not be saved. Check database health.";}}
    private async Task StartAsync(){try{var signals=new HashSet<string>(StringComparer.OrdinalIgnoreCase);if(CpuEnabled)signals.Add("cpu");if(MemoryEnabled)signals.Add("memory");if(StorageEnabled)signals.Add("storage");if(signals.Count==0){Status="Select at least one signal before starting monitoring.";return;}await _service.StartAsync(new(Enabled,TimeSpan.FromSeconds(IntervalSeconds),TimeSpan.FromSeconds(MaximumIntervalSeconds),signals),CancellationToken.None);UpdateStatus();}catch(LiveMonitoringException e){Status=$"Monitoring unavailable ({e.Code}): {e.Message} {e.RecoveryAction}";}catch(ArgumentOutOfRangeException e){Status=$"Monitoring settings are invalid: {e.Message}";}catch(Exception){Status="Monitoring could not start because local monitoring storage is unavailable. Check Logs & Audit, then retry.";}}
    private void UpdateStatus(){Alerts.Clear();foreach(var alert in _service.ActiveAlerts)Alerts.Add(alert);Status=$"Monitoring state: {_service.State}. Pause and stop never run repairs.";var usage=_service.ResourceUsage;ResourceUsage=$"Last collection {usage.LastCollectionDuration.TotalMilliseconds:F0} ms of {usage.Budget.TotalMilliseconds:F0} ms budget; {usage.CollectedSignals} signals, {usage.FailedCollectors} failures; next interval {usage.CurrentInterval.TotalSeconds:F0} seconds.";}
}
