using System.Collections.ObjectModel;
using System.Windows.Input;
using WAID.Application.Services;

namespace WAID.Desktop.ViewModels;

public sealed class NotificationCenterViewModel:ViewModelBase
{
    private readonly IAlertRepository _repository;private readonly AlertManager _manager;private string _status="Loading notifications…";private string _search="";private string _category="All";private string _state="All";private string _severity="Information";private string _deliverySeverity="Advisory";private int _cooldownMinutes=240;private int _quietStartHour=22;private int _quietEndHour=7;private int _escalateAfter=3;private bool _inAppEnabled=true;
    public NotificationCenterViewModel(IAlertRepository repository,AlertManager manager){_repository=repository;_manager=manager;RefreshCommand=new AsyncCommand(LoadAsync);SaveSettingsCommand=new AsyncCommand(SaveSettingsAsync);}
    public event Action<string>? NavigationRequested;public ObservableCollection<AlertNotification> Alerts{get;}=[];public ICommand RefreshCommand{get;}public ICommand SaveSettingsCommand{get;}
    public string Status{get=>_status;private set{_status=value;Notify(nameof(Status));}}public string Search{get=>_search;set{_search=value;Notify(nameof(Search));}}public string Category{get=>_category;set{_category=value;Notify(nameof(Category));}}public string State{get=>_state;set{_state=value;Notify(nameof(State));}}public string MinimumSeverity{get=>_severity;set{_severity=value;Notify(nameof(MinimumSeverity));}}public string DeliveryMinimumSeverity{get=>_deliverySeverity;set{_deliverySeverity=value;Notify(nameof(DeliveryMinimumSeverity));}}public int CooldownMinutes{get=>_cooldownMinutes;set{_cooldownMinutes=Math.Clamp(value,5,43200);Notify(nameof(CooldownMinutes));}}public int QuietStartHour{get=>_quietStartHour;set{_quietStartHour=Math.Clamp(value,0,23);Notify(nameof(QuietStartHour));}}public int QuietEndHour{get=>_quietEndHour;set{_quietEndHour=Math.Clamp(value,0,23);Notify(nameof(QuietEndHour));}}public int EscalateAfter{get=>_escalateAfter;set{_escalateAfter=Math.Clamp(value,2,100);Notify(nameof(EscalateAfter));}}public bool InAppEnabled{get=>_inAppEnabled;set{_inAppEnabled=value;Notify(nameof(InAppEnabled));}}
    public async Task LoadAsync(){try{AlertCategory? category=Enum.TryParse<AlertCategory>(Category,true,out var c)?c:null;AlertState? state=Enum.TryParse<AlertState>(State,true,out var s)?s:null;var severity=Enum.TryParse<AlertSeverity>(MinimumSeverity,true,out var v)?v:AlertSeverity.Information;var items=await _repository.QueryAsync(new(category,severity,state,Search,300),CancellationToken.None);Alerts.Clear();foreach(var item in items)Alerts.Add(item);var settings=await _repository.GetSettingsAsync(CancellationToken.None);CooldownMinutes=(int)settings.Cooldown.TotalMinutes;QuietStartHour=settings.QuietHoursStart.Hour;QuietEndHour=settings.QuietHoursEnd.Hour;EscalateAfter=settings.EscalateAfterOccurrences;DeliveryMinimumSeverity=settings.MinimumSeverity.ToString();InAppEnabled=settings.EnabledChannels.Contains("in-app");Status=$"{Alerts.Count} notification(s). Filters and alert actions never execute repairs.";}catch(Exception ex){Status=$"Notification center unavailable ({ex.GetType().Name}). Check database health and Logs & Audit.";}}
    public async Task AcknowledgeAsync(AlertNotification alert){try{await _manager.AcknowledgeAsync(alert.Id,CancellationToken.None);await LoadAsync();Status="Alert acknowledged. Future duplicate delivery is suppressed until its state changes.";}catch(Exception ex){Status=$"Alert could not be acknowledged ({ex.GetType().Name}).";}}
    public async Task SnoozeAsync(AlertNotification alert){try{await _manager.SnoozeAsync(alert.Id,TimeSpan.FromHours(4),CancellationToken.None);await LoadAsync();Status="Alert snoozed for four hours.";}catch(Exception ex){Status=$"Alert could not be snoozed ({ex.GetType().Name}).";}}
    public void OpenAction(AlertNotification alert){NavigationRequested?.Invoke(alert.ActionTarget);Status=alert.ActionTarget switch{"waid://live-monitoring"=>"Open Live Monitoring from the navigation menu to review the linked evidence.","waid://storage"=>"Open Storage Health from the navigation menu to review the linked evidence.","waid://security"=>"Open Security Center from the navigation menu to review the linked evidence.",_=>$"Review the related WAID area: {alert.ActionLabel}."};}
    private async Task SaveSettingsAsync(){try{var channels=InAppEnabled?new HashSet<string>(["in-app"],StringComparer.OrdinalIgnoreCase):new HashSet<string>(StringComparer.OrdinalIgnoreCase);var deliverySeverity=Enum.TryParse<AlertSeverity>(DeliveryMinimumSeverity,true,out var parsedSeverity)?parsedSeverity:AlertSeverity.Advisory;var settings=new AlertSettings(TimeSpan.FromMinutes(CooldownMinutes),new(QuietStartHour,0),new(QuietEndHour,0),deliverySeverity,channels,EscalateAfter,"User");await _repository.SaveSettingsAsync(settings,CancellationToken.None);Status="Notification policy saved. Critical alerts may bypass quiet hours; repairs remain approval-only.";}catch(Exception ex){Status=$"Notification settings are invalid ({ex.GetType().Name}).";}}
}
