using System.Collections.ObjectModel;using System.Windows.Input;using Microsoft.UI.Xaml;using WAID.Application.Services;namespace WAID.Desktop.ViewModels;public sealed class ReliabilityTimelineViewModel:ViewModelBase
{private readonly ReliabilityTimelineProjector _projector;private readonly IReliabilityTimelineRepository _repository;private readonly ReliabilityTimelineExporter _exporter;private string _status="Build the local projection to view reliability history.";private string _search="";private string _selectedKind="All";private string _viewMode="Timeline";private int _page;private int _total;private string _comparison="Select two events in table mode, then choose Compare selected.";private ReliabilityTimelineEvent?_selectedEvent;private ReliabilityIncident?_selectedIncident;
 public ReliabilityTimelineViewModel(ReliabilityTimelineProjector projector,IReliabilityTimelineRepository repository,ReliabilityTimelineExporter exporter){_projector=projector;_repository=repository;_exporter=exporter;RefreshCommand=new AsyncCommand(RebuildAsync);FilterCommand=new AsyncCommand(()=>LoadPageAsync(0));NextCommand=new AsyncCommand(()=>LoadPageAsync(((_page+1)*50)<_total?_page+1:_page));PreviousCommand=new AsyncCommand(()=>LoadPageAsync(Math.Max(0,_page-1)));ExportCommand=new AsyncCommand(ExportAsync);}
 public ObservableCollection<ReliabilityTimelineEvent>Events{get;}=[];public ObservableCollection<ReliabilityIncident>Incidents{get;}=[];public IReadOnlyList<string>Kinds{get;}=["All",..Enum.GetNames<ReliabilityEventKind>()];public IReadOnlyList<string>ViewModes{get;}=["Timeline","Table"];public ICommand RefreshCommand{get;}public ICommand FilterCommand{get;}public ICommand NextCommand{get;}public ICommand PreviousCommand{get;}public ICommand ExportCommand{get;}
 public string Status{get=>_status;private set=>Set(ref _status,value);}public string Search{get=>_search;set=>Set(ref _search,value);}public string SelectedKind{get=>_selectedKind;set=>Set(ref _selectedKind,value);}public string ViewMode{get=>_viewMode;set{if(Set(ref _viewMode,value)){Notify(nameof(TimelineVisibility));Notify(nameof(TableVisibility));}}}public Visibility TimelineVisibility=>ViewMode=="Timeline"?Visibility.Visible:Visibility.Collapsed;public Visibility TableVisibility=>ViewMode=="Table"?Visibility.Visible:Visibility.Collapsed;public string Comparison{get=>_comparison;private set=>Set(ref _comparison,value);}public ReliabilityTimelineEvent?SelectedEvent{get=>_selectedEvent;set=>Set(ref _selectedEvent,value);}public ReliabilityIncident?SelectedIncident{get=>_selectedIncident;set=>Set(ref _selectedIncident,value);}
 public async Task LoadAsync(){await LoadPageAsync(0);await LoadIncidentsAsync();}
 public void Compare(IReadOnlyList<ReliabilityTimelineEvent>selected){if(selected.Count!=2){Comparison="Select exactly two events to compare.";return;}var a=selected.OrderBy(x=>x.OccurredAtUtc).ToArray();Comparison=$"{a[0].OccurredAtUtc.LocalDateTime:g} {a[0].Kind} → {a[1].OccurredAtUtc.LocalDateTime:g} {a[1].Kind}; elapsed {(a[1].OccurredAtUtc-a[0].OccurredAtUtc).TotalMinutes:F0} minutes. This comparison does not establish causation.";}
 private async Task RebuildAsync(){Status="Projecting immutable reliability sources…";try{var projection=await _projector.RebuildAsync(null,null,CancellationToken.None);await LoadPageAsync(0);Incidents.Clear();foreach(var x in projection.Incidents.OrderByDescending(x=>x.StartedAtUtc))Incidents.Add(x);Status=$"Projected {projection.Events.Count} events and {projection.Incidents.Count} possible-association incident groups with {projection.ProjectionVersion}.";}catch(Exception){Status="The reliability timeline could not be rebuilt. Source records were not changed. Check database health and Logs & Audit.";}}
 private async Task LoadPageAsync(int page){try{ReliabilityEventKind?kind=SelectedKind=="All"?null:Enum.TryParse<ReliabilityEventKind>(SelectedKind,out var parsed)?parsed:null;var result=await _repository.QueryAsync(new(page,50,Kind:kind,Search:string.IsNullOrWhiteSpace(Search)?null:Search),CancellationToken.None);_page=result.Page;_total=result.TotalCount;Events.Clear();foreach(var x in result.Items)Events.Add(x);Status=$"Page {_page+1}; {result.Items.Count} shown of {result.TotalCount}. Times are displayed locally; stored ordering uses UTC and stable IDs.";}catch(Exception){Status="Timeline history is unavailable. Check database health, then retry.";}}
 private async Task LoadIncidentsAsync(){try{Incidents.Clear();foreach(var x in await _repository.GetRecentIncidentsAsync(100,CancellationToken.None))Incidents.Add(x);}catch(Exception){Status="Incident detail is unavailable. Rebuild the timeline or check database health.";}}
 private async Task ExportAsync(){var page=await _repository.QueryAsync(new(0,200,Kind:SelectedKind=="All"?null:Enum.TryParse<ReliabilityEventKind>(SelectedKind,out var kind)?kind:null,Search:string.IsNullOrWhiteSpace(Search)?null:Search),CancellationToken.None);var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Windows AI Doctor","Reports");var path=await _exporter.ExportJsonAsync(page,dir,CancellationToken.None);Status=$"Redacted timeline export saved to {path}";}
}
