using System.Collections.ObjectModel;using System.Windows.Input;using WAID.Application.Services;
namespace WAID.Desktop.ViewModels;
public sealed class TechnicianDashboardViewModel:ViewModelBase
{
 private readonly TechnicianDashboardService _service;private string _status="Refresh to load the professional workspace.";private string _profile="Simple";private string _layout="Compact";private string _filter="";private string _caseId="";private string _caseTitle="";private string _notes="";
 public TechnicianDashboardViewModel(TechnicianDashboardService service){_service=service;RefreshCommand=new AsyncCommand(RefreshAsync);SavePreferencesCommand=new AsyncCommand(SavePreferencesAsync);SaveCaseCommand=new AsyncCommand(SaveCaseAsync);}
 public ObservableCollection<TechnicianIncident> Incidents{get;}=[];public ObservableCollection<RepairOrchestrationRecord> Repairs{get;}=[];public ObservableCollection<RepairAuditEntry> Evidence{get;}=[];public ObservableCollection<TechnicianCase> Cases{get;}=[];public IReadOnlyList<string> Profiles{get;}=["Simple","Technician"];public IReadOnlyList<string> Layouts{get;}=["Compact","Detailed"];public ICommand RefreshCommand{get;}public ICommand SavePreferencesCommand{get;}public ICommand SaveCaseCommand{get;}
 public string Profile{get=>_profile;set=>Set(ref _profile,value);}public string Layout{get=>_layout;set=>Set(ref _layout,value);}public string Filter{get=>_filter;set=>Set(ref _filter,value);}public string CaseId{get=>_caseId;set=>Set(ref _caseId,value);}public string CaseTitle{get=>_caseTitle;set=>Set(ref _caseTitle,value);}public string Notes{get=>_notes;set=>Set(ref _notes,value);}public string Status{get=>_status;private set=>Set(ref _status,value);}
 public async Task RefreshAsync(){try{var x=await _service.LoadAsync(CancellationToken.None);Profile=x.Preferences.Profile.ToString();Layout=x.Preferences.Layout.ToString();Filter=x.Preferences.SavedFilter;Incidents.Clear();foreach(var i in x.ActiveIncidents)Incidents.Add(i);Repairs.Clear();foreach(var i in x.Repairs)Repairs.Add(i);Evidence.Clear();foreach(var i in x.Evidence)Evidence.Add(i);Cases.Clear();foreach(var i in x.Cases)Cases.Add(i);Status=x.SystemOverview;}catch(Exception e){Status=$"Technician workspace unavailable ({e.GetType().Name}). Check database health and Logs & Audit.";}}
 private async Task SavePreferencesAsync(){try{await _service.SavePreferencesAsync(new(Enum.Parse<DashboardPresentationProfile>(Profile),Enum.Parse<TechnicianLayout>(Layout),Filter,DateTimeOffset.MinValue),CancellationToken.None);Status="Presentation profile saved. Simple mode remains available.";}catch(Exception e){Status=$"Preferences were not saved ({e.GetType().Name}).";}}
 private async Task SaveCaseAsync(){try{var now=DateTimeOffset.UtcNow;await _service.SaveCaseAsync(new(Guid.NewGuid(),CaseId,CaseTitle,Notes,now,now),CancellationToken.None);Status="Case metadata and notes saved locally.";await RefreshAsync();}catch(Exception e){Status=$"Case was not saved ({e.GetType().Name}). Check required fields and length limits.";}}
}
