using Microsoft.Extensions.Logging.Abstractions;
using WAID.Application.Services;

namespace WAID.Application.Tests;

public sealed class AlertingTests
{
    [Fact]public async Task Duplicate_alerts_merge_evidence_and_cooldown_prevents_spam(){var f=Fixture();var first=await f.Manager.RaiseAsync(Request(),CancellationToken.None);f.Time.Advance(TimeSpan.FromMinutes(1));var second=await f.Manager.RaiseAsync(Request("second"),CancellationToken.None);Assert.True(first.Created);Assert.False(second.Created);Assert.Equal(first.Alert.Id,second.Alert.Id);Assert.Equal(2,second.Alert.Occurrences);Assert.Equal(2,second.Alert.Evidence.Count);Assert.Single(f.Channel.Items);Assert.Contains(second.Deliveries,x=>x.Status==AlertDeliveryStatus.SuppressedCooldown);}
    [Fact]public async Task Quiet_hours_suppress_warning_but_critical_bypasses(){var now=new DateTimeOffset(2026,1,1,23,0,0,TimeSpan.Zero);var f=Fixture(now,AlertSettings.Default with{QuietHoursStart=new(22,0),QuietHoursEnd=new(7,0)});var warning=await f.Manager.RaiseAsync(Request(),CancellationToken.None);var critical=await f.Manager.RaiseAsync(Request("critical")with{DeduplicationKey="critical",Severity=AlertSeverity.Critical},CancellationToken.None);Assert.Contains(warning.Deliveries,x=>x.Status==AlertDeliveryStatus.SuppressedQuietHours);Assert.Contains(critical.Deliveries,x=>x.Status==AlertDeliveryStatus.Delivered);}
    [Fact]public async Task Snooze_and_acknowledgement_survive_duplicate_observations(){var f=Fixture();var initial=await f.Manager.RaiseAsync(Request(),CancellationToken.None);await f.Manager.SnoozeAsync(initial.Alert.Id,TimeSpan.FromHours(4),CancellationToken.None);var snoozed=await f.Manager.RaiseAsync(Request(),CancellationToken.None);Assert.Contains(snoozed.Deliveries,x=>x.Status==AlertDeliveryStatus.SuppressedSnooze);await f.Manager.AcknowledgeAsync(initial.Alert.Id,CancellationToken.None);var acknowledged=await f.Manager.RaiseAsync(Request(),CancellationToken.None);Assert.Contains(acknowledged.Deliveries,x=>x.Status==AlertDeliveryStatus.SuppressedAcknowledged);}
    [Fact]public async Task Repeated_alerts_escalate_without_changing_evidence_severity(){var f=Fixture(settings:AlertSettings.Default with{Cooldown=TimeSpan.FromMinutes(5),EscalateAfterOccurrences=2});for(var i=0;i<4;i++){await f.Manager.RaiseAsync(Request(i.ToString()),CancellationToken.None);f.Time.Advance(TimeSpan.FromMinutes(6));}var alert=Assert.Single(f.Repository.Alerts);Assert.Equal(2,alert.EscalationLevel);Assert.Equal(AlertSeverity.Warning,alert.Severity);}
    [Fact]public async Task Delivery_failure_is_typed_persisted_and_does_not_break_alert_state(){var f=Fixture(channel:new Channel(fail:true));var result=await f.Manager.RaiseAsync(Request(),CancellationToken.None);Assert.Contains(result.Deliveries,x=>x.Status==AlertDeliveryStatus.Failed);Assert.Single(f.Repository.Alerts);Assert.Contains(f.Repository.Deliveries,x=>x.Status==AlertDeliveryStatus.Failed);}
    [Fact]public async Task Evidence_redaction_removes_secrets_and_profile_paths(){var f=Fixture();var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);var request=Request()with{Evidence=new("test","ref",f.Time.GetUtcNow(),new Dictionary<string,string>{{"eventId","41"},{"token","secret"},{"path",Path.Combine(profile,"file.txt")}})};var result=await f.Manager.RaiseAsync(request,CancellationToken.None);var values=Assert.Single(result.Alert.Evidence).Values;Assert.DoesNotContain("token",values.Keys,StringComparer.OrdinalIgnoreCase);Assert.DoesNotContain(profile,values["path"],StringComparison.OrdinalIgnoreCase);}
    [Fact]public void Quiet_hour_math_handles_overnight_and_day_windows(){Assert.True(AlertManager.InsideQuietHours(new(23,0),new(22,0),new(7,0)));Assert.True(AlertManager.InsideQuietHours(new(6,0),new(22,0),new(7,0)));Assert.False(AlertManager.InsideQuietHours(new(12,0),new(22,0),new(7,0)));Assert.True(AlertManager.InsideQuietHours(new(12,0),new(9,0),new(17,0)));}
    private static AlertRaiseRequest Request(string reference="first")=>new("cpu:high","cpu-high","1.0",AlertCategory.Performance,AlertSeverity.Warning,"CPU needs attention","CPU remained above the warning threshold.","Review monitoring","waid://live-monitoring",new("monitor",reference,DateTimeOffset.UtcNow,new Dictionary<string,string>{{"value","91"}}));
    private static Harness Fixture(DateTimeOffset? now=null,AlertSettings? settings=null,Channel? channel=null){var time=new MutableTime(now??new DateTimeOffset(2026,1,1,12,0,0,TimeSpan.Zero));var repo=new Repository(settings??AlertSettings.Default);var delivery=channel??new Channel();var manager=new AlertManager(repo,[delivery],new AllowConfiguredAlertPolicy(),time,NullLogger<AlertManager>.Instance);return new(manager,repo,delivery,time);}
    private sealed record Harness(AlertManager Manager,Repository Repository,Channel Channel,MutableTime Time);
    private sealed class MutableTime(DateTimeOffset now):TimeProvider{private DateTimeOffset _now=now;public override DateTimeOffset GetUtcNow()=>_now;public void Advance(TimeSpan value)=>_now+=value;}
    private sealed class Channel(bool fail=false):IAlertDeliveryChannel{public string Id=>"in-app";public List<Guid>Items{get;}=[];public Task DeliverAsync(AlertNotification a,CancellationToken t){if(fail)throw new IOException("channel failure");Items.Add(a.Id);return Task.CompletedTask;}}
    private sealed class Repository(AlertSettings settings):IAlertRepository{public List<AlertNotification>Alerts{get;}=[];public List<AlertDelivery>Deliveries{get;}=[];private AlertSettings _settings=settings;public Task<AlertNotification?>GetActiveByKeyAsync(string k,CancellationToken t)=>Task.FromResult(Alerts.LastOrDefault(x=>x.DeduplicationKey==k&&x.State!=AlertState.Resolved));public Task SaveAsync(AlertNotification a,CancellationToken t){var i=Alerts.FindIndex(x=>x.Id==a.Id);if(i<0)Alerts.Add(a);else Alerts[i]=a;return Task.CompletedTask;}public Task SaveDeliveryAsync(AlertDelivery d,CancellationToken t){Deliveries.Add(d);return Task.CompletedTask;}public Task<IReadOnlyList<AlertNotification>>QueryAsync(AlertQuery q,CancellationToken t)=>Task.FromResult<IReadOnlyList<AlertNotification>>(Alerts);public Task<AlertSettings>GetSettingsAsync(CancellationToken t)=>Task.FromResult(_settings);public Task SaveSettingsAsync(AlertSettings s,CancellationToken t){_settings=s;return Task.CompletedTask;}}
}
