using System.Text.Json;
using WAID.Application.Services;
namespace WAID.Application.Tests;
public sealed class CliAutomationTests
{
 [Fact]public void Parser_accepts_stable_commands_output_and_options(){var request=WaidCliParser.Parse(["findings","--limit","25","--json"]);Assert.Equal("findings",request.Command);Assert.Equal("25",request.Option("limit"));Assert.Equal(CliOutputFormat.Json,request.OutputFormat);}
 [Theory][InlineData("unknown")][InlineData("scan --json --json")][InlineData("repair-plan")][InlineData("findings --limit")]public void Parser_rejects_invalid_or_ambiguous_input(string text)=>Assert.Throws<CliParseException>(()=>WaidCliParser.Parse(text.Split(' ')));
 [Fact]public async Task Json_envelope_has_stable_schema_command_and_exit_code(){var output=new StringWriter();var code=await new WaidCliApplication(new Runtime(CliResult.Success(new{value=42})),TimeProvider.System).RunAsync(["status","--json"],output,new StringWriter(),CancellationToken.None);using var json=JsonDocument.Parse(output.ToString());Assert.Equal(0,code);Assert.Equal("waid-cli-1.0",json.RootElement.GetProperty("schemaVersion").GetString());Assert.Equal("status",json.RootElement.GetProperty("command").GetString());Assert.True(json.RootElement.GetProperty("succeeded").GetBoolean());}
 [Fact]public async Task Runtime_failure_preserves_stable_exit_code_and_actionable_error(){var output=new StringWriter();var result=CliResult.Failure(CliExitCode.NotFound,"WAID-TEST-NOTFOUND","Missing.","Create it first.");var code=await new WaidCliApplication(new Runtime(result),TimeProvider.System).RunAsync(["report","--json"],output,new StringWriter(),CancellationToken.None);Assert.Equal(3,code);Assert.Contains("WAID-TEST-NOTFOUND",output.ToString(),StringComparison.Ordinal);Assert.Contains("Create it first",output.ToString(),StringComparison.Ordinal);}
 [Fact]public async Task Cancellation_returns_documented_exit_code_without_stack_trace(){var output=new StringWriter();var code=await new WaidCliApplication(new ThrowingRuntime(),TimeProvider.System).RunAsync(["scan","--json"],output,new StringWriter(),CancellationToken.None);Assert.Equal(6,code);Assert.Contains("WAID-CLI-CANCELLED",output.ToString(),StringComparison.Ordinal);}
 [Fact]public void Repair_execution_requires_every_gate_and_exact_plan_bound_phrase(){var id=Guid.NewGuid();Assert.False(RepairExecutionConfirmation.IsValid(Request(id,false,true,$"EXECUTE WAID REPAIR {id:D}"),id,out _));Assert.False(RepairExecutionConfirmation.IsValid(Request(id,true,true,$"execute waid repair {id:D}"),id,out _));Assert.False(RepairExecutionConfirmation.IsValid(Request(Guid.NewGuid(),true,true,$"EXECUTE WAID REPAIR {id:D}"),id,out _));Assert.True(RepairExecutionConfirmation.IsValid(Request(id,true,true,$"EXECUTE WAID REPAIR {id:D}"),id,out var expected));Assert.Equal($"EXECUTE WAID REPAIR {id:D}",expected);}
 [Fact]public async Task Progress_is_written_to_stderr_and_json_stdout_remains_parseable(){var output=new StringWriter();var error=new StringWriter();await new WaidCliApplication(new ProgressRuntime(),TimeProvider.System).RunAsync(["scan","--json"],output,error,CancellationToken.None);JsonDocument.Parse(output.ToString()).Dispose();Assert.Contains("phase 1",error.ToString(),StringComparison.Ordinal);Assert.DoesNotContain("phase 1",output.ToString(),StringComparison.Ordinal);}
 static CliRequest Request(Guid id,bool approve,bool risk,string confirmation)=>new("repair-plan","execute",new Dictionary<string,string>{{"id",id.ToString()},{"approve",approve.ToString()},{"acknowledge-risk",risk.ToString()},{"confirmation",confirmation}},CliOutputFormat.Json,false);
 sealed class Runtime(CliResult result):IWaidCliRuntime{public Task<CliResult>ExecuteAsync(CliRequest request,IProgress<string>?progress,CancellationToken token)=>Task.FromResult(result);}
 sealed class ThrowingRuntime:IWaidCliRuntime{public Task<CliResult>ExecuteAsync(CliRequest request,IProgress<string>?progress,CancellationToken token)=>throw new OperationCanceledException();}
 sealed class ProgressRuntime:IWaidCliRuntime{public Task<CliResult>ExecuteAsync(CliRequest request,IProgress<string>?progress,CancellationToken token){progress?.Report("phase 1");return Task.FromResult(CliResult.Success(new{done=true}));}}
}