using Microsoft.Extensions.Logging.Abstractions;
using WAID.Application.Abstractions;
using WAID.Application.Services;
using WAID.Diagnosis;
using WAID.Domain.Diagnostics;
using WAID.Domain.Repairs;
using WAID.EventAnalysis;
using WAID.Health;
using WAID.KnowledgeBase;

namespace WAID.Application.Tests;

public sealed class ContinuousHealthTests
{
    [Fact] public void Schedule_detects_due_and_missed_scans(){var now=DateTimeOffset.UtcNow;var schedule=new ScanSchedule(true,ScheduleFrequency.Daily,TimeSpan.FromHours(1),DayOfWeek.Monday,new(9,0),false,false,now.AddDays(-2));Assert.True(ScheduledScanService.IsDue(schedule,now));Assert.False(ScheduledScanService.IsDue(schedule with{LastRunUtc=now},now));}
    [Fact] public void Evidence_collector_removes_secrets_and_redacts_profile_paths(){var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);var finding=new DiagnosticFinding("scanner","CODE","Title","Description",DiagnosticSeverity.Warning,evidence:new Dictionary<string,string>{{"eventId","41"},{"token","secret"},{"fileName",Path.Combine(profile,"dump.dmp")}});var evidence=Assert.Single(new EvidenceCollector(TimeProvider.System).Collect([finding]));Assert.Equal("41",evidence.Values["eventId"]);Assert.DoesNotContain("token",evidence.Values.Keys,StringComparer.OrdinalIgnoreCase);Assert.DoesNotContain(profile,evidence.Values["fileName"],StringComparison.OrdinalIgnoreCase);}
    [Fact] public async Task Approval_requires_acknowledgement_for_high_risk_repairs(){var repository=new ApprovalRepository();var workflow=new RepairApprovalWorkflow(repository,TimeProvider.System);var repair=new PrioritizedRepair("repair","Repair",1,80,SafetyLevel.High,true,false,true,90,80);await Assert.ThrowsAsync<InvalidOperationException>(()=>workflow.RecordAsync(repair,"evidence",["action"],true,false,CancellationToken.None));var approval=await workflow.RecordAsync(repair,"evidence",["action"],true,true,CancellationToken.None);Assert.True(approval.Approved);Assert.Single(repository.Items);}
    [Fact] public void Prioritization_orders_dism_before_sfc_and_reports_safety(){var modules=new IRepairModule[]{new Module("waid.sfc",SafetyLevel.High),new Module("waid.dism",SafetyLevel.High)};var engine=new RepairPrioritizationEngine(new RepairRegistry(modules));var finding=new DiagnosticFinding("scanner","CBS_CORRUPTION","CBS","CBS",DiagnosticSeverity.Critical);RootCause Cause(string id,string repair,int priority)=>new(id,id,[finding],95,DiagnosticSeverity.Critical,priority,new(repair,repair,priority,DiagnosticSeverity.Critical,95),"Explanation");var report=new AIReport(DateTimeOffset.UtcNow,"Summary",new HealthScore(70,70,70,70,70,70,70,70),[Cause("sfc","waid.sfc",1),Cause("dism","waid.dism",1)],[],[finding]);var ordered=engine.Prioritize(report).ToArray();Assert.Equal("waid.dism",ordered[0].RepairId);Assert.True(ordered[0].RequiresAdministrator);Assert.True(ordered[0].SupportsRollback);}
    [Fact] public async Task Monitoring_can_be_cancelled_and_stores_snapshot_without_repairs(){var scanRepository=new ScanRepository();var orchestrator=new ScanOrchestrator([new Scanner()],scanRepository,TimeProvider.System,NullLogger<ScanOrchestrator>.Instance);var snapshotRepository=new SnapshotRepository();var monitoring=new BackgroundHealthMonitoringService(new ScanCoordinator(orchestrator),CreateDiagnosis(),snapshotRepository,new Conditions(),TimeProvider.System,NullLogger<BackgroundHealthMonitoringService>.Instance);monitoring.Start(new MonitoringOptions(TimeSpan.FromMinutes(1)));await snapshotRepository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(5));await monitoring.StopAsync();Assert.Equal(MonitoringState.Stopped,monitoring.State);Assert.Single(snapshotRepository.Items);}
    private static DiagnosisEngine CreateDiagnosis(){var confidence=new ConfidenceEngine();return new(new DiagnosticKnowledgeBase(),new RuleEngine(),new CorrelationScanner(new EventCorrelationEngine()),new RootCauseAnalyzer(confidence,new RecommendationEngine(),new ExplanationEngine()),new HealthScoreEngine(),new AIReportBuilder(TimeProvider.System));}
    private sealed class Scanner:ISystemScanner{public string Id=>"monitor";public string DisplayName=>"Monitor";public Task<IReadOnlyCollection<DiagnosticFinding>> ScanAsync(ScanContext context,CancellationToken token)=>Task.FromResult<IReadOnlyCollection<DiagnosticFinding>>([new(Id,"CPU_HIGH","CPU","High CPU",DiagnosticSeverity.Warning)]);}
    private sealed class ScanRepository:IScanRepository{public List<ScanSession> Items{get;}=[];public Task SaveAsync(ScanSession session,CancellationToken token){Items.Add(session);return Task.CompletedTask;}public Task<IReadOnlyList<ScanSession>> GetRecentAsync(int count,CancellationToken token)=>Task.FromResult<IReadOnlyList<ScanSession>>(Items);}
    private sealed class SnapshotRepository:IHealthSnapshotRepository{public List<HealthSnapshot> Items{get;}=[];public TaskCompletionSource Saved{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);public Task SaveAsync(HealthSnapshot snapshot,CancellationToken token){Items.Add(snapshot);Saved.TrySetResult();return Task.CompletedTask;}public Task<IReadOnlyList<HealthSnapshot>> GetRecentAsync(int count,CancellationToken token)=>Task.FromResult<IReadOnlyList<HealthSnapshot>>(Items);}
    private sealed class Conditions:ISystemConditionService{public bool IsBatterySaverEnabled()=>false;public bool IsPluggedIn()=>true;public bool IsSystemIdle()=>true;public double GetSystemLoadPercent()=>0;}
    private sealed class ApprovalRepository:IRepairApprovalRepository{public List<RepairApproval> Items{get;}=[];public Task SaveAsync(RepairApproval approval,CancellationToken token){Items.Add(approval);return Task.CompletedTask;}public Task<IReadOnlyList<RepairApproval>> GetRecentAsync(int count,CancellationToken token)=>Task.FromResult<IReadOnlyList<RepairApproval>>(Items);}
    private sealed class Module(string id,SafetyLevel level):IRepairModule{public string Id=>id;public string DisplayName=>id;public string Description=>id;public RepairPolicy Policy{get;}=new(level);public Task<RepairPlan>CreatePlanAsync(DiagnosticFinding?finding,CancellationToken token)=>Task.FromResult(new RepairPlan([],id));public Task<RepairResult>ExecuteAsync(RepairExecutionContext context,CancellationToken token)=>Task.FromResult(RepairResult.Success("done"));}
}
