using Microsoft.Extensions.Logging.Abstractions;
using WAID.Application.Services;
namespace WAID.Application.Tests;
public sealed class LiveMonitoringTests
{
    [Fact]public async Task Lifecycle_can_start_pause_resume_and_fully_disable(){var h=Harness();await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));h.Service.Pause();Assert.Equal(LiveMonitoringState.Paused,h.Service.State);h.Service.Resume();Assert.Equal(LiveMonitoringState.Running,h.Service.State);await h.Service.StopAsync();Assert.Equal(LiveMonitoringState.Disabled,h.Service.State);Assert.NotNull(h.Repository.Sessions[^1].EndedAtUtc);}
    [Fact]public async Task Battery_saver_pauses_collection_and_records_gap(){var h=Harness(battery:true);await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Equal(LiveMonitoringState.PausedBatterySaver,h.Service.State);Assert.Contains(h.Repository.Gaps,x=>x.Reason==MonitoringGapReason.Suspended);await h.Service.StopAsync();}
    [Fact]public async Task High_load_pauses_without_invoking_collector(){var collector=new Collector();var h=Harness(load:95,collector:collector);await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Equal(0,collector.Calls);Assert.Equal(LiveMonitoringState.PausedHighLoad,h.Service.State);await h.Service.StopAsync();}
    [Fact]public async Task Collector_failure_is_isolated_and_persisted(){var h=Harness(collector:new Collector(fail:true));await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Single(h.Repository.Failures);Assert.Equal("WAID-MON-COLLECTOR",h.Repository.Failures[0].Code);await h.Service.StopAsync();}
    [Fact]public async Task Collection_budget_cancels_slow_collector(){var h=Harness(collector:new Collector(delay:TimeSpan.FromSeconds(1)));await h.Service.StartAsync(Options() with{CollectionBudget=TimeSpan.FromMilliseconds(100)});await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Contains(h.Repository.Gaps,x=>x.Reason==MonitoringGapReason.BudgetExceeded);Assert.True(h.Service.ResourceUsage.LastCollectionDuration<=TimeSpan.FromSeconds(1));await h.Service.StopAsync();}
    [Fact]public async Task Stable_soak_cycles_remain_bounded_and_adapt_interval(){var h=Harness();await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));for(var i=0;i<100;i++)await h.Service.RunCycleAsync(CancellationToken.None);Assert.True(h.Repository.Samples.Count<=303);Assert.True(h.Service.ResourceUsage.CurrentInterval>TimeSpan.FromSeconds(15));Assert.All(h.Repository.Samples,x=>Assert.InRange(x.Value??0,0,100));await h.Service.StopAsync();}
    [Fact]public async Task Policy_can_disable_all_collection(){var collector=new Collector();var h=Harness(collector:collector,policy:new DenyPolicy());await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Equal(LiveMonitoringState.PausedByPolicy,h.Service.State);Assert.Equal(0,collector.Calls);await h.Service.StopAsync();}
    [Fact]public async Task Alert_evaluation_is_separate_and_exposes_threshold_crossing(){var h=Harness(collector:new Collector(values:[96,97,4]));await h.Service.StartAsync(Options());await h.Repository.Saved.Task.WaitAsync(TimeSpan.FromSeconds(3));Assert.Equal(3,h.Service.ActiveAlerts.Count);Assert.All(h.Service.ActiveAlerts,x=>Assert.True(x.Severity>=LiveSignalSeverity.Warning));await h.Service.StopAsync();}
    [Fact]public void Options_reject_unsafe_intervals_and_storage_limits(){Assert.Throws<ArgumentOutOfRangeException>(()=>(Options()with{BaseInterval=TimeSpan.FromSeconds(1)}).Validate());Assert.Throws<ArgumentOutOfRangeException>(()=>(Options()with{MaximumStoredSamples=10}).Validate());}
    private static LiveMonitoringOptions Options()=>new(true,TimeSpan.FromSeconds(15),TimeSpan.FromMinutes(2),new HashSet<string>(["cpu","memory","storage"]));
    private static TestHarness Harness(bool battery=false,double load=0,Collector? collector=null,ILiveMonitoringPolicy? policy=null){var repository=new Repository();var service=new LiveMonitoringService([collector??new Collector()],repository,new Conditions(battery,load),new LiveSignalAggregator(),new LiveAlertEvaluator(),policy??new AllowLiveMonitoringPolicy(),TimeProvider.System,NullLogger<LiveMonitoringService>.Instance);return new(service,repository);}
    private sealed record TestHarness(LiveMonitoringService Service,Repository Repository);
    private sealed class Collector(bool fail=false,TimeSpan delay=default,double[]? values=null):ILiveSignalCollector{public int Calls;public string Id=>"test";public IReadOnlySet<string> SignalIds{get;}=new HashSet<string>(["cpu","memory","storage"]);public async Task<IReadOnlyList<LiveCollectorReading>>CollectAsync(CancellationToken token){Interlocked.Increment(ref Calls);if(delay>TimeSpan.Zero)await Task.Delay(delay,token);if(fail)throw new InvalidOperationException("private failure detail");var v=values??[25,40,50];return[new("cpu",v[0],"percent","test"),new("memory",v[1],"percent","test"),new("storage",v[2],"percent-free","test")];}}
    private sealed class DenyPolicy:ILiveMonitoringPolicy{public bool IsMonitoringAllowed()=>false;}
    private sealed class Conditions(bool battery,double load):ISystemConditionService{public bool IsBatterySaverEnabled()=>battery;public bool IsPluggedIn()=>!battery;public bool IsSystemIdle()=>true;public double GetSystemLoadPercent()=>load;}
    private sealed class Repository:ILiveMonitoringRepository{private readonly object _gate=new();public List<LiveMonitoringSession>Sessions{get;}=[];public List<LiveSignalSample>Samples{get;}=[];public List<MonitoringGap>Gaps{get;}=[];public List<CollectorFailure>Failures{get;}=[];public TaskCompletionSource Saved{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);public Task RecoverInterruptedSessionsAsync(DateTimeOffset now,CancellationToken token)=>Task.CompletedTask;public Task SaveSessionAsync(LiveMonitoringSession session,CancellationToken token){lock(_gate){var index=Sessions.FindIndex(x=>x.Id==session.Id);if(index<0)Sessions.Add(session);else Sessions[index]=session;}return Task.CompletedTask;}public Task SaveCycleAsync(IReadOnlyList<LiveSignalSample> samples,IReadOnlyList<MonitoringGap> gaps,IReadOnlyList<CollectorFailure> failures,CancellationToken token){lock(_gate){Samples.AddRange(samples);Gaps.AddRange(gaps);Failures.AddRange(failures);}Saved.TrySetResult();return Task.CompletedTask;}public Task<MonitoringRetentionState>ApplyRetentionAsync(DateTimeOffset retainAfterUtc,int maximumSamples,CancellationToken token)=>Task.FromResult(new MonitoringRetentionState(DateTimeOffset.UtcNow,retainAfterUtc,maximumSamples,0,0));public Task<LiveMonitoringSnapshot?>GetLatestAsync(int sampleCount,CancellationToken token)=>Task.FromResult<LiveMonitoringSnapshot?>(null);}
}
