using System.Diagnostics;using WAID.Application.Services;namespace WAID.Application.Tests;[Trait("Category","Performance")]
public sealed class PerformanceHistoryTests
{private readonly PerformanceAggregationEngine _engine=new();private static readonly DateTimeOffset Start=new(2026,3,8,0,0,0,TimeSpan.Zero);
 [Fact]public void Hourly_aggregation_calculates_values_quality_and_coverage(){var samples=new[]{S(Start,10),S(Start.AddMinutes(10),20),S(Start.AddMinutes(20),null,MetricQuality.Unavailable)};var x=Assert.Single(_engine.Aggregate(PerformanceMetricKind.CpuUtilization,samples,MetricResolution.Hourly));Assert.Equal(10,x.Minimum);Assert.Equal(20,x.Maximum);Assert.Equal(15,x.Average);Assert.Equal(2,x.SampleCount);Assert.Equal(66.67,x.CoveragePercent,2);}
 [Fact]public void Timezone_and_dst_offsets_bucket_by_utc_instant(){var a=S(new DateTimeOffset(2026,3,8,1,30,0,TimeSpan.FromHours(-5)),10);var b=S(new DateTimeOffset(2026,3,8,3,30,0,TimeSpan.FromHours(-4)),20);var rollups=_engine.Aggregate(PerformanceMetricKind.CpuUtilization,[a,b],MetricResolution.Hourly);Assert.Equal(2,rollups.Count);Assert.All(rollups,x=>Assert.Equal(TimeSpan.Zero,x.PeriodStartUtc.Offset));}
 [Fact]public void Downsampling_is_bounded_ordered_and_preserves_spike_bucket(){var points=Enumerable.Range(0,10_000).Select(i=>R(Start.AddHours(i),i==5000?100:10)).ToArray();var result=_engine.Downsample(points,300);Assert.Equal(300,result.Count);Assert.Equal(result.OrderBy(x=>x.PeriodStartUtc),result);Assert.Contains(result,x=>x.Maximum==100);}
 [Fact]public void Sustained_change_requires_consistent_recent_shift(){var points=Enumerable.Range(0,8).Select(i=>R(Start.AddHours(i),i<4?20:30)).ToArray();var change=Assert.Single(_engine.DetectChanges(PerformanceMetricKind.MemoryUtilization,points));Assert.True(change.Sustained);Assert.Equal(50,change.PercentChange);}
 [Fact]public void Invalid_samples_and_query_bounds_are_rejected(){Assert.Throws<ArgumentOutOfRangeException>(()=>new PerformanceMetricSample(Guid.NewGuid(),PerformanceMetricKind.CpuUtilization,Start,double.NaN,"percent",MetricQuality.Measured,"test").Validate());Assert.Throws<ArgumentException>(()=>new PerformanceHistoryQuery(PerformanceMetricKind.CpuUtilization,Start.AddDays(1),Start,MetricResolution.Daily).Validate());}
 [Fact]public void Large_history_downsampling_remains_responsive(){var points=Enumerable.Range(0,100_000).Select(i=>R(Start.AddMinutes(i),i%100)).ToArray();var sw=Stopwatch.StartNew();var result=_engine.Downsample(points,500);sw.Stop();Assert.Equal(500,result.Count);Assert.True(sw.Elapsed<TimeSpan.FromSeconds(5));}
 private static PerformanceMetricSample S(DateTimeOffset t,double?v,MetricQuality q=MetricQuality.Measured)=>new(Guid.NewGuid(),PerformanceMetricKind.CpuUtilization,t,v,"percent",q,"test");private static PerformanceMetricRollup R(DateTimeOffset t,double v)=>new(Guid.NewGuid(),PerformanceMetricKind.CpuUtilization,MetricResolution.Hourly,t,t.AddHours(1),v,v,v,v,1,100,"percent",MetricQuality.Measured,PerformanceAggregationEngine.Version);}
