using WAID.Application.Services;namespace WAID.Application.Tests;public sealed class ReliabilityTimelineTests
{private static readonly DateTimeOffset Start=new(2026,1,1,12,0,0,TimeSpan.Zero);
 [Fact]public async Task Ordering_and_ids_are_stable_across_rebuilds(){var records=new[]{R("b",Start,"b"),R("a",Start,"a"),R("c",Start.AddMinutes(-1),"c")};var h=Harness(records);var first=await h.Projector.RebuildAsync(null,null,CancellationToken.None);var second=await h.Projector.RebuildAsync(null,null,CancellationToken.None);Assert.Equal(first.Events.Select(x=>x.Id),second.Events.Select(x=>x.Id));Assert.Equal(first.Events.OrderBy(x=>x.OccurredAtUtc).ThenBy(x=>x.Id).Select(x=>x.Id),first.Events.Select(x=>x.Id));}
 [Fact]public async Task Equivalent_timezone_instants_deduplicate(){var a=R("same",new DateTimeOffset(2026,1,1,12,0,0,TimeSpan.Zero),"disk");var b=a with{OccurredAtUtc=new DateTimeOffset(2026,1,1,17,30,0,TimeSpan.FromHours(5.5))};var h=Harness([a,b]);var result=await h.Projector.RebuildAsync(null,null,CancellationToken.None);Assert.Single(result.Events);Assert.Equal(TimeSpan.Zero,result.Events[0].OccurredAtUtc.Offset);}
 [Fact]public async Task Related_events_group_as_association_not_causation(){var h=Harness([R("driver",Start,"device",ReliabilityEventKind.DriverChange),R("crash",Start.AddMinutes(5),"device",ReliabilityEventKind.Crash)]);var result=await h.Projector.RebuildAsync(null,null,CancellationToken.None);var incident=Assert.Single(result.Incidents);Assert.Contains("not proof of causation",incident.CorrelationLabel,StringComparison.OrdinalIgnoreCase);Assert.Equal(ReliabilityTimelineProjector.GroupingVersion,incident.GroupingVersion);}
 [Fact]public async Task Duplicate_source_records_do_not_duplicate_events(){var value=R("one",Start,"subject");var h=Harness([value,value,value]);Assert.Single((await h.Projector.RebuildAsync(null,null,CancellationToken.None)).Events);}
 [Fact]public async Task Large_history_projection_is_complete_and_deterministic(){var values=Enumerable.Range(0,10_000).Select(i=>R(i.ToString(),Start.AddSeconds(i),$"subject-{i%100}")).ToArray();var h=Harness(values);var result=await h.Projector.RebuildAsync(null,null,CancellationToken.None);Assert.Equal(10_000,result.Events.Count);Assert.Equal(result.Events.Select(x=>x.Id).Distinct().Count(),result.Events.Count);Assert.Equal(ReliabilityTimelineProjector.ProjectionVersion,result.ProjectionVersion);}
 [Fact]public async Task Export_redacts_profile_paths_and_secret_evidence(){var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);var e=new ReliabilityTimelineEvent("id",ReliabilityEventKind.Alert,Start,"title",Path.Combine(profile,"private"),ReliabilitySeverity.Warning,"subject",new("test","id","test:id"),new Dictionary<string,string>{{"eventId","41"},{"token","secret"}},"v");var directory=Path.Combine(Path.GetTempPath(),$"waid-timeline-export-{Guid.NewGuid():N}");try{var path=await new ReliabilityTimelineExporter().ExportJsonAsync(new([e],0,50,1),directory,CancellationToken.None);var json=await File.ReadAllTextAsync(path);Assert.DoesNotContain(profile,json,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("token",json,StringComparison.OrdinalIgnoreCase);Assert.Contains("not proof of causation",json,StringComparison.OrdinalIgnoreCase);}finally{if(Directory.Exists(directory))Directory.Delete(directory,true);}}
 [Fact]public void Query_validation_bounds_pagination_and_search(){Assert.Throws<ArgumentOutOfRangeException>(()=>new TimelineQuery(0,201).Validate());Assert.Throws<ArgumentOutOfRangeException>(()=>new TimelineQuery(0,10,Search:new string('x',101)).Validate());}
 private static NormalizedTimelineRecord R(string id,DateTimeOffset time,string subject,ReliabilityEventKind kind=ReliabilityEventKind.Alert)=>new(kind,time,id,id,ReliabilitySeverity.Warning,subject,new("test",id,$"test:{id}"),new Dictionary<string,string>{{"eventId",id}});
 private static TestHarness Harness(IReadOnlyList<NormalizedTimelineRecord>records){var repo=new Repository();return new(new ReliabilityTimelineProjector([new Source(records)],repo,TimeProvider.System),repo);}private sealed record TestHarness(ReliabilityTimelineProjector Projector,Repository Repository);private sealed class Source(IReadOnlyList<NormalizedTimelineRecord> records):IReliabilityTimelineSource{public Task<IReadOnlyList<NormalizedTimelineRecord>>ReadAsync(DateTimeOffset?f,DateTimeOffset?t,int max,CancellationToken token)=>Task.FromResult<IReadOnlyList<NormalizedTimelineRecord>>(records.Take(max).ToArray());}private sealed class Repository:IReliabilityTimelineRepository{public ReliabilityTimelineProjection?Projection;public Task ReplaceAsync(ReliabilityTimelineProjection p,CancellationToken t){Projection=p;return Task.CompletedTask;}public Task<TimelinePage>QueryAsync(TimelineQuery q,CancellationToken t)=>Task.FromResult(new TimelinePage([],q.Page,q.PageSize,0));public Task<ReliabilityIncident?>GetIncidentAsync(string id,CancellationToken t)=>Task.FromResult<ReliabilityIncident?>(Projection?.Incidents.FirstOrDefault(x=>x.Id==id));public Task<IReadOnlyList<ReliabilityIncident>>GetRecentIncidentsAsync(int count,CancellationToken t)=>Task.FromResult<IReadOnlyList<ReliabilityIncident>>(Projection?.Incidents.Take(count).ToArray()??[]);}}
