using WAID.Application.Abstractions;using WAID.Application.Services;using WAID.Diagnosis;using WAID.Domain.Diagnostics;using WAID.Domain.Repairs;using WAID.Health;namespace WAID.Application.Tests;public sealed class RepairPrioritizationV2Tests
{
 [Fact]public void Identical_inputs_produce_identical_order_and_factors(){var e=Engine("waid.dism","waid.sfc");var r=Report("waid.sfc","waid.dism");var a=e.Prioritize(r).ToArray();var b=e.Prioritize(r).ToArray();Assert.Equal(a.Select(x=>x.RepairId),b.Select(x=>x.RepairId));Assert.Equal(a.Select(x=>x.RankingFactors),b.Select(x=>x.RankingFactors));Assert.All(a,x=>Assert.Equal(RepairPrioritizationEngine.RankingVersion,x.RankingVersion));}
 [Fact]public void Unregistered_repairs_are_never_candidates(){var run=Engine("waid.dism").Evaluate(Report("plugin.unknown"),RepairRankingContext.Default);Assert.Empty(run.Ranked);Assert.Empty(run.Decisions);}
 [Fact]public void Conflicts_reject_candidate(){var context=RepairRankingContext.Default with{Conflicts=new Dictionary<string,IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase){{"waid.dism",["servicing operation active"]}}};var run=Engine("waid.dism").Evaluate(Report("waid.dism"),context);Assert.Empty(run.Ranked);Assert.Equal(RepairCandidateStatus.Conflict,Assert.Single(run.Decisions).Status);}
 [Fact]public void Policy_blocks_repairs_above_maximum_risk(){var context=RepairRankingContext.Default with{MaximumRisk=SafetyLevel.Low};var decision=Assert.Single(Engine("waid.dism").Evaluate(Report("waid.dism"),context).Decisions);Assert.Equal(RepairCandidateStatus.BlockedByPolicy,decision.Status);Assert.False(decision.AutoSelectable);}
 [Fact]public void Missing_prerequisites_reject_candidate(){var context=RepairRankingContext.Default with{AvailablePrerequisites=new HashSet<string>(StringComparer.OrdinalIgnoreCase)};var decision=Assert.Single(Engine("waid.dism").Evaluate(Report("waid.dism"),context).Decisions);Assert.Equal(RepairCandidateStatus.PrerequisiteMissing,decision.Status);Assert.Contains("backup",decision.MissingPrerequisites);}
 [Fact]public void Feedback_is_bounded_and_high_risk_is_never_auto_selected(){var feedback=new RepairFeedbackAggregate("waid.dism",10000,0,0);var context=RepairRankingContext.Default with{Feedback=new Dictionary<string,RepairFeedbackAggregate>{{"waid.dism",feedback}}};var item=Assert.Single(Engine("waid.dism").Evaluate(Report("waid.dism"),context).Ranked);Assert.Equal(10,item.RankingFactors!.FeedbackAdjustment);Assert.False(item.AutoSelectable);}
 private static RepairPrioritizationEngine Engine(params string[] ids)=>new(new RepairRegistry(ids.Select(x=>(IRepairModule)new Module(x))));
 private static AIReport Report(params string[] ids){var f=new DiagnosticFinding("scanner","CBS_CORRUPTION","CBS","evidence",DiagnosticSeverity.Critical);var causes=ids.Select((id,i)=>new RootCause($"c{i}",id,[f],90,DiagnosticSeverity.Critical,1,new(id,id,1,DiagnosticSeverity.Critical,90),"explanation")).ToArray();return new(DateTimeOffset.UtcNow,"summary",new HealthScore(70,70,70,70,70,70,70,70),causes,[],[f]);}
 private sealed class Module(string id):IRepairModule{public string Id=>id;public string DisplayName=>id;public string Description=>id;public RepairPolicy Policy{get;}=new(SafetyLevel.High);public Task<RepairPlan>CreatePlanAsync(DiagnosticFinding? finding,CancellationToken token)=>Task.FromResult(new RepairPlan([],id));public Task<RepairResult>ExecuteAsync(RepairExecutionContext context,CancellationToken token)=>Task.FromResult(RepairResult.Success("done"));}
}