using WAID.Application.Abstractions;using WAID.Application.Services;using WAID.Domain.Diagnostics;
namespace WAID.Application.Tests;
public sealed class TechnicianDashboardTests
{
 [Fact]public async Task Defaults_to_simple_profile_and_composes_real_service_results(){var f=new Fixture();var result=await f.Service.LoadAsync(CancellationToken.None);Assert.Equal(DashboardPresentationProfile.Simple,result.Preferences.Profile);Assert.Empty(result.ActiveIncidents);}
 [Fact]public async Task Profile_switch_and_layout_are_persisted_without_security_role(){var f=new Fixture();await f.Service.SavePreferencesAsync(new(DashboardPresentationProfile.Technician,TechnicianLayout.Detailed,"critical",DateTimeOffset.MinValue),CancellationToken.None);Assert.Equal(DashboardPresentationProfile.Technician,f.Workspace.Preferences.Profile);Assert.Equal(TechnicianLayout.Detailed,f.Workspace.Preferences.Layout);}
 [Fact]public async Task Large_filter_and_case_inputs_are_bounded_before_persistence(){var f=new Fixture();await Assert.ThrowsAsync<ArgumentOutOfRangeException>(()=>f.Service.SavePreferencesAsync(new(DashboardPresentationProfile.Technician,TechnicianLayout.Compact,new string('x',201),DateTimeOffset.MinValue),CancellationToken.None));await Assert.ThrowsAsync<ArgumentException>(()=>f.Service.SaveCaseAsync(new(Guid.NewGuid(),"case","title",new string('x',4001),DateTimeOffset.UtcNow,DateTimeOffset.UtcNow),CancellationToken.None));}
 private sealed class Fixture{public Workspace Workspace{get;}=new();public TechnicianDashboardService Service{get;}public Fixture(){Service=new(new Scans(),new Repairs(),new Outcomes(),Workspace,TimeProvider.System);}}
 private sealed class Scans:IScanRepository{public Task SaveAsync(ScanSession s,CancellationToken t)=>Task.CompletedTask;public Task<IReadOnlyList<ScanSession>>GetRecentAsync(int c,CancellationToken t)=>Task.FromResult<IReadOnlyList<ScanSession>>([]);}
 private sealed class Repairs:IRepairOrchestrationRepository{public Task SaveAsync(RepairOrchestrationRecord r,CancellationToken t)=>Task.CompletedTask;public Task<RepairOrchestrationRecord?>GetAsync(Guid id,CancellationToken t)=>Task.FromResult<RepairOrchestrationRecord?>(null);public Task<IReadOnlyList<RepairOrchestrationRecord>>GetRecentAsync(int c,CancellationToken t)=>Task.FromResult<IReadOnlyList<RepairOrchestrationRecord>>([]);public Task<IReadOnlyList<RepairOrchestrationRecord>>GetNonTerminalAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<RepairOrchestrationRecord>>([]);}
 private sealed class Outcomes:IRepairOutcomeRepository{public Task AppendAsync(RepairAuditEntry e,CancellationToken t)=>Task.CompletedTask;public Task<IReadOnlyList<RepairAuditEntry>>QueryAsync(RepairAuditQuery q,CancellationToken t)=>Task.FromResult<IReadOnlyList<RepairAuditEntry>>([]);public Task ReplaceAggregatesAsync(IReadOnlyList<RepairOutcomeAggregate>a,CancellationToken t)=>Task.CompletedTask;public Task<IReadOnlyList<RepairOutcomeAggregate>>GetAggregatesAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<RepairOutcomeAggregate>>([]);}
 public sealed class Workspace:ITechnicianWorkspaceRepository{public TechnicianPreferences Preferences=new(DashboardPresentationProfile.Simple,TechnicianLayout.Compact,"",DateTimeOffset.UtcNow);public Task<TechnicianPreferences>GetPreferencesAsync(CancellationToken t)=>Task.FromResult(Preferences);public Task SavePreferencesAsync(TechnicianPreferences v,CancellationToken t){Preferences=v;return Task.CompletedTask;}public Task<IReadOnlyList<TechnicianCase>>GetCasesAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<TechnicianCase>>([]);public Task SaveCaseAsync(TechnicianCase v,CancellationToken t)=>Task.CompletedTask;}
}
