using System.Text.Json;
using System.Net;
using Microsoft.Extensions.Logging;
using WAID.Application.Abstractions;
using WAID.Infrastructure.PowerShell;

namespace WAID.Infrastructure.Diagnostics;

public sealed class WindowsNetworkEvidenceProvider(IPowerShellRunner powerShell) : INetworkEvidenceProvider
{
    private const string Script = """
param($DnsName,$HttpEndpoint,$TimeoutMs)
$tests=@();$sw=[Diagnostics.Stopwatch]::StartNew();try{$null=[System.Net.NetworkInformation.NetworkInterface]::GetIsNetworkAvailable();$tests+=[pscustomobject]@{id='local-stack';layer='LocalStack';name='Windows network stack';status='Passed';duration=$sw.ElapsedMilliseconds;latency=$null;loss=$null;detail='Windows network stack API responded.';source='NetworkInterface.GetIsNetworkAvailable'}}catch{$tests+=[pscustomobject]@{id='local-stack';layer='LocalStack';name='Windows network stack';status='Failed';duration=$sw.ElapsedMilliseconds;latency=$null;loss=$null;detail='Windows network stack API failed.';source='NetworkInterface.GetIsNetworkAvailable'}}
$cfg=@(Get-NetIPConfiguration -ErrorAction SilentlyContinue);$adapters=@($cfg|ForEach-Object{[pscustomobject]@{id="$($_.InterfaceIndex)";name="$($_.InterfaceAlias)";type="$($_.NetAdapter.MediaType)";status="$($_.NetAdapter.Status)";addresses=@($_.IPv4Address.IPAddress;$_.IPv6Address.IPAddress)|Where-Object{$_};dns=@($_.DNSServer.ServerAddresses);gateway="$($_.IPv4DefaultGateway.NextHop)";wifi=$null;signal=$null}})
$routes=@(Get-NetRoute -AddressFamily IPv4 -ErrorAction SilentlyContinue|Where-Object DestinationPrefix-eq'0.0.0.0/0'|Select-Object -First 16|ForEach-Object{[pscustomobject]@{destination="$($_.DestinationPrefix)";nextHop="$($_.NextHop)";metric=[int]$_.RouteMetric;interfaceId="$($_.InterfaceIndex)"}})
$gateway=@($adapters|Where-Object gateway|Select-Object -First 1).gateway;if($gateway){$sw.Restart();$ping=Test-Connection -TargetName $gateway -Count 2 -TimeoutSeconds ([Math]::Max(1,[Math]::Ceiling($TimeoutMs/1000))) -ErrorAction SilentlyContinue;$loss=100-(@($ping).Count*50);$tests+=[pscustomobject]@{id='gateway';layer='LanGateway';name='Default gateway';status=$(if($ping){'Passed'}else{'TimedOut'});duration=$sw.ElapsedMilliseconds;latency=$(if($ping){(@($ping|Measure-Object Latency -Average).Average)}else{$null});loss=$loss;detail=$(if($ping){'Default gateway responded.'}else{'Default gateway did not respond within the bounded timeout.'});source='Test-Connection'}}else{$tests+=[pscustomobject]@{id='gateway';layer='LanGateway';name='Default gateway';status='Unavailable';duration=0;latency=$null;loss=$null;detail='No IPv4 default gateway was reported.';source='Get-NetIPConfiguration'}}
if($DnsName){$sw.Restart();try{$answer=Resolve-DnsName -Name $DnsName -DnsOnly -ErrorAction Stop;$tests+=[pscustomobject]@{id='dns';layer='Dns';name='DNS resolution';status='Passed';duration=$sw.ElapsedMilliseconds;latency=$sw.Elapsed.TotalMilliseconds;loss=0;detail='The user-selected DNS name resolved.';source='Resolve-DnsName'}}catch{$tests+=[pscustomobject]@{id='dns';layer='Dns';name='DNS resolution';status='Failed';duration=$sw.ElapsedMilliseconds;latency=$null;loss=100;detail='The user-selected DNS name did not resolve.';source='Resolve-DnsName'}}}else{$tests+=[pscustomobject]@{id='dns';layer='Dns';name='DNS resolution';status='Skipped';duration=0;latency=$null;loss=$null;detail='No DNS probe name was configured.';source='User configuration'}}
if($HttpEndpoint){$sw.Restart();try{$response=Invoke-WebRequest -Uri $HttpEndpoint -Method Head -TimeoutSec ([Math]::Max(1,[Math]::Ceiling($TimeoutMs/1000))) -MaximumRedirection 0 -SkipHttpErrorCheck;$captive=($response.StatusCode-ge300-and$response.StatusCode-lt400);$tests+=[pscustomobject]@{id='http';layer='Application';name='Configured HTTP endpoint';status=$(if($captive){'Failed'}else{'Passed'});duration=$sw.ElapsedMilliseconds;latency=$sw.Elapsed.TotalMilliseconds;loss=0;detail=$(if($captive){'Unexpected redirect may indicate a captive portal.'}else{"Configured endpoint returned HTTP $($response.StatusCode)."});source='Invoke-WebRequest'}}catch{$tests+=[pscustomobject]@{id='http';layer='Application';name='Configured HTTP endpoint';status='TimedOut';duration=$sw.ElapsedMilliseconds;latency=$null;loss=100;detail='Configured endpoint did not respond within the bounded timeout.';source='Invoke-WebRequest'}}}else{$tests+=[pscustomobject]@{id='http';layer='Application';name='Configured HTTP endpoint';status='Skipped';duration=0;latency=$null;loss=$null;detail='No application endpoint was configured; WAID does not contact a hard-coded public service.';source='User configuration'}}
$proxy=Get-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -ErrorAction SilentlyContinue;$vpn=@(Get-VpnConnection -AllUserConnection -ErrorAction SilentlyContinue;Get-VpnConnection -ErrorAction SilentlyContinue)|Where-Object ConnectionStatus-eq'Connected';$firewall=@(Get-NetFirewallProfile -ErrorAction SilentlyContinue);$services=@(Get-Service Dhcp,Dnscache,NlaSvc -ErrorAction SilentlyContinue|Where-Object Status-ne'Running'|ForEach-Object{$_.Name});[pscustomobject]@{adapters=$adapters;routes=$routes;proxy=[pscustomobject]@{enabled=([bool]$proxy.ProxyEnable);mode=$(if($proxy.AutoConfigURL){'Automatic script'}elseif($proxy.ProxyEnable){'Manual'}else{'Direct'});host="$($proxy.ProxyServer)";bypass="$($proxy.ProxyOverride)"};vpnActive=(@($vpn).Count-gt0);firewall=$(if($firewall-and@($firewall|Where-Object Enabled).Count-eq@($firewall).Count){'Enabled'}elseif($firewall){'Partially disabled'}else{'Unavailable'});services=$services;tests=$tests}|ConvertTo-Json -Depth 8 -Compress
""";

    public async Task<NetworkSnapshot> CollectAsync(NetworkProbeOptions options, CancellationToken token)
    {
        options.Validate();
        var result = await powerShell.RunAsync(Script, new Dictionary<string, object?> { ["DnsName"] = CleanName(options.DnsName), ["HttpEndpoint"] = options.HttpEndpoint?.AbsoluteUri, ["TimeoutMs"] = options.TimeoutMilliseconds }, token);
        if (!result.Succeeded) throw new NetworkDiagnosticException("WAID-NETWORK-COLLECT", "Network evidence could not be collected.", string.Join("; ", result.Errors));
        var payload = JsonSerializer.Deserialize<Payload>(string.Join(Environment.NewLine, result.Output), new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? throw new NetworkDiagnosticException("WAID-NETWORK-DATA", "Windows returned empty network evidence.", "No payload.");
        return new(DateTimeOffset.UtcNow, (payload.Adapters ?? []).Select(a => new NetworkAdapterSnapshot(Clean(a.Id), Clean(a.Name), Clean(a.Type), Clean(a.Status), SafeList(a.Addresses, true), SafeList(a.Dns, true), MaskAddress(a.Gateway), Empty(a.Wifi), a.Signal)).ToArray(), (payload.Routes ?? []).Select(r => new NetworkRouteSnapshot(Clean(r.Destination), MaskAddress(r.NextHop) ?? "", Math.Max(0, r.Metric), Clean(r.InterfaceId))).ToArray(), new(payload.Proxy?.Enabled == true, Clean(payload.Proxy?.Mode), RedactProxy(payload.Proxy?.Host), "[redacted]"), payload.VpnActive, Clean(payload.Firewall), SafeList(payload.Services), (payload.Tests ?? []).Select(ToTest).ToArray(), ["IP addresses are subnet-masked and proxy bypass values are excluded before persistence and export."]);
    }
    private static NetworkTestResult ToTest(TestDto x) => new(Clean(x.Id), Enum.TryParse<NetworkLayer>(x.Layer, true, out var layer) ? layer : NetworkLayer.LocalStack, Clean(x.Name), Enum.TryParse<NetworkTestStatus>(x.Status, true, out var status) ? status : NetworkTestStatus.Unavailable, TimeSpan.FromMilliseconds(Math.Max(0, x.Duration)), x.Latency is >= 0 and < 60000 ? x.Latency : null, x.Loss is >= 0 and <= 100 ? x.Loss : null, Clean(x.Detail), Clean(x.Source));
    private static string? CleanName(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; var name = value.Trim(); if (name.Length > 253 || name.Any(c => !(char.IsLetterOrDigit(c) || c is '.' or '-'))) throw new ArgumentException("DNS probe name is invalid.", nameof(value)); return name; }
    private static string Clean(string? value) => (value ?? "").Replace(Environment.UserName, "[user]", StringComparison.OrdinalIgnoreCase).Trim();
    private static string? Empty(string? value) => string.IsNullOrWhiteSpace(value) ? null : Clean(value);
    private static IReadOnlyList<string> SafeList(string[]? values, bool maskAddresses = false) => (values ?? []).Where(v => !string.IsNullOrWhiteSpace(v)).Select(v => maskAddresses ? MaskAddress(v) ?? "" : Clean(v)).Where(v => v.Length > 0).Take(64).ToArray();
    private static string? MaskAddress(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; var text = value.Split('%')[0]; if (!IPAddress.TryParse(text, out var address)) return "[address]"; var bytes = address.GetAddressBytes(); if (bytes.Length == 4) { bytes[3] = 0; return $"{new IPAddress(bytes)}/24"; } Array.Clear(bytes, 8, 8); return $"{new IPAddress(bytes)}/64"; }
    private static string? RedactProxy(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; return Uri.TryCreate(value.Contains("://", StringComparison.Ordinal) ? value : $"http://{value}", UriKind.Absolute, out var uri) ? uri.IsDefaultPort ? uri.Host : $"{uri.Host}:{uri.Port}" : "[configured]"; }
    private sealed record Payload(AdapterDto[]? Adapters, RouteDto[]? Routes, ProxyDto? Proxy, bool VpnActive, string? Firewall, string[]? Services, TestDto[]? Tests);
    private sealed record AdapterDto(string? Id, string? Name, string? Type, string? Status, string[]? Addresses, string[]? Dns, string? Gateway, string? Wifi, int? Signal);
    private sealed record RouteDto(string? Destination, string? NextHop, int Metric, string? InterfaceId);
    private sealed record ProxyDto(bool Enabled, string? Mode, string? Host, string? Bypass);
    private sealed record TestDto(string? Id, string? Layer, string? Name, string? Status, double Duration, double? Latency, double? Loss, string? Detail, string? Source);
}

public sealed class NetworkDiagnosticCenter(INetworkEvidenceProvider provider, INetworkHealthRepository repository, ILogger<NetworkDiagnosticCenter> logger, string exportDirectory) : INetworkDiagnosticCenter
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web) { WriteIndented = true };
    public async Task<NetworkHealthReport> AnalyzeAsync(NetworkProbeOptions options, CancellationToken token)
    {
        var snapshot = await provider.CollectAsync(options, token); var findings = Evaluate(snapshot); var topology = BuildTopology(snapshot);
        var report = new NetworkHealthReport(Guid.NewGuid(), snapshot.CollectedAtUtc, snapshot, findings, topology, snapshot.Limitations);
        await repository.SaveAsync(report, token); logger.LogInformation("Network report {ReportId} stored with {FindingCount} findings", report.Id, findings.Count); return report;
    }
    public async Task<string> ExportAsync(NetworkHealthReport report, CancellationToken token) { Directory.CreateDirectory(exportDirectory); var path = Path.Combine(exportDirectory, $"waid-network-{report.GeneratedAtUtc:yyyyMMdd-HHmmss}.json"); await File.WriteAllTextAsync(path, JsonSerializer.Serialize(report, JsonOptions), token); return path; }
    public static IReadOnlyList<NetworkFinding> Evaluate(NetworkSnapshot snapshot)
    {
        var findings = new List<NetworkFinding>();
        void Add(NetworkLayer layer, string code, string title, string explanation, string severity, double confidence, string source, string? repair = null) => findings.Add(new(layer, code, title, explanation, severity, confidence, [new("test", code, source, snapshot.CollectedAtUtc)], repair, repair is not null));
        if (!snapshot.Adapters.Any(a => a.Status.Equals("Up", StringComparison.OrdinalIgnoreCase))) Add(NetworkLayer.Adapter, "ADAPTER_OFFLINE", "No active network adapter", "Windows does not report an active adapter. Check the physical connection, Wi-Fi state, or adapter status before resetting the stack.", "Warning", .98, "Get-NetIPConfiguration");
        if (snapshot.Adapters.Any(a => a.Status.Equals("Up", StringComparison.OrdinalIgnoreCase)) && snapshot.Routes.Count == 0) Add(NetworkLayer.LanGateway, "DEFAULT_ROUTE_MISSING", "No default route", "An adapter is active but Windows reports no IPv4 default route. Review DHCP, static IP, VPN, and gateway configuration before considering a stack reset.", "Warning", .96, "Get-NetRoute");
        if (snapshot.Adapters.Any(a => a.Status.Equals("Up", StringComparison.OrdinalIgnoreCase) && a.Addresses.Count == 0)) Add(NetworkLayer.Adapter, "IP_NOT_CONFIGURED", "Active adapter has no IP address", "Windows reports an active adapter without an assigned IP address. TCP/IP reset is supported only because adapter configuration evidence is present.", "Warning", .95, "Get-NetIPConfiguration", "waid.tcpip-reset");
        if (snapshot.Adapters.Any(a => a.Status.Equals("Up", StringComparison.OrdinalIgnoreCase) && a.DnsServers.Count == 0)) Add(NetworkLayer.Dns, "DNS_NOT_CONFIGURED", "DNS is not configured", "An active adapter has no DNS server. A DNS reset is supported only because configuration evidence is present.", "Warning", .95, "Get-NetIPConfiguration", "waid.dns-reset");
        if (!snapshot.FirewallState.Equals("Enabled", StringComparison.OrdinalIgnoreCase)) Add(NetworkLayer.Firewall, "FIREWALL_STATE_DEGRADED", "Firewall profile state needs review", $"Windows reports the firewall state as {snapshot.FirewallState}. Open Windows Security to review profiles; WAID will not weaken firewall policy.", "Warning", .9, "Get-NetFirewallProfile");
        foreach (var test in snapshot.Tests.Where(t => t.Status is NetworkTestStatus.Failed or NetworkTestStatus.TimedOut))
        {
            var code = test.Id == "http" && test.Detail.Contains("captive portal", StringComparison.OrdinalIgnoreCase) ? "CAPTIVE_PORTAL" : $"{test.Layer.ToString().ToUpperInvariant()}_FAILED";
            var repair = test.Layer == NetworkLayer.Dns ? "waid.dns-reset" : test.Layer == NetworkLayer.LocalStack ? "waid.winsock-reset" : null;
            Add(test.Layer, code, $"{test.Name} failed", test.Detail, test.Status == NetworkTestStatus.Failed ? "Warning" : "Information", test.Status == NetworkTestStatus.Failed ? .9 : .75, test.SourceReference, repair);
        }
        if (snapshot.Proxy.Enabled && snapshot.Tests.Any(t => t.Layer == NetworkLayer.Application && t.Status == NetworkTestStatus.Failed)) Add(NetworkLayer.Proxy, "PROXY_PATH_FAILURE", "Proxy may be blocking the configured endpoint", "A proxy is configured and the application-layer test failed. Review the proxy configuration; WAID will not change it automatically.", "Warning", .78, "Internet Settings");
        if (snapshot.RequiredServiceFailures.Count > 0) Add(NetworkLayer.LocalStack, "NETWORK_SERVICE_STOPPED", "Required network service is stopped", $"Stopped services: {string.Join(", ", snapshot.RequiredServiceFailures)}.", "Warning", .95, "Get-Service");
        return findings;
    }
    private static IReadOnlyList<string> BuildTopology(NetworkSnapshot snapshot) { var active = snapshot.Adapters.FirstOrDefault(a => a.Status.Equals("Up", StringComparison.OrdinalIgnoreCase)); return active is null ? ["Computer -> no active adapter"] : [$"Computer -> {active.Name}", active.Gateway is null ? "Adapter -> no default gateway" : $"Adapter -> gateway {active.Gateway}", active.DnsServers.Count == 0 ? "Adapter -> no DNS servers" : $"Adapter -> {active.DnsServers.Count} DNS server(s)", snapshot.Proxy.Enabled ? $"Application -> {snapshot.Proxy.Mode} proxy" : "Application -> direct connection"]; }
}

public sealed class NetworkDiagnosticException(string code, string message, string detail) : InvalidOperationException(message) { public string Code { get; } = code; public string Detail { get; } = detail; }
