using System.Text.Json;using System.Text.RegularExpressions;using Microsoft.Extensions.Logging;using WAID.Application.Abstractions;using WAID.Infrastructure.PowerShell;
namespace WAID.Infrastructure.Diagnostics;
public sealed class WindowsUpdateEvidenceProvider(IPowerShellRunner powerShell):IWindowsUpdateEvidenceProvider
{
 private const string Script="""
 $attempts=@();try{$s=New-Object -ComObject Microsoft.Update.Session;$attempts=@($s.CreateUpdateSearcher().QueryHistory(0,100)|ForEach-Object{$kb=if($_.Title-match'KB\d+'){$Matches[0]}else{$null};[pscustomobject]@{time=$_.Date.ToUniversalTime().ToString('O');title=$_.Title;kb=$kb;code=('0x{0:X8}'-f($_.HResult-band 0xffffffffL));state=switch($_.ResultCode){2{'Succeeded'}4{'Failed'}5{'Failed'}default{'Unknown'}};reference="WindowsUpdateHistory:$($_.Date.ToUniversalTime().Ticks)"}})}catch{}
 $services=@(Get-CimInstance Win32_Service -Filter "Name='wuauserv' OR Name='BITS' OR Name='cryptsvc' OR Name='TrustedInstaller'" -ErrorAction SilentlyContinue|ForEach-Object{[pscustomobject]@{name=$_.Name;state=$_.State;startMode=$_.StartMode;reference="Service:$($_.Name)"}})
 $wu='HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate';$au=Join-Path $wu 'AU';$disabled=[bool]((Get-ItemProperty $au -Name NoAutoUpdate -ErrorAction SilentlyContinue).NoAutoUpdate);$managed=(Test-Path $wu);$policy=[pscustomobject]@{managed=$managed;disabled=$disabled;detail=if($disabled){'Automatic updates are disabled by policy.'}elseif($managed){'Windows Update policy is configured.'}else{'No machine Windows Update policy was detected.'};reference='Registry:WindowsUpdatePolicy'}
 $reboot=(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired')-or[bool](Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' -Name PendingFileRenameOperations -ErrorAction SilentlyContinue)
 $dism='Unavailable';try{$dism=((& dism.exe /Online /Cleanup-Image /CheckHealth /English 2>&1)|Select-Object -Last 12)-join' '}catch{};$repairable=$dism-match'repairable';$corrupt=$repairable-or(($dism-match'component store corruption detected')-and($dism-notmatch'No component store corruption detected'))
 $cbs='No recent CBS corruption event found.';$events=@(Get-WinEvent -FilterHashtable @{LogName='System';StartTime=(Get-Date).AddDays(-30);Id=20,25,31,34} -ErrorAction SilentlyContinue|Select-Object -First 100);$codes=@($events|ForEach-Object{if($_.Message-match'0x[0-9A-Fa-f]{8}'){$Matches[0].ToUpperInvariant()}}|Where-Object{$_}|Select-Object -Unique);if($events.Message-match'CBS|component store|servicing'){$cbs='Recent Windows servicing events report a component-store or CBS condition.'}
 $drive=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='$($env:SystemDrive)'" -ErrorAction SilentlyContinue
 [pscustomobject]@{attempts=$attempts;services=$services;policy=$policy;rebootPending=$reboot;dism=$dism;cbs=$cbs;corruption=$corrupt;repairable=$repairable;freeBytes=[long]$drive.FreeSpace;eventCodes=$codes}|ConvertTo-Json -Depth 6 -Compress
 """;
 public async Task<UpdateEvidenceSnapshot> CollectAsync(CancellationToken token){var r=await powerShell.RunAsync(Script,new Dictionary<string,object?>(),token).ConfigureAwait(false);if(!r.Succeeded)throw new WindowsUpdateIntelligenceException("WAID-WU-COLLECT","Windows Update evidence could not be collected.",string.Join("; ",r.Errors));var p=JsonSerializer.Deserialize<Payload>(string.Join(Environment.NewLine,r.Output),Options)??throw new WindowsUpdateIntelligenceException("WAID-WU-DATA","Windows returned empty update evidence.","No payload was returned.");var now=DateTimeOffset.UtcNow;var attempts=(p.Attempts??[]).Where(x=>DateTimeOffset.TryParse(x.Time,out _)).Take(500).Select(x=>new UpdateAttempt(DateTimeOffset.Parse(x.Time!).ToUniversalTime(),Clean(x.Title),NormalizeKb(x.Kb),NormalizeCode(x.Code),Enum.TryParse<UpdateAttemptState>(x.State,true,out var state)?state:UpdateAttemptState.Unknown,Clean(x.Reference))).ToArray();var services=(p.Services??[]).Where(x=>!string.IsNullOrWhiteSpace(x.Name)).Select(x=>new UpdateServiceState(Clean(x.Name),Clean(x.State),Clean(x.StartMode),Clean(x.Reference))).ToArray();var limitations=new List<string>();if(attempts.Length==0)limitations.Add("Windows Update history is unavailable or empty; no success or failure is inferred.");if(string.Equals(p.Dism,"Unavailable",StringComparison.OrdinalIgnoreCase))limitations.Add("DISM CheckHealth was unavailable, commonly because the process is not elevated.");return new(now,attempts,services,new(p.Policy?.Managed??false,p.Policy?.Disabled??false,Clean(p.Policy?.Detail),Clean(p.Policy?.Reference)),new(p.Repairable,p.Corruption,Clean(p.Dism,1000),Clean(p.Cbs,500),"DISM CheckHealth and Windows servicing events"),p.RebootPending,Math.Max(0,p.FreeBytes),(p.EventCodes??[]).Select(NormalizeCode).Where(x=>x!="0X00000000").Distinct().ToArray(),limitations);}
 private static string NormalizeCode(string? v){var s=(v??"").Trim().ToUpperInvariant();if(Regex.IsMatch(s,"^0X[0-9A-F]{8}$"))return s;return "0X00000000";}private static string? NormalizeKb(string? v)=>Regex.IsMatch(v??"",@"^KB\d{4,8}$",RegexOptions.IgnoreCase)?v!.ToUpperInvariant():null;private static string Clean(string? v,int max=300){var s=(v??"").Replace(Environment.UserName,"[user]",StringComparison.OrdinalIgnoreCase).Trim();return s.Length<=max?s:s[..max];}private static readonly JsonSerializerOptions Options=new(){PropertyNameCaseInsensitive=true};private sealed record Payload(AttemptDto[]? Attempts,ServiceDto[]? Services,PolicyDto? Policy,bool RebootPending,string? Dism,string? Cbs,bool Corruption,bool Repairable,long FreeBytes,string[]? EventCodes);private sealed record AttemptDto(string? Time,string? Title,string? Kb,string? Code,string? State,string? Reference);private sealed record ServiceDto(string? Name,string? State,string? StartMode,string? Reference);private sealed record PolicyDto(bool Managed,bool Disabled,string? Detail,string? Reference);
}
public sealed class WindowsUpdateIntelligence(IWindowsUpdateEvidenceProvider provider,IWindowsUpdateHealthRepository repository,ILogger<WindowsUpdateIntelligence> logger):IWindowsUpdateIntelligence
{
 public async Task<WindowsUpdateHealthReport> AnalyzeAsync(CancellationToken token){var s=await provider.CollectAsync(token).ConfigureAwait(false);var d=Diagnose(s);var plan=Plan(d,s);var report=new WindowsUpdateHealthReport(Guid.NewGuid(),s.CollectedAtUtc,s.Attempts,d,plan,s.RebootPending,s.Limitations);await repository.SaveAsync(s,report,token).ConfigureAwait(false);logger.LogInformation("Windows Update analysis {ReportId} stored {AttemptCount} attempts and {DiagnosisCount} diagnoses",report.Id,report.Attempts.Count,report.Diagnoses.Count);return report;}
 public static IReadOnlyList<UpdateDiagnosis> Diagnose(UpdateEvidenceSnapshot s){var now=s.CollectedAtUtc;var list=new List<UpdateDiagnosis>();var codes=s.Attempts.Where(x=>x.State==UpdateAttemptState.Failed).Select(x=>x.ErrorCode).Concat(s.EventCodes).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();foreach(var group in codes.Select(ErrorCatalog.Map).Where(x=>x.Cause!=UpdateCause.Unknown).GroupBy(x=>x.Cause)){var m=group.First();list.Add(D(m.Cause,m.Title,m.Explanation,.93,m.Severity,group.Select(x=>new UpdateEvidence("errorCode",x.Code,"Windows Update history or event log",now)).ToArray()));}if(s.Policy.UpdatesDisabled)list.Add(D(UpdateCause.Policy,"Updates are blocked by policy",s.Policy.Detail,.99,"Warning",[new("policyDisabled","true",s.Policy.SourceReference,now)]));if(s.RebootPending)list.Add(D(UpdateCause.Reboot,"Windows restart is pending","Servicing cannot reliably continue until the pending restart is completed.",.98,"Warning",[new("rebootPending","true","Windows servicing reboot markers",now)]));if(s.SystemDriveFreeBytes>0&&s.SystemDriveFreeBytes<10L*1024*1024*1024)list.Add(D(UpdateCause.Storage,"System drive space is constrained","Windows Update may not have enough working space to stage and service packages.",.92,s.SystemDriveFreeBytes<5L*1024*1024*1024?"Critical":"Warning",[new("freeBytes",s.SystemDriveFreeBytes.ToString(),"Win32_LogicalDisk",now)]));if(s.Servicing.CorruptionDetected)list.Add(D(UpdateCause.Servicing,"Component store requires attention",s.Servicing.DismSummary,.96,"Critical",[new("dismSummary",s.Servicing.DismSummary,s.Servicing.SourceReference,now),new("cbsSummary",s.Servicing.CbsSummary,s.Servicing.SourceReference,now)]));foreach(var svc in s.Services.Where(x=>x.Name is "wuauserv" or "BITS" or "cryptsvc"&& !x.State.Equals("Running",StringComparison.OrdinalIgnoreCase)))list.Add(D(UpdateCause.Service,$"Required service {svc.Name} is not running",$"{svc.Name} is {svc.State} with start mode {svc.StartMode}.",.9,"Warning",[new("serviceState",svc.State,svc.SourceReference,now),new("startMode",svc.StartMode,svc.SourceReference,now)]));return list.GroupBy(x=>x.Cause).Select(x=>x.OrderByDescending(y=>y.Confidence).First()).ToArray();}
 public static UpdateRepairPlan Plan(IReadOnlyList<UpdateDiagnosis> diagnoses,UpdateEvidenceSnapshot s){var steps=new List<UpdateRepairStep>();void Add(string id,string title,string desc,string[] prereq,bool admin,bool restart)=>steps.Add(new(steps.Count+1,id,title,desc,prereq,admin,restart,false,true));if(diagnoses.Any(x=>x.Cause==UpdateCause.Reboot))Add("restart","Restart Windows","Complete pending servicing operations.",["Save open work"],false,true);if(diagnoses.Any(x=>x.Cause==UpdateCause.Storage))Add("free-space","Free supported storage space","Use Windows Storage settings or Disk Cleanup; do not delete component-store files manually.",["Review files before deletion"],false,false);if(diagnoses.Any(x=>x.Cause==UpdateCause.Service))Add("services","Restore required update services","Start supported Windows Update dependencies using Service Control Manager.",["Administrator approval"],true,false);if(diagnoses.Any(x=>x.Cause==UpdateCause.Network))Add("network","Validate Microsoft update connectivity","Check proxy, DNS, time, and network availability without bypassing policy.",["Network available"],false,false);if(diagnoses.Any(x=>x.Cause==UpdateCause.Servicing))Add("dism","Repair component store","Run DISM RestoreHealth, then SFC, through the existing approved repair workflow.",["Administrator approval","Backup and restore point when available"],true,true);if(diagnoses.Any(x=>x.Cause==UpdateCause.Policy))Add("policy","Contact the policy administrator","Do not bypass organization-managed update policy.",["Confirm device ownership and policy authority"],true,false);return new(steps,"Simulation only. Every execution requires explicit approval. WAID never removes an update silently.");}
 private static UpdateDiagnosis D(UpdateCause c,string t,string e,double confidence,string severity,IReadOnlyList<UpdateEvidence> evidence)=>new(c,t,e,confidence,severity,evidence);
}
public static class ErrorCatalog{private static readonly Dictionary<string,(UpdateCause Cause,string Title,string Explanation,string Severity)> MapData=new(StringComparer.OrdinalIgnoreCase){{"0X8024402C",(UpdateCause.Network,"Update network configuration failed","Windows Update could not resolve the configured update endpoint or proxy.","Warning")},{"0X80072EE2",(UpdateCause.Network,"Update request timed out","The update service did not respond before the supported timeout.","Warning")},{"0X800F081F",(UpdateCause.Servicing,"Repair source files were unavailable","The component store could not locate required repair content.","Critical")},{"0X80073712",(UpdateCause.Servicing,"Component store data is damaged","Windows servicing reported missing or corrupt component metadata.","Critical")},{"0X8024002E",(UpdateCause.Policy,"Update access is disabled by policy","Windows Update access is blocked by configured policy.","Warning")},{"0X80070070",(UpdateCause.Storage,"Insufficient disk space","Windows Update could not stage content because storage is constrained.","Critical")}};public static (string Code,UpdateCause Cause,string Title,string Explanation,string Severity) Map(string code)=>MapData.TryGetValue(code,out var v)?(code,v.Cause,v.Title,v.Explanation,v.Severity):(code,UpdateCause.Unknown,"Unknown Windows Update error","The offline catalog does not contain this code.","Warning");}
public sealed class UpdateRepairPlanner:IUpdateRepairPlanner{public UpdateRepairSimulation Simulate(UpdateRepairStep step,bool approved){if(!approved)return new(false,"Explicit approval is required; no action was performed.",[],step.RequiresAdministrator,step.RequiresRestart);string[] commands=step.Id switch{"services"=>["Start-Service wuauserv","Start-Service BITS","Start-Service cryptsvc"],"dism"=>["DISM.exe /Online /Cleanup-Image /RestoreHealth","sfc.exe /scannow"],"restart"=>["Restart Windows using the standard Start menu"],_=>[step.Description]};return new(true,"Simulation only. Commands are displayed but were not executed.",commands,step.RequiresAdministrator,step.RequiresRestart);}}
public sealed class WindowsUpdateIntelligenceException(string code,string message,string detail):InvalidOperationException(message){public string Code{get;}=code;public string Detail{get;}=detail;}
