using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Automation.Peers;
using Microsoft.UI.Xaml.Controls;
using WAID.Infrastructure.Plugins;
namespace WAID.Desktop.Views;
public sealed class PluginsPage:Page
{
 readonly PluginCatalog catalog;readonly PluginManager manager;readonly WAID.Infrastructure.WaidModuleCatalog modules;
 readonly StackPanel inventory=new(){Spacing=12};readonly TextBox path=new(){Header="Plugin manifest file",PlaceholderText=@"C:\Plugins\vendor.product.waid-plugin.json"};readonly CheckBox approval=new(){Content="I reviewed and approve the permissions requested by this plugin."};readonly TextBlock preview=new(){TextWrapping=TextWrapping.Wrap};readonly TextBlock status=new(){TextWrapping=TextWrapping.Wrap};
 public PluginsPage(PluginCatalog catalog,PluginManager manager,WAID.Infrastructure.WaidModuleCatalog modules){this.catalog=catalog;this.manager=manager;this.modules=modules;Build();}
 void Build(){var panel=new StackPanel{Padding=new Thickness(32),Spacing=16,MaxWidth=900,HorizontalAlignment=HorizontalAlignment.Center};var title=new TextBlock{Text="Plugin Manager",FontSize=28};Id(title,"PluginsPageTitle");Id(path,"PluginInstallPath");Id(approval,"ApprovePluginPermissions");Id(status,"PluginManagerStatus");AutomationProperties.SetLiveSetting(status,AutomationLiveSetting.Polite);panel.Children.Add(title);panel.Children.Add(new TextBlock{Text="Install only plugins you trust. WAID validates compatibility, publisher, signature policy, declared capabilities, permissions, dependencies, and assembly integrity before installation.",TextWrapping=TextWrapping.Wrap});panel.Children.Add(new TextBlock{Text="Install from file",FontSize=20});panel.Children.Add(path);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};var check=new Button{Content="Check compatibility"};var install=new Button{Content="Install certified plugin"};Id(check,"PreviewPluginInstall");Id(install,"InstallPluginFile");check.Click+=Preview;install.Click+=Install;actions.Children.Add(check);actions.Children.Add(install);panel.Children.Add(actions);panel.Children.Add(preview);panel.Children.Add(approval);panel.Children.Add(status);panel.Children.Add(new TextBlock{Text="Application modules",FontSize=20});foreach(var module in modules.Items)panel.Children.Add(new TextBlock{Text=$"{module.DisplayName} | {module.State} | {module.Detail}",TextWrapping=TextWrapping.Wrap});panel.Children.Add(new TextBlock{Text="Plugin inventory",FontSize=20});panel.Children.Add(inventory);Refresh();Content=new ScrollViewer{Content=panel};}
 void Preview(object sender,RoutedEventArgs args){try{var x=manager.PreviewInstall(path.Text.Trim());var checks=string.Join(Environment.NewLine,x.Certification.Checks.Select(c=>$"{(c.Passed?"Passed":"Blocked")}: {c.Detail}"));preview.Text=$"{x.Manifest.Name} {x.Manifest.Version}\nCertification: {(x.Certification.Certified?"Passed":"Blocked")}\nSignature: {x.Certification.SignatureStatus}\nCapabilities: {List(x.Manifest.Capabilities)}\nPermissions: {List(x.Manifest.Permissions)}\n{checks}";status.Text=x.Certification.Certified?"Compatibility check passed. Review permissions before installing.":"Installation is blocked. Correct the failed certification checks.";}catch(Exception e)when(e is IOException or UnauthorizedAccessException or InvalidDataException or System.Text.Json.JsonException){preview.Text="";status.Text=$"Unable to inspect plugin: {e.Message}";}}
 async void Install(object sender,RoutedEventArgs args){try{var x=await manager.InstallAsync(path.Text.Trim(),approval.IsChecked==true,CancellationToken.None);status.Text=$"{x.Code}: {x.Detail}";Refresh();}catch(Exception e)when(e is IOException or UnauthorizedAccessException or InvalidDataException or System.Text.Json.JsonException){status.Text=$"Plugin was not installed: {e.Message}";}}
 void Refresh(){inventory.Children.Clear();if(catalog.Items.Count==0){inventory.Children.Add(new TextBlock{Text="No plugins are installed."});return;}foreach(var item in catalog.Items.OrderBy(x=>x.Name,StringComparer.OrdinalIgnoreCase)){var card=new StackPanel{Spacing=6};card.Children.Add(new TextBlock{Text=$"{item.Name} {item.Version} — {item.State}",FontSize=18});card.Children.Add(new TextBlock{Text=$"{item.Detail}\nSignature: {item.SignatureStatus}\nCapabilities: {List(item.Capabilities)}\nPermissions: {List(item.Permissions)}",TextWrapping=TextWrapping.Wrap});var failed=item.Checks?.Where(x=>!x.Passed).Select(x=>x.Detail).ToArray()??[];if(failed.Length>0)card.Children.Add(new TextBlock{Text="Certification log: "+string.Join("; ",failed),TextWrapping=TextWrapping.Wrap});var buttons=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};buttons.Children.Add(Action("Enable",$"EnablePlugin_{item.Id}",()=>manager.SetEnabledAsync(item.Id,true,CancellationToken.None)));buttons.Children.Add(Action("Disable",$"DisablePlugin_{item.Id}",()=>manager.SetEnabledAsync(item.Id,false,CancellationToken.None)));buttons.Children.Add(Action("Quarantine",$"QuarantinePlugin_{item.Id}",()=>manager.QuarantineAsync(item.Id,CancellationToken.None)));card.Children.Add(buttons);inventory.Children.Add(card);}}
 Button Action(string label,string id,Func<Task<PluginManagementResult>> action){var b=new Button{Content=label};Id(b,id);b.Click+=async(_,_)=>{try{var x=await action();status.Text=$"{x.Code}: {x.Detail}";Refresh();}catch(InvalidOperationException e){status.Text=e.Message;}};return b;}
 static string List(IReadOnlyCollection<string>? x)=>x is null||x.Count==0?"None":string.Join(", ",x);static void Id(DependencyObject x,string id)=>AutomationProperties.SetAutomationId(x,id);
}