using System.IO.Compression;using System.Security.Cryptography;using System.Text;using System.Text.Json;using System.Text.RegularExpressions;
namespace WAID.Application.Services;
public enum SystemSnapshotPurpose{Manual,Baseline,PreRepair,PostRepair}
public enum SnapshotComponentState{Captured,Unavailable,Failed}
public enum SnapshotChangeKind{Added,Removed,Changed,Unchanged}
public sealed record SystemSnapshotComponent(string Name,string SerializerVersion,SnapshotComponentState State,IReadOnlyDictionary<string,string> Values,string? FailureCode=null,string? SafeDetail=null);
public sealed record DigitalTwinSnapshot(Guid Id,DateTimeOffset CapturedAtUtc,SystemSnapshotPurpose Purpose,bool IsPinned,string SchemaVersion,IReadOnlyList<SystemSnapshotComponent>Components,string IntegritySha256,Guid? RepairTransactionId=null,Guid? RelatedSnapshotId=null);
public sealed record SnapshotComponentChange(string Component,string Key,SnapshotChangeKind Kind,string?Before,string?After,string Risk,string Explanation);
public sealed record SystemSnapshotDiff(Guid Id,Guid BeforeId,Guid AfterId,DateTimeOffset ComparedAtUtc,string StrategyVersion,IReadOnlyList<SnapshotComponentChange>Changes,IReadOnlyList<string>RiskHighlights);
public sealed record SnapshotRetentionResult(DateTimeOffset ExecutedAtUtc,int RetentionDays,int DeletedSnapshots,int PreservedPinned,string PolicyVersion);
public interface ISystemSnapshotComponentProvider{string Name{get;}string SerializerVersion{get;}Task<IReadOnlyDictionary<string,string>>CaptureAsync(CancellationToken token);}
public interface IDigitalTwinRepository{Task SaveAsync(DigitalTwinSnapshot snapshot,byte[]compressedPayload,CancellationToken token);Task<IReadOnlyList<DigitalTwinSnapshot>>GetRecentAsync(int count,CancellationToken token);Task<DigitalTwinSnapshot?>GetAsync(Guid id,CancellationToken token);Task SaveDiffAsync(SystemSnapshotDiff diff,CancellationToken token);Task<SnapshotRetentionResult>ApplyRetentionAsync(DateTimeOffset retainAfterUtc,CancellationToken token);}
public sealed class DigitalTwinException(string code,string message,string recoveryAction,Exception?inner=null):InvalidOperationException(message,inner){public string Code{get;}=code;public string RecoveryAction{get;}=recoveryAction;}
public sealed class DigitalTwinService(IEnumerable<ISystemSnapshotComponentProvider>providers,IDigitalTwinRepository repository,TimeProvider time)
{public const string SchemaVersion="digital-twin-1.0";public const string DiffVersion="snapshot-diff-v1";private static readonly Regex Secret=new("(?i)(password|token|secret|product.?key|authorization|cookie|serial(number)?)",RegexOptions.Compiled,TimeSpan.FromMilliseconds(100));
 public async Task<DigitalTwinSnapshot>CaptureAsync(SystemSnapshotPurpose purpose,bool pinned,Guid?repairTransactionId,Guid?relatedSnapshotId,CancellationToken token){if(purpose is SystemSnapshotPurpose.PreRepair or SystemSnapshotPurpose.PostRepair&&repairTransactionId is null)throw new DigitalTwinException("WAID-TWIN-REPAIR-LINK","Repair snapshots require a repair transaction link.","Select the repair transaction and retry.");var components=new List<SystemSnapshotComponent>();foreach(var provider in providers.OrderBy(x=>x.Name,StringComparer.Ordinal)){try{var raw=await provider.CaptureAsync(token);var safe=raw.Where(x=>!Secret.IsMatch(x.Key)&&!Secret.IsMatch(x.Value)).OrderBy(x=>x.Key,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>Redact(x.Value),StringComparer.Ordinal);components.Add(new(provider.Name,provider.SerializerVersion,SnapshotComponentState.Captured,safe));}catch(OperationCanceledException){throw;}catch(Exception e){components.Add(new(provider.Name,provider.SerializerVersion,SnapshotComponentState.Failed,new Dictionary<string,string>(),"WAID-TWIN-COMPONENT",$"Capture failed with {e.GetType().Name}."));}}
 var id=Guid.NewGuid();var captured=time.GetUtcNow();var hash=Hash(Canonical(components));var snapshot=new DigitalTwinSnapshot(id,captured,purpose,pinned,SchemaVersion,components,hash,repairTransactionId,relatedSnapshotId);await repository.SaveAsync(snapshot,Compress(JsonSerializer.SerializeToUtf8Bytes(snapshot)),token);return snapshot;}
 public SystemSnapshotDiff Compare(DigitalTwinSnapshot before,DigitalTwinSnapshot after){Verify(before);Verify(after);var changes=new List<SnapshotComponentChange>();var names=before.Components.Select(x=>x.Name).Union(after.Components.Select(x=>x.Name),StringComparer.Ordinal).OrderBy(x=>x,StringComparer.Ordinal);foreach(var name in names){var a=before.Components.FirstOrDefault(x=>x.Name==name);var b=after.Components.FirstOrDefault(x=>x.Name==name);var keys=(a?.Values.Keys??[]).Union(b?.Values.Keys??[],StringComparer.Ordinal).OrderBy(x=>x,StringComparer.Ordinal);foreach(var key in keys){string?av=null;string?bv=null;a?.Values.TryGetValue(key,out av);b?.Values.TryGetValue(key,out bv);var kind=av is null?SnapshotChangeKind.Added:bv is null?SnapshotChangeKind.Removed:av==bv?SnapshotChangeKind.Unchanged:SnapshotChangeKind.Changed;if(kind==SnapshotChangeKind.Unchanged)continue;var risk=Risk(name,key,av,bv);changes.Add(new(name,key,kind,av,bv,risk,$"{name}.{key} was {kind.ToString().ToLowerInvariant()}; this is a structured difference, not a diagnosis."));}}var highlights=changes.Where(x=>x.Risk!="None").Select(x=>$"{x.Risk}: {x.Component}.{x.Key}").ToArray();return new(Guid.NewGuid(),before.Id,after.Id,time.GetUtcNow(),DiffVersion,changes,highlights);}
 public async Task<SystemSnapshotDiff>CompareAndSaveAsync(Guid beforeId,Guid afterId,CancellationToken token){var a=await repository.GetAsync(beforeId,token)??throw new DigitalTwinException("WAID-TWIN-MISSING","The earlier snapshot is unavailable.","Choose another snapshot.");var b=await repository.GetAsync(afterId,token)??throw new DigitalTwinException("WAID-TWIN-MISSING","The later snapshot is unavailable.","Choose another snapshot.");var diff=Compare(a,b);await repository.SaveDiffAsync(diff,token);return diff;}
 public void Verify(DigitalTwinSnapshot x){if(x.SchemaVersion!=SchemaVersion)throw new DigitalTwinException("WAID-TWIN-VERSION","The snapshot version is unsupported.","Use a compatible WAID version.");if(!CryptographicOperations.FixedTimeEquals(Convert.FromHexString(x.IntegritySha256),Convert.FromHexString(Hash(Canonical(x.Components)))))throw new DigitalTwinException("WAID-TWIN-INTEGRITY","Snapshot integrity verification failed.","Do not use this snapshot for comparison.");}
 private static string Canonical(IEnumerable<SystemSnapshotComponent>x)=>JsonSerializer.Serialize(x.OrderBy(c=>c.Name,StringComparer.Ordinal).Select(c=>new{c.Name,c.SerializerVersion,c.State,Values=c.Values.OrderBy(v=>v.Key,StringComparer.Ordinal)}));private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));private static byte[]Compress(byte[]value){using var output=new MemoryStream();using(var gzip=new GZipStream(output,CompressionLevel.SmallestSize,true))gzip.Write(value);return output.ToArray();}private static string Redact(string value){var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);return string.IsNullOrWhiteSpace(profile)?value:value.Replace(profile,"%USERPROFILE%",StringComparison.OrdinalIgnoreCase);}private static string Risk(string component,string key,string?before,string?after){var text=$"{component} {key}";if(text.Contains("security",StringComparison.OrdinalIgnoreCase)||text.Contains("defender",StringComparison.OrdinalIgnoreCase))return"High";if(text.Contains("driver",StringComparison.OrdinalIgnoreCase)||text.Contains("storage",StringComparison.OrdinalIgnoreCase)||text.Contains("update",StringComparison.OrdinalIgnoreCase))return"Review";return"None";}}
