namespace WAID.Application.Services;
public enum PerformanceMetricKind{CpuUtilization,MemoryUtilization,DiskFreeSpace,NetworkThroughput,Temperature,BatteryCharge,ResponsivenessLatency}
public enum MetricQuality{Measured,Estimated,Unavailable,Gap}
public enum MetricResolution{Raw,Hourly,Daily,Weekly}
public sealed record PerformanceMetricSample(Guid Id,PerformanceMetricKind Kind,DateTimeOffset CapturedAtUtc,double? Value,string Unit,MetricQuality Quality,string Source,string? Detail=null){public PerformanceMetricSample Validate(){if(Value is{ }v&&(double.IsNaN(v)||double.IsInfinity(v)))throw new ArgumentOutOfRangeException(nameof(Value));if(Quality==MetricQuality.Unavailable&&Value is not null)throw new ArgumentException("Unavailable samples cannot contain a value.");if(string.IsNullOrWhiteSpace(Unit)||string.IsNullOrWhiteSpace(Source))throw new ArgumentException("Metric unit and source are required.");return this;}}
public sealed record PerformanceMetricRollup(Guid Id,PerformanceMetricKind Kind,MetricResolution Resolution,DateTimeOffset PeriodStartUtc,DateTimeOffset PeriodEndUtc,double? Minimum,double? Maximum,double? Average,double? Percentile95,int SampleCount,double CoveragePercent,string Unit,MetricQuality Quality,string AggregationVersion);
public sealed record SustainedMetricChange(PerformanceMetricKind Kind,double BaselineAverage,double RecentAverage,double PercentChange,bool Sustained,string Explanation);
public sealed record PeriodComparison(PerformanceMetricKind Kind,DateTimeOffset FirstStartUtc,DateTimeOffset FirstEndUtc,double? FirstAverage,DateTimeOffset SecondStartUtc,DateTimeOffset SecondEndUtc,double? SecondAverage,double? PercentChange,string Summary);
public sealed record PerformanceRetentionJob(Guid Id,DateTimeOffset ExecutedAtUtc,DateTimeOffset RawRetainAfterUtc,DateTimeOffset RollupRetainAfterUtc,int DeletedSamples,int DeletedRollups,string PolicyVersion);
public sealed record PerformanceHistoryQuery(PerformanceMetricKind Kind,DateTimeOffset FromUtc,DateTimeOffset ToUtc,MetricResolution Resolution,int MaximumPoints=500){public PerformanceHistoryQuery Validate(){if(FromUtc>ToUtc)throw new ArgumentException("Start must not follow end.");if(MaximumPoints is<10 or>2000)throw new ArgumentOutOfRangeException(nameof(MaximumPoints));return this;}}
public sealed record PerformanceHistoryResult(PerformanceHistoryQuery Query,IReadOnlyList<PerformanceMetricRollup> Points,IReadOnlyList<SustainedMetricChange> Changes,string AccessibleSummary,long StorageGeneration);
public interface IPerformanceMetricCollector{Task<IReadOnlyList<PerformanceMetricSample>>CollectAsync(CancellationToken token);}
public interface IPerformanceHistoryRepository{long Generation{get;}Task SaveSamplesAsync(IReadOnlyList<PerformanceMetricSample>samples,CancellationToken token);Task ReplaceRollupsAsync(PerformanceMetricKind kind,MetricResolution resolution,DateTimeOffset fromUtc,IReadOnlyList<PerformanceMetricRollup>rollups,CancellationToken token);Task<IReadOnlyList<PerformanceMetricSample>>ReadSamplesAsync(PerformanceMetricKind kind,DateTimeOffset fromUtc,DateTimeOffset toUtc,CancellationToken token);Task<IReadOnlyList<PerformanceMetricRollup>>ReadRollupsAsync(PerformanceHistoryQuery query,CancellationToken token);Task<PerformanceRetentionJob>ApplyRetentionAsync(DateTimeOffset rawRetainAfterUtc,DateTimeOffset rollupRetainAfterUtc,CancellationToken token);}
public sealed class PerformanceHistoryException(string code,string message,string recoveryAction,Exception?inner=null):InvalidOperationException(message,inner){public string Code{get;}=code;public string RecoveryAction{get;}=recoveryAction;}
public sealed class PerformanceAggregationEngine
{public const string Version="performance-rollup-v1";public IReadOnlyList<PerformanceMetricRollup>Aggregate(PerformanceMetricKind kind,IReadOnlyList<PerformanceMetricSample>samples,MetricResolution resolution){if(resolution==MetricResolution.Raw)throw new ArgumentException("Raw samples are not rollups.");var span=resolution switch{MetricResolution.Hourly=>TimeSpan.FromHours(1),MetricResolution.Daily=>TimeSpan.FromDays(1),MetricResolution.Weekly=>TimeSpan.FromDays(7),_=>throw new ArgumentOutOfRangeException(nameof(resolution))};return samples.OrderBy(x=>x.CapturedAtUtc).GroupBy(x=>Bucket(x.CapturedAtUtc,span)).Select(g=>Build(kind,resolution,g.Key,g.Key+span,g.ToArray())).ToArray();}
 public IReadOnlyList<PerformanceMetricRollup>Downsample(IReadOnlyList<PerformanceMetricRollup>points,int maximum){if(maximum<1)throw new ArgumentOutOfRangeException(nameof(maximum));if(points.Count<=maximum)return points;var result=new List<PerformanceMetricRollup>(maximum);var size=(double)points.Count/maximum;for(var i=0;i<maximum;i++){var start=(int)Math.Floor(i*size);var end=Math.Min(points.Count,(int)Math.Ceiling((i+1)*size));var selected=points[start];var selectedRange=Range(selected);for(var index=start+1;index<end;index++){var candidate=points[index];var range=Range(candidate);if(range>selectedRange||(range==selectedRange&&Maximum(candidate)>Maximum(selected))||(range==selectedRange&&Maximum(candidate)==Maximum(selected)&&candidate.PeriodStartUtc<selected.PeriodStartUtc)){selected=candidate;selectedRange=range;}}result.Add(selected);}result.Sort(static(a,b)=>a.PeriodStartUtc.CompareTo(b.PeriodStartUtc));return result;static double Range(PerformanceMetricRollup point)=>(point.Maximum??double.MinValue)-(point.Minimum??double.MaxValue);static double Maximum(PerformanceMetricRollup point)=>point.Maximum??double.MinValue;}
 public IReadOnlyList<SustainedMetricChange>DetectChanges(PerformanceMetricKind kind,IReadOnlyList<PerformanceMetricRollup>points){var valid=points.Where(x=>x.Average is not null).ToArray();if(valid.Length<6)return[];var half=valid.Length/2;var baseline=valid.Take(half).Average(x=>x.Average!.Value);var recent=valid.Skip(half).Average(x=>x.Average!.Value);var percent=Math.Abs(baseline)<.001?0:(recent-baseline)/Math.Abs(baseline)*100;var sustained=Math.Abs(percent)>=15&&valid.Skip(half).Count(x=>Math.Sign(x.Average!.Value-baseline)==Math.Sign(percent))>=Math.Ceiling((double)(valid.Length-half)*.7);return[new(kind,baseline,recent,percent,sustained,sustained?$"A sustained {percent:+0.0;-0.0}% change is visible across the recent period.":"No sustained 15% change is supported by the available rollups.")];}
 private static DateTimeOffset Bucket(DateTimeOffset value,TimeSpan span){var utc=value.ToUniversalTime();return new DateTimeOffset(utc.Ticks-utc.Ticks%span.Ticks,TimeSpan.Zero);}private static PerformanceMetricRollup Build(PerformanceMetricKind kind,MetricResolution resolution,DateTimeOffset start,DateTimeOffset end,PerformanceMetricSample[]samples){var values=samples.Where(x=>x.Value is not null).Select(x=>x.Value!.Value).OrderBy(x=>x).ToArray();var coverage=samples.Length==0?0:values.Length*100d/samples.Length;var quality=values.Length==0?MetricQuality.Unavailable:samples.Any(x=>x.Quality==MetricQuality.Estimated)?MetricQuality.Estimated:MetricQuality.Measured;var p95=values.Length==0?(double?)null:values[(int)Math.Clamp(Math.Ceiling(values.Length*.95)-1,0,values.Length-1)];return new(Guid.NewGuid(),kind,resolution,start,end,values.Length==0?null:values[0],values.Length==0?null:values[^1],values.Length==0?null:values.Average(),p95,values.Length,coverage,samples.FirstOrDefault()?.Unit??"unknown",quality,Version);}}
public sealed class PerformanceHistoryService(IPerformanceMetricCollector collector,IPerformanceHistoryRepository repository,PerformanceAggregationEngine aggregation,TimeProvider time,IPerformanceTelemetry? performance=null)
{private readonly System.Collections.Concurrent.ConcurrentDictionary<string,PerformanceHistoryResult>_cache=[];public async Task<IReadOnlyList<PerformanceMetricSample>>CollectAsync(CancellationToken token){var samples=(await collector.CollectAsync(token)).Select(x=>x.Validate()).ToArray();await repository.SaveSamplesAsync(samples,token);_cache.Clear();return samples;}public async Task BuildRollupsAsync(DateTimeOffset fromUtc,CancellationToken token){foreach(var kind in Enum.GetValues<PerformanceMetricKind>()){var samples=await repository.ReadSamplesAsync(kind,fromUtc,time.GetUtcNow(),token);foreach(var resolution in new[]{MetricResolution.Hourly,MetricResolution.Daily,MetricResolution.Weekly})await repository.ReplaceRollupsAsync(kind,resolution,fromUtc,aggregation.Aggregate(kind,samples,resolution),token);}_cache.Clear();}
 public async Task<PerformanceHistoryResult>QueryAsync(PerformanceHistoryQuery query,CancellationToken token){query.Validate();var key=$"{query}|{repository.Generation}";if(_cache.TryGetValue(key,out var cached))return cached;using var measurement=performance?.Measure("database.performance-history",PerformanceArea.Database);var stored=await repository.ReadRollupsAsync(query,token);var points=aggregation.Downsample(stored,query.MaximumPoints);var changes=aggregation.DetectChanges(query.Kind,points);var missing=points.Count(x=>x.Quality is MetricQuality.Unavailable or MetricQuality.Gap);var summary=points.Count==0?$"No {query.Kind} history is available for this period.":$"{query.Kind}: {points.Count} displayed points, {missing} unavailable or gap points; range {points.Where(x=>x.Minimum is not null).Select(x=>x.Minimum!.Value).DefaultIfEmpty().Min():F1} to {points.Where(x=>x.Maximum is not null).Select(x=>x.Maximum!.Value).DefaultIfEmpty().Max():F1} {points[0].Unit}.";var result=new PerformanceHistoryResult(query,points,changes,summary,repository.Generation);_cache[key]=result;return result;}
 public async Task<PeriodComparison>CompareAsync(PerformanceMetricKind kind,DateTimeOffset aStart,DateTimeOffset aEnd,DateTimeOffset bStart,DateTimeOffset bEnd,CancellationToken token){var a=await repository.ReadSamplesAsync(kind,aStart,aEnd,token);var b=await repository.ReadSamplesAsync(kind,bStart,bEnd,token);double?Avg(IReadOnlyList<PerformanceMetricSample>x){var v=x.Where(y=>y.Value is not null).Select(y=>y.Value!.Value).ToArray();return v.Length==0?null:v.Average();}var av=Avg(a);var bv=Avg(b);var change=av is null||bv is null||Math.Abs(av.Value)<.001?null:(bv-av)/Math.Abs(av.Value)*100;return new(kind,aStart,aEnd,av,bStart,bEnd,bv,change,change is null?"Comparison unavailable because one period has insufficient measured data.":$"The second period changed {change:+0.0;-0.0}% from the first; this is descriptive, not causal.");}}
