using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
namespace WAID.Application.Services;
public enum ReliabilityEventKind{Crash,Update,DriverChange,Repair,Alert,HealthShift,ReliabilityEvent,RetentionGap}
public enum ReliabilitySeverity{Information,Advisory,Warning,Critical,Unavailable}
public sealed record TimelineSourceReference(string SourceType,string SourceId,string EvidenceReference);
public sealed record NormalizedTimelineRecord(ReliabilityEventKind Kind,DateTimeOffset OccurredAtUtc,string Title,string Summary,ReliabilitySeverity Severity,string SubjectKey,TimelineSourceReference Provenance,IReadOnlyDictionary<string,string> Evidence);
public sealed record ReliabilityTimelineEvent(string Id,ReliabilityEventKind Kind,DateTimeOffset OccurredAtUtc,string Title,string Summary,ReliabilitySeverity Severity,string SubjectKey,TimelineSourceReference Provenance,IReadOnlyDictionary<string,string> Evidence,string ProjectionVersion);
public sealed record ReliabilityIncident(string Id,DateTimeOffset StartedAtUtc,DateTimeOffset EndedAtUtc,string Title,ReliabilitySeverity Severity,IReadOnlyList<string> EventIds,string GroupingVersion,string CorrelationLabel);
public sealed record ReliabilityTimelineProjection(string ProjectionVersion,string GroupingVersion,DateTimeOffset GeneratedAtUtc,IReadOnlyList<ReliabilityTimelineEvent> Events,IReadOnlyList<ReliabilityIncident> Incidents);
public sealed record TimelineQuery(int Page,int PageSize,DateTimeOffset? FromUtc=null,DateTimeOffset? ToUtc=null,ReliabilityEventKind? Kind=null,string? Search=null){public TimelineQuery Validate(){if(Page<0||PageSize is<1 or>200)throw new ArgumentOutOfRangeException(nameof(PageSize));if(FromUtc>ToUtc)throw new ArgumentException("The start date must not be after the end date.");if(Search?.Length>100)throw new ArgumentOutOfRangeException(nameof(Search));return this;}}
public sealed record TimelinePage(IReadOnlyList<ReliabilityTimelineEvent> Items,int Page,int PageSize,int TotalCount);
public interface IReliabilityTimelineSource{Task<IReadOnlyList<NormalizedTimelineRecord>> ReadAsync(DateTimeOffset? fromUtc,DateTimeOffset? toUtc,int maximumRecords,CancellationToken token);}
public interface IReliabilityTimelineRepository{Task ReplaceAsync(ReliabilityTimelineProjection projection,CancellationToken token);Task<TimelinePage> QueryAsync(TimelineQuery query,CancellationToken token);Task<ReliabilityIncident?> GetIncidentAsync(string id,CancellationToken token);Task<IReadOnlyList<ReliabilityIncident>> GetRecentIncidentsAsync(int count,CancellationToken token);}
public sealed class ReliabilityTimelineException(string code,string message,string recoveryAction,Exception? inner=null):InvalidOperationException(message,inner){public string Code{get;}=code;public string RecoveryAction{get;}=recoveryAction;}
public sealed class ReliabilityTimelineProjector(IEnumerable<IReliabilityTimelineSource> sources,IReliabilityTimelineRepository repository,TimeProvider time)
{
 public const string ProjectionVersion="timeline-v1";public const string GroupingVersion="temporal-subject-v1";private readonly IReadOnlyList<IReliabilityTimelineSource>_sources=sources.ToArray();
 public async Task<ReliabilityTimelineProjection> RebuildAsync(DateTimeOffset? fromUtc,DateTimeOffset? toUtc,CancellationToken token){var records=new List<NormalizedTimelineRecord>();foreach(var source in _sources)records.AddRange(await source.ReadAsync(fromUtc,toUtc,100_000,token));var events=records.Select(Normalize).GroupBy(x=>x.Id,StringComparer.Ordinal).Select(g=>g.OrderBy(x=>x.Provenance.SourceType,StringComparer.Ordinal).First()).OrderBy(x=>x.OccurredAtUtc).ThenBy(x=>x.Id,StringComparer.Ordinal).ToArray();var incidents=Group(events);var projection=new ReliabilityTimelineProjection(ProjectionVersion,GroupingVersion,time.GetUtcNow(),events,incidents);await repository.ReplaceAsync(projection,token);return projection;}
 private static ReliabilityTimelineEvent Normalize(NormalizedTimelineRecord x){var utc=x.OccurredAtUtc.ToUniversalTime();var id=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{x.Provenance.SourceType}|{x.Provenance.SourceId}|{x.Kind}|{utc:O}")))[..24];return new(id,x.Kind,utc,Clean(x.Title),Clean(x.Summary),x.Severity,Clean(x.SubjectKey),x.Provenance,x.Evidence,ProjectionVersion);}
 private static IReadOnlyList<ReliabilityIncident> Group(IReadOnlyList<ReliabilityTimelineEvent> events){var groups=new List<List<ReliabilityTimelineEvent>>();foreach(var item in events.Where(x=>x.Kind!=ReliabilityEventKind.RetentionGap)){var found=groups.LastOrDefault(g=>g[^1].OccurredAtUtc>=item.OccurredAtUtc-TimeSpan.FromMinutes(30)&&(g.Any(x=>x.SubjectKey.Equals(item.SubjectKey,StringComparison.OrdinalIgnoreCase))||g.Any(x=>Related(x.Kind,item.Kind))));if(found is null)groups.Add([item]);else found.Add(item);}return groups.Where(g=>g.Count>1).Select(g=>{var ids=g.Select(x=>x.Id).OrderBy(x=>x,StringComparer.Ordinal).ToArray();var id=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(string.Join('|',ids))))[..24];return new ReliabilityIncident(id,g.Min(x=>x.OccurredAtUtc),g.Max(x=>x.OccurredAtUtc),$"{g.Count} possibly related reliability events",g.Max(x=>x.Severity),ids,GroupingVersion,"Possible association based on time and subject; not proof of causation.");}).OrderBy(x=>x.StartedAtUtc).ThenBy(x=>x.Id,StringComparer.Ordinal).ToArray();}
 private static bool Related(ReliabilityEventKind a,ReliabilityEventKind b)=>(a,b) is(ReliabilityEventKind.Update,ReliabilityEventKind.Crash)or(ReliabilityEventKind.DriverChange,ReliabilityEventKind.Crash)or(ReliabilityEventKind.Alert,ReliabilityEventKind.Crash)or(ReliabilityEventKind.Repair,ReliabilityEventKind.HealthShift)or(ReliabilityEventKind.Crash,ReliabilityEventKind.Update)or(ReliabilityEventKind.Crash,ReliabilityEventKind.DriverChange)or(ReliabilityEventKind.Crash,ReliabilityEventKind.Alert)or(ReliabilityEventKind.HealthShift,ReliabilityEventKind.Repair);
 private static string Clean(string value){if(string.IsNullOrWhiteSpace(value))return "Unavailable";var clean=value.Replace('\r',' ').Replace('\n',' ').Trim();return clean.Length<=500?clean:clean[..500];}
}
public sealed class ReliabilityTimelineExporter
{
 private static readonly Regex Secret=new("(?i)(password|token|secret|product.?key|authorization|cookie)",RegexOptions.Compiled,TimeSpan.FromMilliseconds(100));
 private static string Redact(string value){var profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);return string.IsNullOrWhiteSpace(profile)?value:value.Replace(profile,"%USERPROFILE%",StringComparison.OrdinalIgnoreCase);}
 public async Task<string> ExportJsonAsync(TimelinePage page,string directory,CancellationToken token){Directory.CreateDirectory(directory);var path=Path.Combine(directory,$"waid-reliability-timeline-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}.json");var payload=new{schemaVersion="1.0",exportedAtUtc=DateTimeOffset.UtcNow,correlationNotice="Incident groupings are possible associations, not proof of causation.",page.TotalCount,events=page.Items.Select(x=>new{x.Id,x.Kind,x.OccurredAtUtc,Title=Redact(x.Title),Summary=Redact(x.Summary),x.Severity,x.SubjectKey,x.Provenance,Evidence=x.Evidence.Where(item=>!Secret.IsMatch(item.Key)&&!Secret.IsMatch(item.Value)).ToDictionary(item=>item.Key,item=>Redact(item.Value))})};await File.WriteAllTextAsync(path,JsonSerializer.Serialize(payload,new JsonSerializerOptions(JsonSerializerDefaults.Web){WriteIndented=true}),token);return path;}
}
