using System.Text.Json;
using WAID.Application.Services;

namespace WAID.Infrastructure.Persistence;

public sealed class SqliteAlertRepository(WaidDatabase database):IAlertRepository
{
    private static readonly JsonSerializerOptions Json=new(JsonSerializerDefaults.Web);
    public async Task<AlertNotification?> GetActiveByKeyAsync(string key,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT alert_json FROM alerts WHERE json_extract(alert_json,'$.deduplicationKey')=$key AND resolved_utc IS NULL ORDER BY created_utc DESC LIMIT 1";q.Parameters.AddWithValue("$key",key);var json=await q.ExecuteScalarAsync(token).ConfigureAwait(false)as string;return json is null?null:Decode<AlertNotification>(json);}
    public async Task SaveAsync(AlertNotification alert,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO alerts(id,created_utc,resolved_utc,alert_json)VALUES($id,$created,$resolved,$json) ON CONFLICT(id) DO UPDATE SET resolved_utc=$resolved,alert_json=$json";q.Parameters.AddWithValue("$id",alert.Id.ToString());q.Parameters.AddWithValue("$created",alert.CreatedAtUtc.ToString("O"));q.Parameters.AddWithValue("$resolved",alert.State==AlertState.Resolved?alert.LastObservedAtUtc.ToString("O"):DBNull.Value);q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(alert,Json));await q.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
    public async Task SaveDeliveryAsync(AlertDelivery delivery,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO alert_deliveries(id,alert_id,attempted_utc,status,delivery_json)VALUES($id,$alert,$time,$status,$json)";q.Parameters.AddWithValue("$id",delivery.Id.ToString());q.Parameters.AddWithValue("$alert",delivery.AlertId.ToString());q.Parameters.AddWithValue("$time",delivery.AttemptedAtUtc.ToString("O"));q.Parameters.AddWithValue("$status",(int)delivery.Status);q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(delivery,Json));await q.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
    public async Task<IReadOnlyList<AlertNotification>> QueryAsync(AlertQuery query,CancellationToken token){if(query.MaximumRecords is<1 or>500)throw new ArgumentOutOfRangeException(nameof(query));var items=new List<AlertNotification>();await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT alert_json FROM alerts ORDER BY created_utc DESC LIMIT $count";q.Parameters.AddWithValue("$count",query.MaximumRecords);await using var r=await q.ExecuteReaderAsync(token).ConfigureAwait(false);while(await r.ReadAsync(token).ConfigureAwait(false))items.Add(Decode<AlertNotification>(r.GetString(0)));return items.Where(x=>(query.Category is null||x.Category==query.Category)&&(query.MinimumSeverity is null||x.Severity>=query.MinimumSeverity)&&(query.State is null||x.State==query.State)&&(string.IsNullOrWhiteSpace(query.Search)||x.Title.Contains(query.Search,StringComparison.OrdinalIgnoreCase)||x.Message.Contains(query.Search,StringComparison.OrdinalIgnoreCase))).ToArray();}
    public async Task<AlertSettings> GetSettingsAsync(CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT settings_json FROM alert_settings WHERE id=1";var json=await q.ExecuteScalarAsync(token).ConfigureAwait(false)as string;return json is null?AlertSettings.Default:Decode<AlertSettings>(json).Validate();}
    public async Task SaveSettingsAsync(AlertSettings settings,CancellationToken token){settings.Validate();await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO alert_settings(id,settings_json,updated_utc)VALUES(1,$json,$time) ON CONFLICT(id) DO UPDATE SET settings_json=$json,updated_utc=$time";q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(settings,Json));q.Parameters.AddWithValue("$time",DateTimeOffset.UtcNow.ToString("O"));await q.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
    private static T Decode<T>(string json)=>JsonSerializer.Deserialize<T>(json,Json)??throw new InvalidDataException("Stored alert data is invalid.");
}
