using System.Text.Json;
using WAID.Application.Abstractions;

namespace WAID.Infrastructure.Persistence;

public sealed class SqliteRecoveryArtifactRepository(WaidDatabase database) : IRecoveryArtifactRepository
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public async Task SaveAsync(RecoveryArtifactRecord artifact, CancellationToken token) { await using var c = database.OpenConnection(); await using var q = c.CreateCommand(); q.CommandText = "INSERT INTO recovery_artifacts(id,transaction_id,created_utc,expires_utc,state,artifact_json) VALUES($id,$transaction,$created,$expires,$state,$json) ON CONFLICT(id) DO UPDATE SET expires_utc=$expires,state=$state,artifact_json=$json"; q.Parameters.AddWithValue("$id", artifact.Id.ToString()); q.Parameters.AddWithValue("$transaction", artifact.TransactionId.ToString()); q.Parameters.AddWithValue("$created", artifact.CreatedAtUtc.ToString("O")); q.Parameters.AddWithValue("$expires", artifact.ExpiresAtUtc.ToString("O")); q.Parameters.AddWithValue("$state", (int)artifact.State); q.Parameters.AddWithValue("$json", JsonSerializer.Serialize(artifact, Json)); await q.ExecuteNonQueryAsync(token).ConfigureAwait(false); }
    public async Task<RecoveryArtifactRecord?> GetByTransactionAsync(Guid transactionId, CancellationToken token) { await using var c = database.OpenConnection(); await using var q = c.CreateCommand(); q.CommandText = "SELECT artifact_json FROM recovery_artifacts WHERE transaction_id=$transaction ORDER BY created_utc DESC LIMIT 1"; q.Parameters.AddWithValue("$transaction", transactionId.ToString()); var value = await q.ExecuteScalarAsync(token).ConfigureAwait(false) as string; return value is null ? null : Decode(value); }
    public async Task<IReadOnlyList<RecoveryArtifactRecord>> GetRecentAsync(int count, CancellationToken token) { if (count is < 1 or > 500) throw new ArgumentOutOfRangeException(nameof(count)); await using var c = database.OpenConnection(); await using var q = c.CreateCommand(); q.CommandText = "SELECT artifact_json FROM recovery_artifacts ORDER BY created_utc DESC,id DESC LIMIT $count"; q.Parameters.AddWithValue("$count", count); return await ReadAsync(q, token).ConfigureAwait(false); }
    public async Task<IReadOnlyList<RecoveryArtifactRecord>> GetExpiredAsync(DateTimeOffset nowUtc, int count, CancellationToken token) { if (count is < 1 or > 500) throw new ArgumentOutOfRangeException(nameof(count)); await using var c = database.OpenConnection(); await using var q = c.CreateCommand(); q.CommandText = "SELECT artifact_json FROM recovery_artifacts WHERE expires_utc<=$now AND state IN ($valid,$invalid,$failed) ORDER BY expires_utc LIMIT $count"; q.Parameters.AddWithValue("$now", nowUtc.ToString("O")); q.Parameters.AddWithValue("$valid", (int)RecoveryArtifactState.Valid); q.Parameters.AddWithValue("$invalid", (int)RecoveryArtifactState.Invalid); q.Parameters.AddWithValue("$failed", (int)RecoveryArtifactState.RollbackFailed); q.Parameters.AddWithValue("$count", count); return await ReadAsync(q, token).ConfigureAwait(false); }
    private static async Task<IReadOnlyList<RecoveryArtifactRecord>> ReadAsync(Microsoft.Data.Sqlite.SqliteCommand q, CancellationToken token) { var result = new List<RecoveryArtifactRecord>(); await using var reader = await q.ExecuteReaderAsync(token).ConfigureAwait(false); while (await reader.ReadAsync(token).ConfigureAwait(false)) result.Add(Decode(reader.GetString(0))); return result; }
    private static RecoveryArtifactRecord Decode(string value) => JsonSerializer.Deserialize<RecoveryArtifactRecord>(value, Json) ?? throw new InvalidDataException("Stored recovery artifact is invalid.");
}