using System.Text.Json;
using Microsoft.Data.Sqlite;
using WAID.EventAnalysis;
namespace WAID.Infrastructure.Persistence;
public sealed class SqliteEvidenceGraphRepository(WaidDatabase database):IEvidenceGraphRepository
{
 private static readonly JsonSerializerOptions Options=new(JsonSerializerDefaults.Web);
 public async Task SaveAsync(EvidenceGraph graph,CancellationToken token){ArgumentNullException.ThrowIfNull(graph);await using var c=database.OpenConnection();await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(token);await using(var run=c.CreateCommand()){run.Transaction=tx;run.CommandText="INSERT INTO evidence_graph_runs(id,generated_utc,schema_version,strategy_version,retain_until_utc)VALUES($id,$time,$schema,$strategy,$retain)";run.Parameters.AddWithValue("$id",graph.Id.ToString());run.Parameters.AddWithValue("$time",graph.GeneratedAtUtc.ToString("O"));run.Parameters.AddWithValue("$schema",graph.SchemaVersion);run.Parameters.AddWithValue("$strategy",graph.StrategyVersion);run.Parameters.AddWithValue("$retain",graph.RetainUntilUtc.ToString("O"));await run.ExecuteNonQueryAsync(token);}foreach(var n in graph.Nodes){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO evidence_graph_nodes(run_id,node_id,observed_utc,domain,code,node_json)VALUES($run,$id,$time,$domain,$code,$json)";q.Parameters.AddWithValue("$run",graph.Id.ToString());q.Parameters.AddWithValue("$id",n.Id);q.Parameters.AddWithValue("$time",n.LastObservedAtUtc.ToString("O"));q.Parameters.AddWithValue("$domain",n.Domain.ToString());q.Parameters.AddWithValue("$code",n.Code);q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(n,Options));await q.ExecuteNonQueryAsync(token);}foreach(var e in graph.Relationships){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO evidence_graph_edges(run_id,edge_id,from_node_id,to_node_id,kind,confidence,edge_json)VALUES($run,$id,$from,$to,$kind,$confidence,$json)";q.Parameters.AddWithValue("$run",graph.Id.ToString());q.Parameters.AddWithValue("$id",e.Id);q.Parameters.AddWithValue("$from",e.FromNodeId);q.Parameters.AddWithValue("$to",e.ToNodeId);q.Parameters.AddWithValue("$kind",e.Kind.ToString());q.Parameters.AddWithValue("$confidence",e.Confidence);q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(e,Options));await q.ExecuteNonQueryAsync(token);}await using(var purge=c.CreateCommand()){purge.Transaction=tx;purge.CommandText="DELETE FROM evidence_graph_runs WHERE retain_until_utc < $now";purge.Parameters.AddWithValue("$now",DateTimeOffset.UtcNow.ToString("O"));await purge.ExecuteNonQueryAsync(token);}await tx.CommitAsync(token);}
 public async Task<EvidenceGraph?> GetLatestAsync(CancellationToken token){await using var c=database.OpenConnection();await using var run=c.CreateCommand();run.CommandText="SELECT id,generated_utc,schema_version,strategy_version,retain_until_utc FROM evidence_graph_runs ORDER BY generated_utc DESC LIMIT 1";await using var r=await run.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))return null;var id=Guid.Parse(r.GetString(0));var generated=DateTimeOffset.Parse(r.GetString(1));var schema=r.GetString(2);var strategy=r.GetString(3);var retain=DateTimeOffset.Parse(r.GetString(4));await r.DisposeAsync();var nodes=new List<EvidenceNode>();await using(var q=c.CreateCommand()){q.CommandText="SELECT node_json FROM evidence_graph_nodes WHERE run_id=$id ORDER BY observed_utc,node_id";q.Parameters.AddWithValue("$id",id.ToString());await using var rows=await q.ExecuteReaderAsync(token);while(await rows.ReadAsync(token))nodes.Add(JsonSerializer.Deserialize<EvidenceNode>(rows.GetString(0),Options)??throw new InvalidOperationException("Evidence node is invalid."));}var edges=new List<EvidenceRelationship>();await using(var q=c.CreateCommand()){q.CommandText="SELECT edge_json FROM evidence_graph_edges WHERE run_id=$id ORDER BY edge_id";q.Parameters.AddWithValue("$id",id.ToString());await using var rows=await q.ExecuteReaderAsync(token);while(await rows.ReadAsync(token))edges.Add(JsonSerializer.Deserialize<EvidenceRelationship>(rows.GetString(0),Options)??throw new InvalidOperationException("Evidence relationship is invalid."));}return new(id,generated,schema,strategy,nodes,edges,retain);}
}