using System.Text.Json;
using WAID.Application.Services;
namespace WAID.Infrastructure.Persistence;
public sealed class SqliteLiveMonitoringRepository(WaidDatabase database):ILiveMonitoringRepository
{
    private static readonly JsonSerializerOptions Options=new(JsonSerializerDefaults.Web);
    public async Task RecoverInterruptedSessionsAsync(DateTimeOffset now,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="UPDATE monitoring_sessions SET ended_utc=$now,state=$state,stop_reason='Application restarted before the session closed.' WHERE ended_utc IS NULL";q.Parameters.AddWithValue("$now",now.ToString("O"));q.Parameters.AddWithValue("$state",(int)LiveMonitoringState.Disabled);await q.ExecuteNonQueryAsync(token);}
    public async Task SaveSessionAsync(LiveMonitoringSession session,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO monitoring_sessions(id,started_utc,ended_utc,state,options_json,stop_reason)VALUES($id,$start,$end,$state,$options,$reason) ON CONFLICT(id) DO UPDATE SET ended_utc=$end,state=$state,stop_reason=$reason";q.Parameters.AddWithValue("$id",session.Id.ToString());q.Parameters.AddWithValue("$start",session.StartedAtUtc.ToString("O"));q.Parameters.AddWithValue("$end",session.EndedAtUtc?.ToString("O") is { } end?end:DBNull.Value);q.Parameters.AddWithValue("$state",(int)session.State);q.Parameters.AddWithValue("$options",JsonSerializer.Serialize(session.Options,Options));q.Parameters.AddWithValue("$reason",session.StopReason);await q.ExecuteNonQueryAsync(token);}
    public async Task SaveCycleAsync(IReadOnlyList<LiveSignalSample> samples,IReadOnlyList<MonitoringGap> gaps,IReadOnlyList<CollectorFailure> failures,CancellationToken token){await using var c=database.OpenConnection();await using var tx=await c.BeginTransactionAsync(token);try{foreach(var x in samples)await Insert(c,(Microsoft.Data.Sqlite.SqliteTransaction)tx,"INSERT INTO monitoring_samples(id,session_id,signal_id,captured_utc,sample_json)VALUES($id,$session,$key,$time,$json)",x.Id,x.SessionId,x.SignalId,x.CapturedAtUtc,JsonSerializer.Serialize(x,Options),token);foreach(var x in gaps)await Insert(c,(Microsoft.Data.Sqlite.SqliteTransaction)tx,"INSERT INTO monitoring_gaps(id,session_id,signal_id,captured_utc,sample_json)VALUES($id,$session,$key,$time,$json)",x.Id,x.SessionId,x.Reason.ToString(),x.EndedAtUtc,JsonSerializer.Serialize(x,Options),token);foreach(var x in failures)await Insert(c,(Microsoft.Data.Sqlite.SqliteTransaction)tx,"INSERT INTO monitoring_collector_failures(id,session_id,signal_id,captured_utc,sample_json)VALUES($id,$session,$key,$time,$json)",x.Id,x.SessionId,x.CollectorId,x.OccurredAtUtc,JsonSerializer.Serialize(x,Options),token);await tx.CommitAsync(token);}catch{await tx.RollbackAsync(CancellationToken.None);throw;}}
    public async Task<MonitoringRetentionState> ApplyRetentionAsync(DateTimeOffset retainAfterUtc,int maximumSamples,CancellationToken token){await using var c=database.OpenConnection();var deleted=0;foreach(var table in new[]{"monitoring_samples","monitoring_gaps","monitoring_collector_failures"}){await using var q=c.CreateCommand();q.CommandText=$"DELETE FROM {table} WHERE captured_utc<$retain";q.Parameters.AddWithValue("$retain",retainAfterUtc.ToString("O"));deleted+=await q.ExecuteNonQueryAsync(token);}await using(var cap=c.CreateCommand()){cap.CommandText="DELETE FROM monitoring_samples WHERE id IN(SELECT id FROM monitoring_samples ORDER BY captured_utc DESC LIMIT -1 OFFSET $maximum)";cap.Parameters.AddWithValue("$maximum",maximumSamples);deleted+=await cap.ExecuteNonQueryAsync(token);}await using var sessions=c.CreateCommand();sessions.CommandText="DELETE FROM monitoring_sessions WHERE ended_utc IS NOT NULL AND ended_utc<$retain AND id NOT IN(SELECT DISTINCT session_id FROM monitoring_samples UNION SELECT DISTINCT session_id FROM monitoring_gaps UNION SELECT DISTINCT session_id FROM monitoring_collector_failures)";sessions.Parameters.AddWithValue("$retain",retainAfterUtc.ToString("O"));var deletedSessions=await sessions.ExecuteNonQueryAsync(token);var state=new MonitoringRetentionState(DateTimeOffset.UtcNow,retainAfterUtc,maximumSamples,deleted,deletedSessions);await using var save=c.CreateCommand();save.CommandText="INSERT INTO monitoring_retention(id,evaluated_utc,state_json)VALUES(1,$time,$json) ON CONFLICT(id) DO UPDATE SET evaluated_utc=$time,state_json=$json";save.Parameters.AddWithValue("$time",state.EvaluatedAtUtc.ToString("O"));save.Parameters.AddWithValue("$json",JsonSerializer.Serialize(state,Options));await save.ExecuteNonQueryAsync(token);return state;}
    public async Task<LiveMonitoringSnapshot?> GetLatestAsync(int sampleCount,CancellationToken token){if(sampleCount is<1 or>1000)throw new ArgumentOutOfRangeException(nameof(sampleCount));await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT id,started_utc,ended_utc,state,options_json,stop_reason FROM monitoring_sessions ORDER BY started_utc DESC LIMIT 1";await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))return null;var id=Guid.Parse(r.GetString(0));var session=new LiveMonitoringSession(id,DateTimeOffset.Parse(r.GetString(1)),r.IsDBNull(2)?null:DateTimeOffset.Parse(r.GetString(2)),(LiveMonitoringState)r.GetInt32(3),JsonSerializer.Deserialize<LiveMonitoringOptions>(r.GetString(4),Options)??LiveMonitoringOptions.Default,r.GetString(5));await r.DisposeAsync();var samples=await Read<LiveSignalSample>(c,"monitoring_samples",id,sampleCount,token);var gaps=await Read<MonitoringGap>(c,"monitoring_gaps",id,sampleCount,token);var failures=await Read<CollectorFailure>(c,"monitoring_collector_failures",id,sampleCount,token);await using var retention=c.CreateCommand();retention.CommandText="SELECT state_json FROM monitoring_retention WHERE id=1";var json=await retention.ExecuteScalarAsync(token)as string;return new(session,samples,gaps,failures,json is null?null:JsonSerializer.Deserialize<MonitoringRetentionState>(json,Options));}
    private static async Task Insert(Microsoft.Data.Sqlite.SqliteConnection c,Microsoft.Data.Sqlite.SqliteTransaction tx,string sql,Guid id,Guid session,string key,DateTimeOffset time,string json,CancellationToken token){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;q.Parameters.AddWithValue("$id",id.ToString());q.Parameters.AddWithValue("$session",session.ToString());q.Parameters.AddWithValue("$key",key);q.Parameters.AddWithValue("$time",time.ToString("O"));q.Parameters.AddWithValue("$json",json);await q.ExecuteNonQueryAsync(token);}
    private static async Task<IReadOnlyList<T>> Read<T>(Microsoft.Data.Sqlite.SqliteConnection c,string table,Guid session,int count,CancellationToken token){var items=new List<T>();await using var q=c.CreateCommand();q.CommandText=$"SELECT sample_json FROM {table} WHERE session_id=$session ORDER BY captured_utc DESC LIMIT $count";q.Parameters.AddWithValue("$session",session.ToString());q.Parameters.AddWithValue("$count",count);await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))items.Add(JsonSerializer.Deserialize<T>(r.GetString(0),Options)??throw new InvalidDataException($"Invalid {table} record."));return items;}
}
