using System.Text.Json;
using WAID.Application.Services;
namespace WAID.Infrastructure.Persistence;
public sealed class SqliteTechnicianWorkspaceRepository(WaidDatabase database,TimeProvider time):ITechnicianWorkspaceRepository
{
 public async Task<TechnicianPreferences> GetPreferencesAsync(CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT preferences_json FROM technician_preferences WHERE id=1";var value=await q.ExecuteScalarAsync(token);return value is string json&&JsonSerializer.Deserialize<TechnicianPreferences>(json) is{}item?item:new(DashboardPresentationProfile.Simple,TechnicianLayout.Compact,"",time.GetUtcNow());}
 public async Task SavePreferencesAsync(TechnicianPreferences value,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO technician_preferences(id,updated_utc,preferences_json)VALUES(1,$time,$json) ON CONFLICT(id) DO UPDATE SET updated_utc=$time,preferences_json=$json";q.Parameters.AddWithValue("$time",value.UpdatedAtUtc.ToString("O"));q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(value));await q.ExecuteNonQueryAsync(token);}
 public async Task<IReadOnlyList<TechnicianCase>> GetCasesAsync(CancellationToken token){var result=new List<TechnicianCase>();await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="SELECT case_json FROM technician_cases ORDER BY updated_utc DESC LIMIT 500";await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token)){var item=JsonSerializer.Deserialize<TechnicianCase>(r.GetString(0));if(item is not null)result.Add(item);}return result;}
 public async Task SaveCaseAsync(TechnicianCase value,CancellationToken token){await using var c=database.OpenConnection();await using var q=c.CreateCommand();q.CommandText="INSERT INTO technician_cases(id,case_id,updated_utc,case_json)VALUES($id,$case,$time,$json) ON CONFLICT(id) DO UPDATE SET case_id=$case,updated_utc=$time,case_json=$json";q.Parameters.AddWithValue("$id",value.Id.ToString());q.Parameters.AddWithValue("$case",value.CaseId);q.Parameters.AddWithValue("$time",value.UpdatedAtUtc.ToString("O"));q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(value));await q.ExecuteNonQueryAsync(token);}
}
