using System.Globalization;
using WAID.Diagnosis;
using WAID.Domain.Diagnostics;
using WAID.EventAnalysis;
using WAID.Health;
using WAID.KnowledgeBase;
namespace WAID.Diagnosis.Tests;
public sealed class ExplainableDiagnosisTests
{
 [Theory][InlineData(0,ConfidenceBand.Low)][InlineData(49,ConfidenceBand.Low)][InlineData(50,ConfidenceBand.Moderate)][InlineData(75,ConfidenceBand.High)][InlineData(90,ConfidenceBand.VeryHigh)][InlineData(100,ConfidenceBand.VeryHigh)]public void Confidence_boundaries_are_clamped_and_banded(int score,ConfidenceBand band){var value=ExplanationEngine.Calibrate(score,1,0,1,0);Assert.Equal(Math.Clamp(score,0,99),value.Score);Assert.Equal(band,value.Band);Assert.Equal(ExplanationEngine.CalibrationVersion,value.CalibrationVersion);}
 [Fact]public async Task Contradictory_evidence_reduces_confidence_and_is_exposed(){var rule=Rule("disk","Disk issue",80,["DISK_BAD"]);var engine=Engine([rule]);var baseline=await engine.DiagnoseAsync([Finding("DISK_BAD")],CancellationToken.None);var contradicted=await engine.DiagnoseAsync([Finding("DISK_BAD"),Finding("DISK_BAD_HEALTHY")],CancellationToken.None);var explanation=Assert.Single(contradicted.RootCauses).ExplanationDetail;Assert.True(Assert.Single(contradicted.RootCauses).Confidence<Assert.Single(baseline.RootCauses).Confidence);Assert.Single(explanation.CounterEvidence);Assert.True(explanation.Calibration.CounterWeight>0);}
 [Fact]public async Task Identical_inputs_reproduce_confidence_and_rendering(){var engine=Engine([Rule("dns","DNS issue",74,["DNS_BAD"])]);var findings=new[]{Finding("DNS_BAD")};var first=await engine.DiagnoseAsync(findings,CancellationToken.None);var second=await engine.DiagnoseAsync(findings,CancellationToken.None);Assert.Equal(Assert.Single(first.RootCauses).Confidence,Assert.Single(second.RootCauses).Confidence);Assert.Equal(ExplanationRenderer.RenderPlainText(Assert.Single(first.RootCauses).ExplanationDetail),ExplanationRenderer.RenderPlainText(Assert.Single(second.RootCauses).ExplanationDetail));}
 [Fact]public async Task Unknown_finding_has_explicit_unsupported_explanation(){var report=await Engine([]).DiagnoseAsync([Finding("UNKNOWN")],CancellationToken.None);var explanation=Assert.Single(report.Explanations);Assert.Equal(ExplanationSupportState.Unsupported,explanation.State);Assert.Equal("unsupported",explanation.RuleId);Assert.Contains("no repair",explanation.NextStep,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Competing_matches_are_listed_as_alternatives(){var engine=Engine([Rule("primary","Primary cause",85,["A"]),Rule("alternative","Alternative cause",70,["A"])]);var report=await engine.DiagnoseAsync([Finding("A")],CancellationToken.None);var primary=report.RootCauses.Single(item=>item.Id=="primary").ExplanationDetail;Assert.Contains(primary.Alternatives,item=>item.RuleId=="alternative");}
 [Fact]public async Task Historical_comparison_explains_confidence_change(){var engine=Engine([Rule("cause","Cause",70,["A"],any:["B"])]);var previous=await engine.DiagnoseAsync([Finding("A"),Finding("B")],CancellationToken.None);var current=await engine.DiagnoseAsync([Finding("A"),Finding("B"),Finding("A_HEALTHY")],previous,CancellationToken.None);Assert.Contains("changed from",Assert.Single(current.RootCauses).ExplanationDetail.ChangeOverTime,StringComparison.OrdinalIgnoreCase);}
 [Fact]public void Plain_text_rendering_is_culture_stable(){var explanation=ExplanationEngine.Unsupported("Unsupported evidence.");var original=CultureInfo.CurrentCulture;try{CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo("fr-FR");var french=ExplanationRenderer.RenderPlainText(explanation);CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo("en-US");Assert.Equal(french,ExplanationRenderer.RenderPlainText(explanation));}finally{CultureInfo.CurrentCulture=original;}}
 [Fact]public void Rendering_snapshot_contains_standard_sections(){var text=ExplanationRenderer.RenderPlainText(ExplanationEngine.Unsupported("No matching rule."));var expected="Problem: Unsupported diagnosis\nState: Unsupported\nRationale: No matching rule.\nConfidence: 0% (Low) - Evidence is insufficient for a reliable machine-specific conclusion.\nAlternatives: None identified.\nCounter-evidence: None observed.\nImpact: Impact cannot be determined from the available rule set.\nUrgency: Review when more evidence is available.\nNext step: Inspect the cited finding and collect additional supported evidence; no repair is recommended.\nChange over time: No supported historical comparison is available.";Assert.Equal(expected,text);}
 [Fact]public async Task Supported_explanation_links_every_rule_evidence(){var report=await Engine([Rule("cause","Cause",80,["A","B"])]).DiagnoseAsync([Finding("A"),Finding("B")],CancellationToken.None);var explanation=Assert.Single(report.RootCauses).ExplanationDetail;Assert.Equal(2,explanation.Evidence.Count);Assert.All(explanation.Evidence,item=>Assert.True(item.Supports&&item.Weight>=1));Assert.Equal(ExplanationEngine.RuleVersion,explanation.RuleVersion);Assert.Equal(ExplanationEngine.SchemaVersion,report.ExplanationSchemaVersion);}
 private static DiagnosisEngine Engine(IEnumerable<KnowledgeRule> rules){var confidence=new ConfidenceEngine();return new(new DiagnosticKnowledgeBase(rules),new RuleEngine(),new CorrelationScanner(new EventCorrelationEngine()),new RootCauseAnalyzer(confidence,new RecommendationEngine(),new ExplanationEngine()),new HealthScoreEngine(),new AIReportBuilder(TimeProvider.System));}
 private static KnowledgeRule Rule(string id,string cause,int confidence,IReadOnlyCollection<string> required,IReadOnlyCollection<string>? any=null)=>new(id,cause,$"Explanation for {cause}.",DiagnosticSeverity.Warning,1,null,confidence,required,any??[]);
 private static DiagnosticFinding Finding(string code)=>new("test",code,code,$"Evidence for {code}",DiagnosticSeverity.Warning);
}