namespace WAID.Health;
public enum PredictiveRiskKind{StorageWear,CrashRate,ThermalTrend,MemoryInstability,UpdateFailures,PerformanceDecline}
public enum PredictionState{InsufficientHistory,Suppressed,EmergingRisk}
public enum PredictionValidationOutcome{NotEnoughData,Passed,Uncertain}
public sealed record PredictiveObservation(DateTimeOffset ObservedAtUtc,double Value,string SourceReference);
public sealed record PredictiveFeature(string Name,double Value,string Unit,string FeatureVersion);
public sealed record PredictiveRiskRange(double Minimum,double MostLikely,double Maximum);
public sealed record HealthPrediction(PredictiveRiskKind Kind,PredictionState State,string ModelVersion,TimeSpan Horizon,PredictiveRiskRange RiskRange,double ConfidenceLower,double ConfidenceUpper,IReadOnlyList<PredictiveFeature> Features,IReadOnlyList<string> Evidence,string Explanation,string MonitoringRecommendation,PredictionValidationOutcome ValidationOutcome);
public sealed record PredictiveHealthReport(Guid Id,DateTimeOffset GeneratedAtUtc,string ModelVersion,IReadOnlyList<HealthPrediction> Predictions);
public interface IPredictiveHealthModel{HealthPrediction Predict(PredictiveRiskKind kind,IReadOnlyList<PredictiveObservation> observations,TimeSpan horizon);}
public sealed class TransparentTrendPredictor:IPredictiveHealthModel
{
 public const string Version="transparent-linear-v1";private const int MinimumPoints=5;
 public HealthPrediction Predict(PredictiveRiskKind kind,IReadOnlyList<PredictiveObservation> values,TimeSpan horizon)
 {
  ArgumentNullException.ThrowIfNull(values);if(horizon<=TimeSpan.Zero||horizon>TimeSpan.FromDays(90))throw new ArgumentOutOfRangeException(nameof(horizon));var data=values.OrderBy(x=>x.ObservedAtUtc).ToArray();if(data.Length<MinimumPoints||data[^1].ObservedAtUtc-data[0].ObservedAtUtc<TimeSpan.FromDays(3))return Result(kind,PredictionState.InsufficientHistory,horizon,0,0,0,[],data,"At least five observations spanning three days are required.","Continue local monitoring; no prediction is available.",PredictionValidationOutcome.NotEnoughData);
  var origin=data[0].ObservedAtUtc;var x=data.Select(v=>(v.ObservedAtUtc-origin).TotalDays).ToArray();var y=data.Select(v=>v.Value).ToArray();var slope=Slope(x,y);var intercept=y.Average()-slope*x.Average();var residuals=x.Select((t,i)=>y[i]-(intercept+slope*t)).ToArray();var sigma=Math.Sqrt(residuals.Sum(r=>r*r)/Math.Max(1,residuals.Length-2));var threshold=Threshold(kind);var direction=data.Zip(data.Skip(1),(a,b)=>b.Value>=a.Value).Count(v=>v)/(double)(data.Length-1);var drift=Math.Abs(y.Take(data.Length/2).Average()-y.Skip(data.Length/2).Average());var maximumStep=data.Zip(data.Skip(1),(a,b)=>Math.Abs(b.Value-a.Value)).Max();var projected=intercept+slope*(x[^1]+horizon.TotalDays);var risk=Math.Clamp((slope/threshold)*40+Math.Max(0,projected-y[^1])*2,0,100);var weak=slope<threshold||direction<.7||sigma>Math.Max(1,Math.Abs(slope)*3)||drift>Math.Max(threshold*20,sigma*4)||maximumStep>Math.Max(threshold*8,sigma*2);var state=weak?PredictionState.Suppressed:PredictionState.EmergingRisk;var validation=Backtest(data,kind);var margin=Math.Clamp(sigma*10+15,10,40);var features=new[]{new PredictiveFeature("slopePerDay",Math.Round(slope,4),"units/day","features-v1"),new("sampleCount",data.Length,"count","features-v1"),new("historyDays",Math.Round(x[^1],2),"days","features-v1"),new("monotonicFraction",Math.Round(direction,3),"ratio","features-v1"),new("residualSigma",Math.Round(sigma,3),"units","features-v1"),new("maximumStep",Math.Round(maximumStep,3),"units","features-v1")};var explanation=state==PredictionState.EmergingRisk?$"A sustained {kind} trend of {slope:F2} units/day was observed. This is an emerging-risk estimate, not a failure prediction.":"The observed change is weak, noisy, contradictory, or drifting; prediction is suppressed to reduce false positives.";return Result(kind,state,horizon,risk,Math.Max(0,risk-margin),Math.Min(100,risk+margin),features,data,explanation,"Continue monitoring and verify the underlying evidence before considering maintenance.",validation);
 }
 private static HealthPrediction Result(PredictiveRiskKind k,PredictionState s,TimeSpan h,double likely,double min,double max,IReadOnlyList<PredictiveFeature> f,IReadOnlyList<PredictiveObservation> e,string explanation,string recommendation,PredictionValidationOutcome validation)=>new(k,s,Version,h,new(min,likely,max),Math.Max(0,min),Math.Min(100,max),f,e.Select(x=>x.SourceReference).Distinct().ToArray(),explanation,recommendation,validation);
 private static double Threshold(PredictiveRiskKind k)=>k switch{PredictiveRiskKind.StorageWear=>.5,PredictiveRiskKind.ThermalTrend=>.5,PredictiveRiskKind.PerformanceDecline=>.4,_=>.2};
 private static double Slope(double[] x,double[] y){var ax=x.Average();var ay=y.Average();var denominator=x.Sum(v=>(v-ax)*(v-ax));return denominator==0?0:x.Select((v,i)=>(v-ax)*(y[i]-ay)).Sum()/denominator;}
 private PredictionValidationOutcome Backtest(PredictiveObservation[] data,PredictiveRiskKind kind){if(data.Length<6)return PredictionValidationOutcome.NotEnoughData;var train=data[..^1];var origin=train[0].ObservedAtUtc;var x=train.Select(v=>(v.ObservedAtUtc-origin).TotalDays).ToArray();var y=train.Select(v=>v.Value).ToArray();var slope=Slope(x,y);var predicted=y.Average()-slope*x.Average()+slope*(data[^1].ObservedAtUtc-origin).TotalDays;return Math.Abs(predicted-data[^1].Value)<=Math.Max(Threshold(kind)*3,1)?PredictionValidationOutcome.Passed:PredictionValidationOutcome.Uncertain;}
}
