using Microsoft.Extensions.Logging.Abstractions;
using WAID.Application.Abstractions;
using WAID.Application.Services;
using WAID.Infrastructure.Configuration;
using WAID.Infrastructure.Persistence;
namespace WAID.Infrastructure.Tests;
public sealed class EnterprisePolicyTests
{
 [Fact]public async Task Higher_priority_provider_wins_with_explainable_locked_source(){var low=new Provider(10,"Machine",Doc(new(){[EnterpriseCapability.CloudServices]=true}));var organization=new Provider(100,"Organization",Doc(new(){[EnterpriseCapability.CloudServices]=false}));var service=Service([organization,low],out _);var snapshot=await service.RefreshAsync(CancellationToken.None);var decision=service.Evaluate(EnterpriseCapability.CloudServices);Assert.False(decision.Allowed);Assert.True(decision.Locked);Assert.Equal("Organization",decision.Source);Assert.Equal(EnterprisePolicyState.Active,snapshot.State);}
 [Fact]public async Task Invalid_external_policy_fails_closed_for_every_sensitive_capability(){var service=Service([new ThrowingProvider()],out _);var snapshot=await service.RefreshAsync(CancellationToken.None);Assert.Equal(EnterprisePolicyState.FailClosed,snapshot.State);Assert.Equal("WAID-POLICY-INVALID",snapshot.FailureCode);Assert.All(Enum.GetValues<EnterpriseCapability>(),x=>Assert.False(service.Evaluate(x).Allowed));}
 [Fact]public async Task Refresh_applies_policy_updates_deterministically(){var provider=new Provider(100,"Organization",Doc(new(){[EnterpriseCapability.Monitoring]=true}));var service=Service([provider],out _);await service.RefreshAsync(CancellationToken.None);Assert.True(service.Evaluate(EnterpriseCapability.Monitoring).Allowed);provider.Document=Doc(new(){[EnterpriseCapability.Monitoring]=false});await service.RefreshAsync(CancellationToken.None);Assert.False(service.Evaluate(EnterpriseCapability.Monitoring).Allowed);}
 [Fact]public async Task Rollback_restores_a_previous_valid_snapshot_and_records_state(){var provider=new Provider(100,"Organization",Doc(new(){[EnterpriseCapability.Repairs]=true}));var service=Service([provider],out var repository);var first=await service.RefreshAsync(CancellationToken.None);provider.Document=Doc(new(){[EnterpriseCapability.Repairs]=false});await service.RefreshAsync(CancellationToken.None);var restored=await service.RollbackAsync(first.Id,CancellationToken.None);Assert.Equal(EnterprisePolicyState.RolledBack,restored.State);Assert.True(service.Evaluate(EnterpriseCapability.Repairs).Allowed);Assert.Equal(3,repository.Items.Count);}
 [Fact]public void Bootstrap_blocks_invalid_policy_and_honors_portable_mode_lock(){var path=Path.Combine(Path.GetTempPath(),$"waid-enterprise-{Guid.NewGuid():N}.json");try{File.WriteAllText(path,"{invalid");Assert.False(EnterprisePolicyBootstrap.IsAllowed(path,EnterpriseCapability.PortableMode));File.WriteAllText(path,"{\"version\":1,\"id\":\"org\",\"source\":\"deployment\",\"updatedAtUtc\":\"2026-01-01T00:00:00Z\",\"rules\":{\"portableMode\":false}}");Assert.False(EnterprisePolicyBootstrap.IsAllowed(path,EnterpriseCapability.PortableMode));Assert.True(EnterprisePolicyBootstrap.IsAllowed(path,EnterpriseCapability.Diagnostics));}finally{if(File.Exists(path))File.Delete(path);}}
 [Fact]public async Task SQLite_round_trip_preserves_rules_sources_locks_retention_and_failure_state(){var path=Path.Combine(Path.GetTempPath(),$"waid-policy-{Guid.NewGuid():N}.db");try{var db=new WaidDatabase($"Data Source={path};Pooling=False");await db.InitializeAsync(CancellationToken.None);var repo=new SqliteEnterprisePolicyRepository(db);var snapshot=EnterprisePolicySnapshot.SafeDefault(DateTimeOffset.UtcNow);await repo.SaveAsync(snapshot,CancellationToken.None);var loaded=Assert.Single(await repo.GetRecentAsync(10,CancellationToken.None));Assert.Equal(snapshot.Id,loaded.Id);Assert.Equal(snapshot.Retention,loaded.Retention);Assert.Equal(snapshot.Rules[EnterpriseCapability.Plugins],loaded.Rules[EnterpriseCapability.Plugins]);}finally{Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();if(File.Exists(path))File.Delete(path);}}
 static EnterprisePolicyService Service(IEnumerable<IEnterprisePolicyProvider>providers,out MemoryRepository repository){repository=new();return new(providers,repository,new Audit(),TimeProvider.System,NullLogger<EnterprisePolicyService>.Instance);}
 static EnterprisePolicyDocument Doc(Dictionary<EnterpriseCapability,bool>rules)=>new(1,"org-policy","test",DateTimeOffset.UtcNow,rules,new(7,730,14));
 sealed class Provider(int priority,string name,EnterprisePolicyDocument?document):IEnterprisePolicyProvider{public int Priority=>priority;public string Name=>name;public EnterprisePolicyDocument?Document{get;set;}=document;public Task<EnterprisePolicyDocument?>ReadAsync(CancellationToken token)=>Task.FromResult(Document);}
 sealed class ThrowingProvider:IEnterprisePolicyProvider{public int Priority=>100;public string Name=>"Invalid organization policy";public Task<EnterprisePolicyDocument?>ReadAsync(CancellationToken token)=>throw new InvalidDataException("invalid");}
 sealed class MemoryRepository:IEnterprisePolicyRepository{public List<EnterprisePolicySnapshot>Items{get;}=[];public Task SaveAsync(EnterprisePolicySnapshot snapshot,CancellationToken token){Items.Insert(0,snapshot);return Task.CompletedTask;}public Task<IReadOnlyList<EnterprisePolicySnapshot>>GetRecentAsync(int count,CancellationToken token)=>Task.FromResult<IReadOnlyList<EnterprisePolicySnapshot>>(Items.Take(count).ToArray());}
 sealed class Audit:IAuditTrailService{public Task<AuditWriteResult>AppendAsync(AuditRecord record,CancellationToken token)=>Task.FromResult(new AuditWriteResult(true,record.Id));public Task<IReadOnlyList<AuditRecord>>SearchAsync(AuditQuery query,CancellationToken token)=>Task.FromResult<IReadOnlyList<AuditRecord>>([]);public Task ApplyRetentionAsync(CancellationToken token)=>Task.CompletedTask;}
}