using Microsoft.Extensions.Logging.Abstractions;
using WAID.Application.Abstractions;
using WAID.Infrastructure.Diagnostics;
using WAID.Infrastructure.Persistence;
using WAID.Infrastructure.PowerShell;
namespace WAID.Infrastructure.Tests;
public sealed class NetworkDiagnosticTests
{
 private static readonly DateTimeOffset Now=DateTimeOffset.Parse("2026-07-21T12:00:00Z");
 [Fact]public void Dns_failure_identifies_dns_layer_and_allows_evidenced_reset(){var findings=NetworkDiagnosticCenter.Evaluate(Snapshot(tests:[Test("dns",NetworkLayer.Dns,NetworkTestStatus.Failed,"DNS query failed")]));var finding=Assert.Single(findings);Assert.Equal(NetworkLayer.Dns,finding.Layer);Assert.Equal("waid.dns-reset",finding.RepairId);Assert.True(finding.ResetSupported);}
 [Fact]public void Missing_route_identifies_lan_layer_without_speculative_reset(){var findings=NetworkDiagnosticCenter.Evaluate(Snapshot(tests:[Test("gateway",NetworkLayer.LanGateway,NetworkTestStatus.TimedOut,"Gateway timeout")]));var finding=Assert.Single(findings);Assert.Equal(NetworkLayer.LanGateway,finding.Layer);Assert.Null(finding.RepairId);Assert.False(finding.ResetSupported);}
 [Fact]public void Proxy_and_application_failure_are_correlated(){var findings=NetworkDiagnosticCenter.Evaluate(Snapshot(proxy:new(true,"Manual","proxy.example:8080","[redacted]"),tests:[Test("http",NetworkLayer.Application,NetworkTestStatus.Failed,"Endpoint failed")]));Assert.Contains(findings,f=>f.Layer==NetworkLayer.Proxy&&f.Code=="PROXY_PATH_FAILURE");}
 [Fact]public void Captive_portal_redirect_has_specific_finding(){var finding=Assert.Single(NetworkDiagnosticCenter.Evaluate(Snapshot(tests:[Test("http",NetworkLayer.Application,NetworkTestStatus.Failed,"Unexpected redirect may indicate a captive portal.")])));Assert.Equal("CAPTIVE_PORTAL",finding.Code);}
 [Fact]public void Offline_adapter_is_reported_before_reset(){var finding=Assert.Single(NetworkDiagnosticCenter.Evaluate(Snapshot(adapters:[new("1","Ethernet","802.3","Down",[],[],null,null,null)])));Assert.Equal(NetworkLayer.Adapter,finding.Layer);Assert.False(finding.ResetSupported);}
 [Fact]public void Timeout_is_distinct_from_hard_failure(){var finding=Assert.Single(NetworkDiagnosticCenter.Evaluate(Snapshot(tests:[Test("gateway",NetworkLayer.LanGateway,NetworkTestStatus.TimedOut,"Timed out")])));Assert.Equal("Information",finding.Severity);Assert.Equal(.75,finding.Confidence);}
 [Fact]public void Missing_default_route_identifies_lan_configuration(){var snapshot=Snapshot() with{Routes=[]};var finding=Assert.Single(NetworkDiagnosticCenter.Evaluate(snapshot));Assert.Equal("DEFAULT_ROUTE_MISSING",finding.Code);Assert.Equal(NetworkLayer.LanGateway,finding.Layer);}
 [Fact]public void Tcpip_reset_requires_missing_ip_evidence(){var adapter=new NetworkAdapterSnapshot("1","Ethernet","802.3","Up",[],["192.168.1.0/24"],"192.168.1.0/24",null,null);var finding=Assert.Single(NetworkDiagnosticCenter.Evaluate(Snapshot(adapters:[adapter])));Assert.Equal("waid.tcpip-reset",finding.RepairId);Assert.True(finding.ResetSupported);}
 [Fact]public async Task Cancellation_propagates_without_persistence(){var repository=new MemoryRepository();var center=new NetworkDiagnosticCenter(new CancellingProvider(),repository,NullLogger<NetworkDiagnosticCenter>.Instance,Path.GetTempPath());using var cancellation=new CancellationTokenSource();cancellation.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>center.AnalyzeAsync(new(),cancellation.Token));Assert.Null(repository.Saved);}
 [Fact]public async Task Complete_workflow_collects_classifies_and_persists(){var repository=new MemoryRepository();var center=new NetworkDiagnosticCenter(new FixedProvider(Snapshot(tests:[Test("dns",NetworkLayer.Dns,NetworkTestStatus.Failed,"Failed")])),repository,NullLogger<NetworkDiagnosticCenter>.Instance,Path.GetTempPath());var report=await center.AnalyzeAsync(new("example.invalid"),CancellationToken.None);Assert.Same(report,repository.Saved);Assert.Equal(NetworkLayer.Dns,Assert.Single(report.Findings).Layer);Assert.NotEmpty(report.Topology);}
 [Fact]public async Task Sqlite_round_trip_preserves_tests_latency_loss_and_repairs(){var path=Path.Combine(Path.GetTempPath(),$"waid-network-{Guid.NewGuid():N}.db");try{var db=new WaidDatabase($"Data Source={path};Pooling=False");await db.InitializeAsync(CancellationToken.None);var repository=new SqliteNetworkHealthRepository(db);var snapshot=Snapshot(tests:[new("gateway",NetworkLayer.LanGateway,"Gateway",NetworkTestStatus.Passed,TimeSpan.FromMilliseconds(12),12,0,"ok","test")]);var report=new NetworkHealthReport(Guid.NewGuid(),Now,snapshot,NetworkDiagnosticCenter.Evaluate(snapshot),["Computer -> Ethernet"],snapshot.Limitations);await repository.SaveAsync(report,CancellationToken.None);var loaded=await repository.GetLatestAsync(CancellationToken.None);Assert.Equal(report.Id,loaded!.Id);Assert.Equal(12,Assert.Single(loaded.Snapshot.Tests).LatencyMilliseconds);}finally{Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();if(File.Exists(path))File.Delete(path);}}
 [Theory][InlineData(100)][InlineData(16000)]public void Probe_timeout_must_be_bounded(int milliseconds)=>Assert.Throws<ArgumentOutOfRangeException>(()=>new NetworkProbeOptions(TimeoutMilliseconds:milliseconds).Validate());
 [Fact]public async Task Windows_provider_masks_addresses_and_proxy_credentials_before_storage(){const string json="""{"adapters":[{"id":"1","name":"Ethernet","type":"802.3","status":"Up","addresses":["192.168.20.44"],"dns":["10.0.0.53"],"gateway":"192.168.20.1","wifi":null,"signal":null}],"routes":[{"destination":"0.0.0.0/0","nextHop":"192.168.20.1","metric":10,"interfaceId":"1"}],"proxy":{"enabled":true,"mode":"Manual","host":"http://user:secret@proxy.example:8080","bypass":"internal.example"},"vpnActive":false,"firewall":"Enabled","services":[],"tests":[]}""";var snapshot=await new WindowsNetworkEvidenceProvider(new JsonRunner(json)).CollectAsync(new(),CancellationToken.None);var adapter=Assert.Single(snapshot.Adapters);Assert.Equal("192.168.20.0/24",Assert.Single(adapter.Addresses));Assert.Equal("192.168.20.0/24",adapter.Gateway);Assert.Equal("proxy.example:8080",snapshot.Proxy.ProxyHost);Assert.Equal("[redacted]",snapshot.Proxy.BypassSummary);}
 private static NetworkTestResult Test(string id,NetworkLayer layer,NetworkTestStatus status,string detail)=>new(id,layer,id,status,TimeSpan.FromMilliseconds(10),null,status==NetworkTestStatus.Passed?0:100,detail,"test");
 private static NetworkSnapshot Snapshot(IReadOnlyList<NetworkAdapterSnapshot>? adapters=null,NetworkProxySnapshot? proxy=null,IReadOnlyList<NetworkTestResult>? tests=null)=>new(Now,adapters??[new("1","Ethernet","802.3","Up",["192.168.1.0/24"],["192.168.1.0/24"],"192.168.1.0/24",null,null)],[new("0.0.0.0/0","192.168.1.0/24",10,"1")],proxy??new(false,"Direct",null,"[redacted]"),false,"Enabled",[],tests??[],["redacted"]);
 private sealed class FixedProvider(NetworkSnapshot snapshot):INetworkEvidenceProvider{public Task<NetworkSnapshot> CollectAsync(NetworkProbeOptions options,CancellationToken token){token.ThrowIfCancellationRequested();return Task.FromResult(snapshot);}}
 private sealed class CancellingProvider:INetworkEvidenceProvider{public Task<NetworkSnapshot> CollectAsync(NetworkProbeOptions options,CancellationToken token){token.ThrowIfCancellationRequested();throw new InvalidOperationException();}}
 private sealed class JsonRunner(string json):IPowerShellRunner{public Task<PowerShellResult> RunAsync(string script,IReadOnlyDictionary<string,object?> parameters,CancellationToken token)=>Task.FromResult(new PowerShellResult([json],[]));}
 private sealed class MemoryRepository:INetworkHealthRepository{public NetworkHealthReport? Saved{get;private set;}public Task<NetworkHealthReport?> GetLatestAsync(CancellationToken token)=>Task.FromResult(Saved);public Task SaveAsync(NetworkHealthReport report,CancellationToken token){Saved=report;return Task.CompletedTask;}}
}
