using System.Security.Cryptography;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using WAID.Application.Abstractions;
using WAID.Application.Plugins;
using WAID.Infrastructure.Plugins;
using WAID.Plugin.Sample;
namespace WAID.Infrastructure.Tests;
public sealed class PluginCertificationTests
{
 [Fact] public void Traversal_entry_assembly_is_blocked(){using var package=new Package();var path=package.Manifest(new PluginManifest("com.vendor.escape","Escape","1.0.0","WAID Engineering","1.0.0","../outside.dll","2",["Scanner"],["SystemRead"]));var result=new PluginCertificationService().Evaluate(path,new Version(1,0,0),Policy());Assert.False(result.Certified);Assert.Contains(result.Checks,x=>x.Code=="assembly.containment"&&!x.Passed);}
 [Fact] public void Permission_denied_by_host_policy_is_blocked(){using var package=new Package();package.CopySample();var path=package.Manifest(Manifest(permissions:["EnvironmentRead"]));var result=new PluginCertificationService().Evaluate(path,new Version(1,0,0),new PluginSecurityPolicy(["WAID Engineering"],false,new HashSet<PluginPermission>{PluginPermission.SystemRead}));Assert.False(result.Certified);Assert.Contains(result.Checks,x=>x.Code=="policy.permission.EnvironmentRead"&&!x.Passed);}
 [Fact] public void Incompatible_host_is_reported_and_never_loaded(){using var package=new Package();package.CopySample();package.Manifest(Manifest(minimum:"99.0.0"));var catalog=new PluginCatalog();var plugins=new PluginLoader().Load(package.Root,new Version(1,0,0),Policy(),catalog);Assert.Empty(plugins);Assert.Equal(PluginState.Incompatible,Assert.Single(catalog.Items).State);Assert.Contains("Requires host",catalog.Items[0].Detail,StringComparison.Ordinal);}
 [Fact] public void Assembly_integrity_mismatch_fails_certification(){using var package=new Package();package.CopySample();var result=new PluginCertificationService().Evaluate(package.Manifest(Manifest(hash:new string('0',64))),new Version(1,0,0),Policy());Assert.False(result.Certified);Assert.Contains(result.Checks,x=>x.Code=="assembly.sha256"&&!x.Passed);}
 [Fact] public void Sample_plugin_conforms_and_collectible_context_can_be_released(){using var package=new Package();package.CopySample();package.Manifest(Manifest());var catalog=new PluginCatalog();var loader=new PluginLoader();var plugins=loader.Load(package.Root,new Version(1,0,0),Policy(),catalog);Assert.Equal("2",Assert.IsAssignableFrom<IWaidPluginV2>(Assert.Single(plugins)).Sdk.ApiVersion);Assert.Equal(PluginState.Loaded,Assert.Single(catalog.Items).State);Assert.Equal(1,loader.ReleaseLoadContexts());Assert.Equal(0,loader.ReleaseLoadContexts());}
 [Fact] public void Controlled_registry_refuses_undeclared_extension_point(){var services=new ServiceCollection();var sdk=new PluginSdkDescriptor("2",new HashSet<PluginCapability>{PluginCapability.ReportContributor},new HashSet<PluginPermission>{PluginPermission.ReportWrite},[]);var registry=new ControlledPluginServiceRegistry(services,sdk);Assert.Throws<UnauthorizedAccessException>(()=>registry.AddScanner<EnvironmentScanner>());Assert.Empty(services);}
 [Fact] public void Missing_required_plugin_dependency_is_blocked(){using var package=new Package();package.CopySample();package.Manifest(Manifest(dependencies:[new PluginDependency("com.vendor.required","1.0.0",false)]));var catalog=new PluginCatalog();var loaded=new PluginLoader().Load(package.Root,new Version(1,0,0),Policy(),catalog);Assert.Empty(loaded);Assert.Equal(PluginState.Incompatible,Assert.Single(catalog.Items).State);Assert.Contains("com.vendor.required",catalog.Items[0].Detail,StringComparison.Ordinal);}
 static PluginSecurityPolicy Policy()=>new(["WAID Engineering"]);
 static PluginManifest Manifest(string minimum="1.0.0",IReadOnlyCollection<string>? permissions=null,IReadOnlyCollection<PluginDependency>? dependencies=null,string? hash=null)=>new("com.waid.sample","WAID Sample Scanner","1.0.0","WAID Engineering",minimum,"WAID.Plugin.Sample.dll","2",["Scanner"],permissions??["EnvironmentRead"],dependencies??[],hash);
 sealed class Package:IDisposable{public string Root{get;}=Path.Combine(Path.GetTempPath(),$"waid-sdk-{Guid.NewGuid():N}");public Package()=>Directory.CreateDirectory(Root);public void CopySample()=>File.Copy(typeof(SamplePlugin).Assembly.Location,Path.Combine(Root,"WAID.Plugin.Sample.dll"));public string Manifest(PluginManifest manifest){var path=Path.Combine(Root,$"{manifest.Id}.waid-plugin.json");File.WriteAllText(path,JsonSerializer.Serialize(manifest,new JsonSerializerOptions{WriteIndented=true}));return path;}public void Dispose(){GC.Collect();GC.WaitForPendingFinalizers();GC.Collect();try{Directory.Delete(Root,true);}catch(UnauthorizedAccessException){}}}
}