using WAID.Infrastructure;
namespace WAID.Infrastructure.Tests;
public sealed class PortableWorkspaceTests:IDisposable
{
 private readonly string _root=Path.Combine(Path.GetTempPath(),$"waid-portable-tests-{Guid.NewGuid():N}");
 [Fact]public void Relative_workspace_becomes_isolated_absolute_portable_options(){Directory.CreateDirectory(_root);var prior=Environment.CurrentDirectory;try{Environment.CurrentDirectory=_root;using var context=WaidWorkspaceContext.Resolve(["--portable","--workspace","case-a"],_root);var options=context.CreateHostOptions();Assert.True(Path.IsPathFullyQualified(context.Status.RootPath));Assert.Equal(context.Status.RootPath,options.DataDirectory);Assert.Null(options.MachineConfigurationPath);Assert.Null(options.PolicyConfigurationPath);Assert.StartsWith(context.Status.RootPath,Path.Combine(options.DataDirectory,"waid.db"),StringComparison.OrdinalIgnoreCase);}finally{Environment.CurrentDirectory=prior;}}
 [Fact]public void Same_workspace_rejects_second_instance_but_other_workspace_coexists(){using var first=WaidWorkspaceContext.Resolve(["--portable","--workspace",Path.Combine(_root,"one")],_root);var error=Assert.Throws<WaidWorkspaceException>(()=>WaidWorkspaceContext.Resolve(["--portable","--workspace",Path.Combine(_root,"one")],_root));Assert.Equal("WAID-PORTABLE-IN-USE",error.Code);using var other=WaidWorkspaceContext.Resolve(["--portable","--workspace",Path.Combine(_root,"two")],_root);Assert.NotEqual(first.Status.RootPath,other.Status.RootPath);}
 [Fact]public void Cleanup_is_marker_confined_and_requires_approval(){using var context=WaidWorkspaceContext.Resolve(["--portable","--workspace",Path.Combine(_root,"clean")],_root);File.WriteAllText(Path.Combine(context.Status.RootPath,"data.txt"),"private");Assert.Throws<WaidWorkspaceException>(()=>context.CleanPortableWorkspace(false));context.CleanPortableWorkspace(true);Assert.False(File.Exists(Path.Combine(context.Status.RootPath,"data.txt")));Assert.True(File.Exists(Path.Combine(context.Status.RootPath,".waid-portable-workspace")));}
 [Fact]public void Non_directory_media_path_returns_typed_permission_failure(){Directory.CreateDirectory(_root);var file=Path.Combine(_root,"media");File.WriteAllText(file,"read only target");var error=Assert.Throws<WaidWorkspaceException>(()=>WaidWorkspaceContext.Resolve(["--portable","--workspace",file],_root));Assert.Equal("WAID-PORTABLE-READONLY",error.Code);}
 public void Dispose(){if(Directory.Exists(_root))Directory.Delete(_root,true);}
}
