using Microsoft.Extensions.Logging.Abstractions;using WAID.Application.Abstractions;using WAID.Infrastructure.Diagnostics;using WAID.Infrastructure.Persistence;
namespace WAID.Infrastructure.Tests;public sealed class WindowsUpdateIntelligenceTests{private static readonly DateTimeOffset Now=new(2026,7,21,12,0,0,TimeSpan.Zero);
[Theory][InlineData("0X8024402C",UpdateCause.Network)][InlineData("0X80072EE2",UpdateCause.Network)][InlineData("0X800F081F",UpdateCause.Servicing)][InlineData("0X80073712",UpdateCause.Servicing)][InlineData("0X8024002E",UpdateCause.Policy)][InlineData("0X80070070",UpdateCause.Storage)][InlineData("0XDEADBEEF",UpdateCause.Unknown)]public void Error_mapping_is_offline_and_cause_specific(string code,UpdateCause expected)=>Assert.Equal(expected,ErrorCatalog.Map(code).Cause);
[Fact]public void Correlation_distinguishes_all_supported_cause_families(){var snapshot=Snapshot(attempts:[Attempt("0X8024402C"),Attempt("0X800F081F")],services:[new("BITS","Stopped","Auto","Service:BITS")],policy:new(true,true,"Disabled","Policy"),reboot:true,free:4L*1024*1024*1024,corrupt:true);var diagnoses=WindowsUpdateIntelligence.Diagnose(snapshot);Assert.Equal(new[]{UpdateCause.Network,UpdateCause.Servicing,UpdateCause.Policy,UpdateCause.Reboot,UpdateCause.Storage,UpdateCause.Service}.Order(),diagnoses.Select(x=>x.Cause).Order());Assert.All(diagnoses,x=>Assert.NotEmpty(x.Evidence));}
[Fact]public void Pending_reboot_is_not_misreported_as_servicing_or_network(){var diagnosis=Assert.Single(WindowsUpdateIntelligence.Diagnose(Snapshot(reboot:true)));Assert.Equal(UpdateCause.Reboot,diagnosis.Cause);Assert.Equal(.98,diagnosis.Confidence);}
[Fact]public void Repair_orchestration_orders_restart_storage_services_network_servicing_policy_and_never_removes_updates(){var snapshot=Snapshot(reboot:true);var diagnoses=Enum.GetValues<UpdateCause>().Where(x=>x!=UpdateCause.Unknown).Select(x=>new UpdateDiagnosis(x,x.ToString(),"Evidence",.9,"Warning",[new("signal","value","source",Now)])).ToArray();var plan=WindowsUpdateIntelligence.Plan(diagnoses,snapshot);Assert.Equal(new[]{"restart","free-space","services","network","dism","policy"},plan.Steps.Select(x=>x.Id));Assert.All(plan.Steps,x=>{Assert.True(x.RequiresApproval);Assert.False(x.RemovesUpdates);Assert.NotEmpty(x.Prerequisites);});Assert.Contains("never removes",plan.SafetyNotice,StringComparison.OrdinalIgnoreCase);}
[Fact]public void Repair_simulation_requires_explicit_approval_and_does_not_execute(){var step=new UpdateRepairStep(1,"dism","Repair","Supported",["Administrator approval"],true,true,false,true);var planner=new UpdateRepairPlanner();var denied=planner.Simulate(step,false);Assert.False(denied.Allowed);Assert.Empty(denied.Commands);var approved=planner.Simulate(step,true);Assert.True(approved.Allowed);Assert.Contains("Simulation only",approved.Message);Assert.Contains(approved.Commands,x=>x.StartsWith("DISM",StringComparison.OrdinalIgnoreCase));}
[Fact]public async Task Analyzer_orchestrates_provider_repository_and_plan(){var repository=new MemoryRepository();var engine=new WindowsUpdateIntelligence(new SnapshotProvider(Snapshot(attempts:[Attempt("0X80070070")])),repository,NullLogger<WindowsUpdateIntelligence>.Instance);var report=await engine.AnalyzeAsync(CancellationToken.None);Assert.Same(report,repository.Saved);Assert.Equal(UpdateCause.Storage,Assert.Single(report.Diagnoses).Cause);Assert.Equal("free-space",Assert.Single(report.Plan.Steps).Id);}
[Fact]public async Task Sqlite_round_trip_preserves_attempts_evidence_plan_and_outcome_schema(){var path=Path.Combine(Path.GetTempPath(),$"waid-wu-{Guid.NewGuid():N}.db");try{var db=new WaidDatabase($"Data Source={path};Pooling=False");await db.InitializeAsync(CancellationToken.None);var repo=new SqliteWindowsUpdateHealthRepository(db);var snapshot=Snapshot(attempts:[Attempt("0X800F081F")]);var diagnoses=WindowsUpdateIntelligence.Diagnose(snapshot);var report=new WindowsUpdateHealthReport(Guid.NewGuid(),Now,snapshot.Attempts,diagnoses,WindowsUpdateIntelligence.Plan(diagnoses,snapshot),false,[]);await repo.SaveAsync(snapshot,report,CancellationToken.None);var loaded=await repo.GetLatestAsync(CancellationToken.None);Assert.Equal(report.Id,loaded!.Id);Assert.Single(loaded.Attempts);Assert.NotEmpty(loaded.Diagnoses);Assert.NotEmpty(loaded.Plan.Steps);}finally{Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();if(File.Exists(path))File.Delete(path);}}
private static UpdateAttempt Attempt(string code)=>new(Now,"Security Update for Windows (KB1234567)","KB1234567",code,UpdateAttemptState.Failed,"history");private static UpdateEvidenceSnapshot Snapshot(IReadOnlyList<UpdateAttempt>? attempts=null,IReadOnlyList<UpdateServiceState>? services=null,UpdatePolicyState? policy=null,bool reboot=false,long free=100L*1024*1024*1024,bool corrupt=false)=>new(Now,attempts??[],services??[],policy??new(false,false,"Not managed","policy"),new(corrupt,corrupt,corrupt?"repairable":"healthy","CBS","servicing"),reboot,free,[],[]);
private sealed class SnapshotProvider(UpdateEvidenceSnapshot snapshot):IWindowsUpdateEvidenceProvider{public Task<UpdateEvidenceSnapshot> CollectAsync(CancellationToken cancellationToken)=>Task.FromResult(snapshot);}private sealed class MemoryRepository:IWindowsUpdateHealthRepository{public WindowsUpdateHealthReport? Saved{get;private set;}public Task<WindowsUpdateHealthReport?> GetLatestAsync(CancellationToken cancellationToken)=>Task.FromResult(Saved);public Task SaveAsync(UpdateEvidenceSnapshot snapshot,WindowsUpdateHealthReport report,CancellationToken cancellationToken){Saved=report;return Task.CompletedTask;}}
}
