[CmdletBinding()]
param([Parameter(Mandatory)][ValidateSet('Windows10','Windows11','Windows11Arm64','Administrator','StandardUser','Offline','UnsupportedHardware')][string]$Scenario,[Parameter(Mandatory)][string]$ApplicationPath,[string]$OutputDirectory=(Join-Path $PSScriptRoot '..\artifacts\release-evidence'))
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$releaseManifest=Get-Content -Raw -LiteralPath (Join-Path $root 'release\release-candidate.json')|ConvertFrom-Json;$commit=(& git -C $root rev-parse HEAD).Trim();$resolvedApplication=(Resolve-Path -LiteralPath $ApplicationPath).Path;$os=Get-CimInstance Win32_OperatingSystem;$version=[Environment]::OSVersion.Version;$architecture=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$isAdministrator=([Security.Principal.WindowsPrincipal]$identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if($Scenario-eq'Windows10'-and$version.Build-ge22000){throw"Windows 10 is required; detected build $($version.Build)."};if($Scenario-in'Windows11','Windows11Arm64'-and$version.Build-lt22000){throw"Windows 11 is required; detected build $($version.Build)."};if($Scenario-eq'Windows11Arm64'-and$architecture-ne'Arm64'){throw"ARM64 is required; detected $architecture."};if($Scenario-eq'Administrator'-and-not$isAdministrator){throw'Run from elevated PowerShell.'};if($Scenario-eq'StandardUser'-and$isAdministrator){throw'Run from non-elevated PowerShell.'}
$checks=@('UI launch behavior','All navigation pages open, including Plugins','Scanner progress and terminal status are visible','Permission failures are visible and remaining scanners continue','Timeout or unavailable checks show degraded status and partial evidence count','Restore-point and backup safeguards are shown before repair','Cancel repair approval and verify no repair starts','Keyboard navigation and focus order work','Screen reader announces actionable controls and severity','High contrast and 200% text scaling remain usable')
if($Scenario-eq'Offline'){$checks+='Scan, diagnosis, knowledge lookup, and reports complete without network access'};if($Scenario-eq'UnsupportedHardware'){$checks+='Unavailable hardware providers are explicit and never reported healthy'}
New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null;$process=Start-Process -FilePath $resolvedApplication -PassThru;$results=foreach($check in $checks){do{$answer=(Read-Host "$check [pass/fail]").Trim().ToLowerInvariant()}until($answer-in'pass','fail');[pscustomobject]@{Check=$check;Result=$answer}}
$scannerResults=@();do{$scanner=(Read-Host 'Scanner id (blank to finish)').Trim();if($scanner){$status=Read-Host 'Status (Success/Unavailable/TimedOut/PermissionDenied/Cancelled/Failed)';$scannerResults+=[pscustomobject]@{Scanner=$scanner;Status=$status}}}while($scanner)
$report=[pscustomobject]@{SchemaVersion=2;CandidateId=$releaseManifest.candidateId;ProductVersion=$releaseManifest.productVersion;Commit=$commit;Scenario=$Scenario;TimestampUtc=[DateTimeOffset]::UtcNow;OSEdition=$os.Caption;OSVersion=$os.Version;OSBuild=$version.Build;Architecture=$architecture;ApplicationVersion=[Diagnostics.FileVersionInfo]::GetVersionInfo($resolvedApplication).ProductVersion;ApplicationFile=[IO.Path]::GetFileName($resolvedApplication);ArtifactSha256=(Get-FileHash -LiteralPath $resolvedApplication -Algorithm SHA256).Hash;IsAdministrator=$isAdministrator;ScannerResults=$scannerResults;PermissionFailures=@($scannerResults|Where-Object Status-eq'PermissionDenied').Count;SafeguardsVerified=-not($results|Where-Object{$_.Check-like'*safeguard*'-and$_.Result-ne'pass'});UiLaunchBehavior=($results|Where-Object Check-eq'UI launch behavior').Result;PassCriteria='Every required check passes and every scanner has an accepted terminal status.';Results=$results;Passed=-not($results.Result-contains'fail')}
$destination=Join-Path $OutputDirectory("{0}-{1:yyyyMMdd-HHmmss}.json"-f$Scenario,[DateTime]::UtcNow);$report|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $destination -Encoding utf8;Write-Host"Validation report: $destination";if(-not$report.Passed){exit 1}
